#build stage
FROM public.ecr.aws/docker/library/golang:alpine AS builder
LABEL Name=measure-go Version=0.0.1
LABEL org.opencontainers.image.source=https://github.com/measure-sh/measure/tree/$IMAGE_REF/measure-backend/measure-go
LABEL org.opencontainers.image.description="Measure API Server"
LABEL org.opencontainers.image.licenses=Apache-2.0
ARG IMAGE_REF
RUN apk add --no-cache git
WORKDIR /go/src/app
COPY go.mod go.sum ./
RUN go get -d -v ./...
COPY . .
# RUN go build -o /go/bin/app -v ./...
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -o /go/bin/app -v .

#final stage
FROM public.ecr.aws/docker/library/alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/bin/app /app
ENTRYPOINT /app
EXPOSE 8080
