services:
  dashboard:
    build:
      dockerfile: dockerfile.prod
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    volumes: !reset null
    restart: unless-stopped

  api:
    environment:
      - GIN_MODE=release
    develop: !reset null
    restart: unless-stopped

  cleanup:
    environment:
      - GIN_MODE=release
    develop: !reset null
    restart: unless-stopped

  migrator:
    develop: !reset null

  symbolicator:
    volumes:
      # no need to !reset or !override as compose merges entries
      # for `volumes` because target shares as a unique key
      #
      # see: https://docs.docker.com/reference/compose-file/merge/#unique-resources
      - ./symbolicator/config.prod.yml:/etc/symbolicator/config.yml:ro
    restart: unless-stopped

  clickhouse:
    ports:
      !reset # see: https://docs.docker.com/compose/compose-file/13-merge/#reset-value
      - "9000:9000/tcp"
    restart: unless-stopped
