services:
  dashboard:
    build:
      dockerfile: dockerfile.prod
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    volumes: !reset null

  api:
    environment:
      - GIN_MODE=release
    develop: !reset null

  cleanup:
    environment:
      - GIN_MODE=release
    develop: !reset null

  symbolicator-android:
    environment:
      - DEVELOPMENT_MODE=false
    develop: !reset null

  clickhouse:
    ports: !reset # see: https://docs.docker.com/compose/compose-file/13-merge/#reset-value
      - "9000:9000/tcp"