name: measure
services:
  api:
    container_name: api
    build:
      context: ../measure-backend/measure-go
    ports:
      - "8080:8080"
    env_file:
      - ../measure-backend/measure-go/.env
    develop:
      watch:
        - path: ../measure-backend/measure-go
          action: rebuild
    depends_on:
      - clickhouse
      # - symbolicator
      - symbolicator-retrace

  symbolicator-retrace:
    container_name: symbolicator-retrace
    build:
      context: ../measure-backend/symbolicator-retrace
    ports:
      - "8181:8181"
    env_file:
      - ../measure-backend/symbolicator-retrace/.env
    volumes:
      - symbolicator-volume:/data
    develop:
      watch:
        - path: ../measure-backend/symbolicator-retrace
          action: rebuild

  # symbolicator:
  #   build:
  #     context: ../measure-backend/symbolicator
  #   ports:
  #     - "8181:8181"
  #   env_file:
  #     - ../measure-backend/symbolicator/.env
  #   volumes:
  #     - symbolicator-volume:/data
  #   develop:
  #     watch:
  #       - path: ../measure-backend/symbolicator
  #         action: rebuild

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:23
    ports:
      - "9000:9000/tcp"
      - "8123:8123"
    ulimits:
      nofile: 262144
    volumes:
      - clickhouse-volume:/var/lib/clickhouse
      - clickhouse-volume:/var/log/clickhouse-server

volumes:
  clickhouse-volume:
  symbolicator-volume:
