name: measure
services:
  api:
    container_name: api
    build:
      context: ../measure-backend/measure-go
    ports:
      - "8080:8080"
    env_file:
      - ../measure-backend/measure-go/.env
    develop:
      watch:
        - path: ../measure-backend/measure-go
          action: rebuild
    depends_on:
      - clickhouse
      - minio
      - symbolicator-retrace

  symbolicator-retrace:
    container_name: symbolicator-retrace
    build:
      context: ../measure-backend/symbolicator-retrace
    ports:
      - "8181:8181"
    env_file:
      - ../measure-backend/symbolicator-retrace/.env
    volumes:
      - symbolicator-volume:/data
    develop:
      watch:
        - path: ../measure-backend/symbolicator-retrace
          action: rebuild

  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9111:9000"
      - "9222:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    restart: always
    volumes:
      - minio-data:/data
  mc:
    container_name: mcmb
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set msr-minio http://minio:9000 minio minio123;
      mc mb msr-minio/msr-symbols-sandbox msr-minio/msr-attachments-sandbox;
      exit 0;
      "

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:23
    ports:
      - "9000:9000/tcp"
      - "8123:8123"
    ulimits:
      nofile: 262144
    volumes:
      - clickhouse-volume:/var/lib/clickhouse
      - clickhouse-volume:/var/log/clickhouse-server

volumes:
  clickhouse-volume:
  symbolicator-volume:
  minio-data:
