#!/usr/bin/env bash

# exit on error
set -e

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../shared.sh"

events_new_table=$(
  cat <<'EOF'
create or replace table events_new
(
    `id` UUID comment 'unique event id' CODEC(LZ4),
    `team_id` LowCardinality(UUID) comment 'associated team id' CODEC(LZ4),
    `app_id` LowCardinality(UUID) comment 'associated app id' CODEC(LZ4),
    `session_id` UUID comment 'associated session id' CODEC(LZ4),
    `timestamp` DateTime64(3, 'UTC') comment 'event timestamp' CODEC(DoubleDelta, ZSTD(3)),
    `inserted_at` DateTime64(3, 'UTC') DEFAULT now64() comment 'original event insertion timestamp' CODEC(Delta(8), ZSTD(3)),
    `type` LowCardinality(String) comment 'type of the event' CODEC(ZSTD(3)),

    `user_triggered` Bool comment 'true if user chose to trigger by themselves' CODEC(ZSTD(3)),

    `inet.ipv4` Nullable(IPv4) comment 'ipv4 address' CODEC(ZSTD(3)),
    `inet.ipv6` Nullable(IPv6) comment 'ipv6 address' CODEC(ZSTD(3)),
    `inet.country_code` LowCardinality(String) comment 'country code' CODEC(ZSTD(3)),

    `attribute.installation_id` UUID comment 'unique id for an installation of an app, generated by sdk' CODEC(LZ4),
    `attribute.app_version` LowCardinality(String) comment 'app version identifier' CODEC(ZSTD(3)),
    `attribute.app_build` LowCardinality(String) comment 'app build identifier' CODEC(ZSTD(3)),
    `attribute.app_unique_id` LowCardinality(String) comment 'app bundle identifier' CODEC(ZSTD(3)),
    `attribute.platform` LowCardinality(String) comment 'platform identifier' CODEC(ZSTD(3)),
    `attribute.measure_sdk_version` String comment 'measure sdk version identifier' CODEC(ZSTD(3)),
    `attribute.thread_name` String comment 'thread on which the event was captured' CODEC(ZSTD(3)),
    `attribute.user_id` String comment 'id of the app\'s end user' CODEC(ZSTD(3)),
    `attribute.device_name` String comment 'name of the device' CODEC(ZSTD(3)),
    `attribute.device_model` String comment 'model of the device' CODEC(ZSTD(3)),
    `attribute.device_manufacturer` String comment 'manufacturer of the device' CODEC(ZSTD(3)),
    `attribute.device_type` LowCardinality(String) comment 'type of the device, like phone or tablet' CODEC(ZSTD(3)),
    `attribute.device_is_foldable` Bool comment 'true for foldable devices' CODEC(ZSTD(3)),
    `attribute.device_is_physical` Bool comment 'true for physical devices' CODEC(ZSTD(3)),
    `attribute.device_density_dpi` UInt16 comment 'dpi density' CODEC(Delta(2), ZSTD(3)),
    `attribute.device_width_px` UInt16 comment 'screen width' CODEC(Delta(2), ZSTD(3)),
    `attribute.device_height_px` UInt16 comment 'screen height' CODEC(Delta(2), ZSTD(3)),
    `attribute.device_density` Float32 comment 'device density' CODEC(Delta(4), ZSTD(3)),
    `attribute.device_locale` LowCardinality(String) comment 'rfc 5646 locale string' CODEC(ZSTD(3)),
    `attribute.device_low_power_mode` Bool comment 'true if low power mode is enabled',
    `attribute.device_thermal_throttling_enabled` Bool comment 'true if thermal throttling is enabled',
    `attribute.device_cpu_arch` LowCardinality(String) comment 'cpu architecture like arm64 and so on',
    `attribute.os_name` LowCardinality(String) comment 'name of the operating system' CODEC(ZSTD(3)),
    `attribute.os_version` String comment 'version of the operating system' CODEC(ZSTD(3)),
    `attribute.os_page_size` UInt8 comment 'memory_page_size' CODEC(Delta(1), ZSTD(3)),
    `attribute.network_type` LowCardinality(String) comment 'either - wifi, cellular, vpn, unknown, no_network' CODEC(ZSTD(3)),
    `attribute.network_generation` LowCardinality(String) comment 'either - 2g, 3g, 4g, 5g, unknown' CODEC(ZSTD(3)),
    `attribute.network_provider` String comment 'name of the network service provider' CODEC(ZSTD(3)),

    `user_defined_attribute` Map(LowCardinality(String), Tuple(
        Enum8('string' = 1, 'int64' = 2, 'float64' = 3, 'bool' = 4),
        String)) comment 'user defined attributes' CODEC(ZSTD(3)),

    `anr.handled` Bool comment 'anr was handled by the application code' CODEC(ZSTD(3)),
    `anr.fingerprint` String comment 'fingerprint for anr similarity classification' CODEC(ZSTD(3)),
    `anr.exceptions` String comment 'anr exception data' CODEC(ZSTD(3)),
    `anr.threads` String comment 'anr thread data' CODEC(ZSTD(3)),
    `anr.foreground` Bool comment 'true if the anr was perceived by end user' CODEC(ZSTD(3)),

    `exception.handled` Bool comment 'exception was handled by application code' CODEC(ZSTD(3)),
    `exception.fingerprint` String comment 'fingerprint for exception similarity classification' CODEC(ZSTD(3)),
    `exception.exceptions` String comment 'exception data' CODEC(ZSTD(3)),
    `exception.threads` String comment 'exception thread data' CODEC(ZSTD(3)),
    `exception.foreground` Bool comment 'true if the exception was perceived by end user' CODEC(ZSTD(3)),
    `exception.framework` String comment 'the framework in which the exception was thrown',
    `exception.binary_images` String comment 'list of apple crash binary images',
    `exception.error` String comment 'general error data',
    `app_exit.reason` LowCardinality(String) comment 'reason for app exit' CODEC(ZSTD(3)),
    `app_exit.importance` LowCardinality(String) comment 'importance of process that it used to have before death' CODEC(ZSTD(3)),

    `app_exit.trace` String comment 'modified trace given by ApplicationExitInfo to help debug anrs.' CODEC(ZSTD(3)),
    `app_exit.process_name` String comment 'name of the process that died' CODEC(ZSTD(3)),
    `app_exit.pid` String comment 'id of the process that died' CODEC(ZSTD(3)),

    `string.severity_text` LowCardinality(String) comment 'log level - info, warning, error, fatal, debug' CODEC(ZSTD(3)),
    `string.string` String comment 'log message text' CODEC(ZSTD(3)),

    `gesture_long_click.target` String comment 'class or instance name of the originating view' CODEC(ZSTD(3)),
    `gesture_long_click.target_id` String comment 'unique identifier of the target' CODEC(ZSTD(3)),
    `gesture_long_click.touch_down_time` UInt64 comment 'time for touch down gesture' CODEC(T64, ZSTD(3)),
    `gesture_long_click.touch_up_time` UInt64 comment 'time for touch up gesture' CODEC(T64, ZSTD(3)),
    `gesture_long_click.width` UInt16 comment 'width of the target view in pixels' CODEC(T64, ZSTD(3)),
    `gesture_long_click.height` UInt16 comment 'height of the target view in pixels' CODEC(T64, ZSTD(3)),
    `gesture_long_click.x` Float32 comment 'x coordinate of where the gesture happened' CODEC(Delta(4), ZSTD(3)),
    `gesture_long_click.y` Float32 comment 'y coordinate of where the gesture happened' CODEC(Delta(4), ZSTD(3)),

    `gesture_click.target` String comment 'class or instance name of the originating view' CODEC(ZSTD(3)),
    `gesture_click.target_id` String comment 'unique identifier of the target' CODEC(ZSTD(3)),
    `gesture_click.touch_down_time` UInt64 comment 'time for touch down gesture' CODEC(T64, ZSTD(3)),
    `gesture_click.touch_up_time` UInt64 comment 'time for the touch up gesture' CODEC(T64, ZSTD(3)),
    `gesture_click.width` UInt16 comment 'width of the target view in pixels' CODEC(Delta(2), ZSTD(3)),
    `gesture_click.height` UInt16 comment 'height of the target view in pixels' CODEC(Delta(2), ZSTD(3)),
    `gesture_click.x` Float32 comment 'x coordinate of where the gesture happened' CODEC(Delta(4), ZSTD(3)),
    `gesture_click.y` Float32 comment 'y coordinate of where the gesture happened' CODEC(Delta(4), ZSTD(3)),

    `gesture_scroll.target` String comment 'class or instance name of the originating view' CODEC(ZSTD(3)),
    `gesture_scroll.target_id` String comment 'unique identifier of the target' CODEC(ZSTD(3)),
    `gesture_scroll.touch_down_time` UInt64 comment 'time for touch down gesture' CODEC(T64, ZSTD(3)),
    `gesture_scroll.touch_up_time` UInt64 comment 'time for touch up gesture' CODEC(T64, ZSTD(3)),
    `gesture_scroll.x` Float32 comment 'x coordinate of where the gesture started' CODEC(Delta(4), ZSTD(3)),
    `gesture_scroll.y` Float32 comment 'y coordinate of where the gesture started' CODEC(Delta(4), ZSTD(3)),
    `gesture_scroll.end_x` Float32 comment 'x coordinate of where the gesture ended' CODEC(Delta(4), ZSTD(3)),
    `gesture_scroll.end_y` Float32 comment 'y coordinate of where the gesture ended' CODEC(Delta(4), ZSTD(3)),
    `gesture_scroll.direction` LowCardinality(String) comment 'direction of the scroll' CODEC(ZSTD(3)),

    `lifecycle_activity.type` LowCardinality(String) comment 'type of the lifecycle activity, either - created, resumed, paused, destroyed' CODEC(ZSTD(3)),
    `lifecycle_activity.class_name` String comment 'fully qualified class name of the activity' CODEC(ZSTD(3)),
    `lifecycle_activity.intent` String comment 'intent data serialized as string' CODEC(ZSTD(3)),
    `lifecycle_activity.saved_instance_state` Bool comment 'represents that activity was recreated with a saved state. only available for type created.' CODEC(ZSTD(3)),

    `lifecycle_fragment.type` LowCardinality(String) comment 'type of the lifecycle fragment, either - attached, resumed, paused, detached' CODEC(ZSTD(3)),
    `lifecycle_fragment.class_name` String comment 'fully qualified class name of the fragment' CODEC(ZSTD(3)),
    `lifecycle_fragment.parent_activity` String comment 'fully qualified class name of the parent activity that the fragment is attached to' CODEC(ZSTD(3)),
    `lifecycle_fragment.parent_fragment` String comment 'fully qualified class name of the parent fragment that the fragment is attached to' CODEC(ZSTD(3)),
    `lifecycle_fragment.tag` String comment 'optional fragment tag' CODEC(ZSTD(3)),

    `lifecycle_view_controller.type` LowCardinality(String) comment 'type of the iOS ViewController lifecycle event',
    `lifecycle_view_controller.class_name` LowCardinality(String) comment 'class name of the iOS ViewController lifecycle event',

    `lifecycle_swift_ui.type` LowCardinality(String) comment 'type of the iOS SwiftUI view lifecycle event',
    `lifecycle_swift_ui.class_name` LowCardinality(String) comment 'class name of the iOS SwiftUI view lifecycle event',

    `lifecycle_app.type` LowCardinality(String) comment 'type of the lifecycle app, either - background, foreground' CODEC(ZSTD(3)),

    `cold_launch.process_start_uptime` UInt64 comment 'start uptime in msec' CODEC(T64, ZSTD(3)),
    `cold_launch.process_start_requested_uptime` UInt64 comment 'start uptime in msec' CODEC(T64, ZSTD(3)),
    `cold_launch.content_provider_attach_uptime` UInt64 comment 'start uptime in msec' CODEC(T64, ZSTD(3)),
    `cold_launch.on_next_draw_uptime` UInt64 comment 'time at which app became visible' CODEC(T64, ZSTD(3)),
    `cold_launch.launched_activity` String comment 'activity which drew the first frame during cold launch' CODEC(ZSTD(3)),
    `cold_launch.has_saved_state` Bool comment 'whether the launched_activity was created with a saved state bundle' CODEC(ZSTD(3)),
    `cold_launch.intent_data` String comment 'intent data used to launch the launched_activity' CODEC(ZSTD(3)),
    `cold_launch.duration` UInt32 comment 'computed cold launch duration' CODEC(T64, ZSTD(3)),

    `warm_launch.app_visible_uptime` UInt64 comment 'time since the app became visible to user, in msec',
    `warm_launch.process_start_uptime` UInt64 comment 'start uptime in msec' CODEC(T64, ZSTD(3)),
    `warm_launch.process_start_requested_uptime` UInt64 comment 'start uptime in msec' CODEC(T64, ZSTD(3)),
    `warm_launch.content_provider_attach_uptime` UInt64 comment 'start uptime in msec' CODEC(T64, ZSTD(3)),
    `warm_launch.on_next_draw_uptime` UInt64 comment 'time at which app became visible to user, in msec' CODEC(ZSTD(3)),
    `warm_launch.launched_activity` String comment 'activity which drew the first frame during warm launch' CODEC(ZSTD(3)),
    `warm_launch.has_saved_state` Bool comment 'whether the launched_activity was created with a saved state bundle' CODEC(ZSTD(3)),
    `warm_launch.intent_data` String comment 'intent data used to launch the launched_activity' CODEC(ZSTD(3)),
    `warm_launch.duration` UInt32 comment 'computed warm launch duration' CODEC(T64, ZSTD(3)),
    `warm_launch.is_lukewarm` Bool comment 'whether it is a lukewarm launch' CODEC(ZSTD(3)),

    `hot_launch.app_visible_uptime` UInt64 comment 'time elapsed since the app became visible to user, in msec' CODEC(T64, ZSTD(3)),
    `hot_launch.on_next_draw_uptime` UInt64 comment 'time at which app became visible to user, in msec' CODEC(T64, ZSTD(3)),
    `hot_launch.launched_activity` String comment 'activity which drew the first frame during hot launch' CODEC(ZSTD(3)),
    `hot_launch.has_saved_state` Bool comment 'whether the launched_activity was created with a saved state bundle' CODEC(ZSTD(3)),
    `hot_launch.intent_data` String comment 'intent data used to launch the launched_activity' CODEC(ZSTD(3)),
    `hot_launch.duration` UInt32 comment 'computed hot launch duration' CODEC(T64, ZSTD(3)),

    `network_change.network_type` LowCardinality(String) comment 'type of the network, wifi, cellular etc' CODEC(ZSTD(3)),
    `network_change.previous_network_type` LowCardinality(String) comment 'type of the previous network' CODEC(ZSTD(3)),
    `network_change.network_generation` LowCardinality(String) comment '2g, 3g, 4g etc' CODEC(ZSTD(3)),
    `network_change.previous_network_generation` LowCardinality(String) comment 'previous network generation' CODEC(ZSTD(3)),
    `network_change.network_provider` String comment 'name of the network service provider' CODEC(ZSTD(3)),

    `http.url` String comment 'url of the http request' CODEC(ZSTD(3)),
    `http.method` LowCardinality(String) comment 'method like get, post' CODEC(ZSTD(3)),
    `http.status_code` UInt16 comment 'http status code' CODEC(T64, ZSTD(3)),
    `http.start_time` UInt64 comment 'uptime at when the http call started, in msec' CODEC(T64, ZSTD(3)),
    `http.end_time` UInt64 comment 'uptime at when the http call ended, in msec' CODEC(T64, ZSTD(3)),
    `http_request_headers` Map(String, String) comment 'http request headers' CODEC(ZSTD(3)),
    `http_response_headers` Map(String, String) comment 'http response headers' CODEC(ZSTD(3)),
    `http.request_body` String comment 'request body' CODEC(ZSTD(3)),
    `http.response_body` String comment 'response body' CODEC(ZSTD(3)),
    `http.failure_reason` String comment 'reason for failure' CODEC(ZSTD(3)),
    `http.failure_description` String comment 'description of the failure' CODEC(ZSTD(3)),
    `http.client` LowCardinality(String) comment 'name of the http client' CODEC(ZSTD(3)),

    `memory_usage.java_max_heap` UInt64 comment 'maximum size of the java heap allocated, in kb' CODEC(T64, ZSTD(3)),
    `memory_usage.java_total_heap` UInt64 comment 'total size of the java heap available for allocation, in KB' CODEC(T64, ZSTD(3)),
    `memory_usage.java_free_heap` UInt64 comment 'free memory available in the java heap, in kb' CODEC(T64, ZSTD(3)),
    `memory_usage.total_pss` UInt64 comment 'total proportional set size - amount of memory used by the process, including shared memory and code. in kb.' CODEC(T64, ZSTD(3)),
    `memory_usage.rss` UInt64 comment 'resident set size - amount of physical memory currently used, in kb' CODEC(T64, ZSTD(3)),
    `memory_usage.native_total_heap` UInt64 comment 'total size of the native heap (memory out of java\'s control) available for allocation, in kb' CODEC(T64, ZSTD(3)),
    `memory_usage.native_free_heap` UInt64 comment 'amount of free memory available in the native heap, in kb' CODEC(T64, ZSTD(3)),
    `memory_usage.interval` UInt64 comment 'interval between two consecutive readings, in msec' CODEC(T64, ZSTD(3)),
    `memory_usage_absolute.max_memory` UInt64 comment 'maximum memory available to the application, in KiB',
    `memory_usage_absolute.used_memory` UInt64 comment 'used memory by the application, in KiB',
    `memory_usage_absolute.interval` UInt64 comment 'interval between two consecutive readings',

    `low_memory.java_max_heap` UInt64 comment 'maximum size of the java heap allocated, in kb' CODEC(T64, ZSTD(3)),
    `low_memory.java_total_heap` UInt64 comment 'total size of the java heap available for allocation, in kb' CODEC(T64, ZSTD(3)),
    `low_memory.java_free_heap` UInt64 comment 'free memory available in the java heap, in kb' CODEC(T64, ZSTD(3)),
    `low_memory.total_pss` UInt64 comment 'total proportional set size - amount of memory used by the process, including shared memory and code. in kb.' CODEC(T64, ZSTD(3)),
    `low_memory.rss` UInt64 comment 'resident set size - amount of physical memory currently used, in kb' CODEC(T64, ZSTD(3)),
    `low_memory.native_total_heap` UInt64 comment 'total size of the native heap (memory out of java' CODEC(T64, ZSTD(3)),
    `low_memory.native_free_heap` UInt64 comment 'amount of free memory available in the native heap, in kb' CODEC(T64, ZSTD(3)),

    `trim_memory.level` LowCardinality(String) comment 'one of the trim memory constants as received by component callback' CODEC(ZSTD(3)),

    `cpu_usage.num_cores` UInt8 comment 'number of cores on the device' CODEC(T64, ZSTD(3)),
    `cpu_usage.clock_speed` UInt64 comment 'clock speed of the processor, in hz' CODEC(T64, ZSTD(3)),
    `cpu_usage.start_time` UInt64 comment 'process start time, in jiffies' CODEC(T64, ZSTD(3)),
    `cpu_usage.uptime` UInt64 comment 'time since the device booted, in msec' CODEC(T64, ZSTD(3)),
    `cpu_usage.utime` UInt64 comment 'execution time in user mode, in jiffies' CODEC(T64, ZSTD(3)),
    `cpu_usage.cutime` UInt64 comment 'execution time in user mode with child processes, in jiffies' CODEC(T64, ZSTD(3)),
    `cpu_usage.stime` UInt64 comment 'execution time in kernel mode, in jiffies' CODEC(T64, ZSTD(3)),
    `cpu_usage.cstime` UInt64 comment 'execution time in user mode with child processes, in jiffies' CODEC(T64, ZSTD(3)),
    `cpu_usage.interval` UInt64 comment 'interval between two consecutive readings, in msec' CODEC(T64, ZSTD(3)),
    `cpu_usage.percentage_usage` Float64 comment 'percentage of cpu usage in the interval' CODEC(DoubleDelta, ZSTD(3)),

    `navigation.to` String comment 'destination page or screen where the navigation led to' CODEC(ZSTD(3)),
    `navigation.from` String comment 'source page or screen from where the navigation was triggered' CODEC(ZSTD(3)),
    `navigation.source` String comment 'how the event was collected example a library or framework name' CODEC(ZSTD(3)),

    `screen_view.name` String comment 'name of the screen viewed' CODEC(ZSTD(3)),

    `bug_report.description` String comment 'description of the bug report',
    `custom.name` LowCardinality(String) comment 'name of the custom event',
    `attachments` String comment 'attachment metadata' CODEC(ZSTD(3)),

    index type_idx type type set(100) granularity 2,
    index exception_handled_idx `exception.handled` type minmax granularity 2,
    index attribute_os_name_idx `attribute.os_name` type minmax granularity 2,
    index attribute_os_version_idx `attribute.os_version` type minmax granularity 2,
    index inet_country_code_idx `inet.country_code` type minmax granularity 2,
    index attribute_device_name_idx `attribute.device_name` type minmax granularity 2,
    index attribute_device_manufacturer_idx `attribute.device_manufacturer` type minmax granularity 2,
    index attribute_device_locale_idx `attribute.device_locale` type minmax granularity 2,
    index attribute_network_provider_idx `attribute.network_provider` type minmax granularity 2,
    index attribute_network_type_idx `attribute.network_type` type minmax granularity 2,
    index exception_fingerprint_bloom_idx `exception.fingerprint` type bloom_filter granularity 4,
    index anr_fingerprint_bloom_idx `anr.fingerprint` type bloom_filter granularity 4,
    index user_defined_attribute_key_bloom_idx mapKeys(user_defined_attribute) type bloom_filter(0.01) granularity 16,
    index user_defined_attribute_key_minmax_idx mapKeys(user_defined_attribute) type minmax granularity 16,
    index custom_name_bloom_idx `custom.name` type bloom_filter granularity 2,
    index timestamp_minmax_idx `timestamp` type minmax granularity 1
)
engine = ReplacingMergeTree
partition by toYYYYMM(timestamp)
order by (team_id, app_id, attribute.app_version, attribute.app_build, timestamp, session_id, id)
settings index_granularity = 8192
comment 'events root table'
EOF
)

app_filters_new_table=$(
  cat <<'EOF'
create or replace table app_filters_new
(
    `team_id` LowCardinality(UUID) CODEC(LZ4),
    `app_id` LowCardinality(UUID) comment 'associated app id' CODEC(LZ4),
    `end_of_month` DateTime comment 'last day of the month' CODEC(DoubleDelta, ZSTD(3)),
    `app_version` Tuple(
        LowCardinality(String),
        LowCardinality(String)) comment 'composite app version' CODEC(ZSTD(3)),
    `os_version` Tuple(
        LowCardinality(String),
        LowCardinality(String)) comment 'composite os version' CODEC(ZSTD(3)),
    `country_code` LowCardinality(String) comment 'country code' CODEC(ZSTD(3)),
    `network_provider` LowCardinality(String) comment 'network provider' CODEC(ZSTD(3)),
    `network_type` LowCardinality(String) comment 'network type' CODEC(ZSTD(3)),
    `network_generation` LowCardinality(String) comment 'network generation' CODEC(ZSTD(3)),
    `device_locale` LowCardinality(String) comment 'device locale' CODEC(ZSTD(3)),
    `device_manufacturer` LowCardinality(String) comment 'device manufacturer' CODEC(ZSTD(3)),
    `device_name` LowCardinality(String) comment 'device name' CODEC(ZSTD(3)),
    `exception` Bool comment 'true if source is exception event' CODEC(ZSTD(3)),
    `anr` Bool comment 'true if source is anr event' CODEC(ZSTD(3)),
)
engine = ReplacingMergeTree
partition by toYYYYMM(end_of_month)
primary key (team_id, app_id, end_of_month)
order by (
  team_id,
  app_id,
  end_of_month,
  exception,
  anr,
  network_type,
  network_generation,
  os_version,
  app_version,
  country_code,
  device_manufacturer,
  device_locale,
  network_provider,
  device_name
)
settings index_granularity = 8192
comment 'derived app filters'
EOF
)

app_metrics_new_table=$(
  cat <<'EOF'
create or replace table app_metrics_new
(
    `team_id` LowCardinality(UUID) comment 'associated team id' CODEC(LZ4),
    `app_id` LowCardinality(UUID) comment 'associated app id' CODEC(LZ4),
    `timestamp` DateTime64(3, 'UTC') comment 'interval metrics will be aggregated to' CODEC(DoubleDelta, ZSTD(3)),
    `app_version` Tuple(
        LowCardinality(String),
        LowCardinality(String)) comment 'composite app version' CODEC(ZSTD(3)),
    `unique_sessions` AggregateFunction(uniq, UUID) comment 'unique sessions in interval window' CODEC(ZSTD(3)),
    `crash_sessions` AggregateFunction(uniq, UUID) comment 'crash sessions in interval window' CODEC(ZSTD(3)),
    `perceived_crash_sessions` AggregateFunction(uniq, UUID) comment 'perceived crash sessions in interval window' CODEC(ZSTD(3)),
    `anr_sessions` AggregateFunction(uniq, UUID) comment 'anr sessions in interval window' CODEC(ZSTD(3)),
    `perceived_anr_sessions` AggregateFunction(uniq, UUID) comment 'perceived anr sessions in interval window' CODEC(ZSTD(3)),
    `cold_launch_p95` AggregateFunction(quantile(0.95), UInt32) comment 'p95 quantile of cold launch duration' CODEC(ZSTD(3)),
    `warm_launch_p95` AggregateFunction(quantile(0.95), UInt32) comment 'p95 quantile of warm launch duration' CODEC(ZSTD(3)),
    `hot_launch_p95` AggregateFunction(quantile(0.95), UInt32) comment 'p95 quantile of hot launch duration' CODEC(ZSTD(3)),

    index app_version_name_idx app_version.1 type set(100) granularity 2,
    index app_version_code_idx app_version.2 type set(100) granularity 2
)
engine = AggregatingMergeTree
partition by toYYYYMM(timestamp)
order by (team_id, app_id, timestamp)
settings index_granularity = 8192
comment 'aggregated app metrics by a fixed time window'
EOF
)

journey_new_table=$(
  cat <<'EOF'
create or replace table journey_new
(
  `id` UUID comment 'unique event id' CODEC(LZ4),
  `team_id` LowCardinality(UUID) comment 'associated team id' CODEC(LZ4),
  `app_id` LowCardinality(UUID) comment 'associated app id' CODEC(LZ4),
  `session_id` UUID comment 'associated session id' CODEC(LZ4),
  `timestamp` DateTime64(3, 'UTC') comment 'event timestamp' CODEC(DoubleDelta, ZSTD(3)),
  `inserted_at` DateTime64(3, 'UTC') comment 'original event insertion timestamp' CODEC(Delta(8), ZSTD(3)),
  `type` LowCardinality(String) comment 'type of the event' CODEC(ZSTD(3)),
  `app_version` Tuple(LowCardinality(String), LowCardinality(String)) comment 'app version identifier' CODEC(ZSTD(3)),
  `exception.handled` Bool comment 'exception was handled by application code' CODEC(ZSTD(3)),
  `exception.fingerprint` String comment 'fingerprint for exception similarity classification' CODEC(ZSTD(3)),
  `anr.fingerprint` String comment 'fingerprint for ANR similarity classification' CODEC(ZSTD(3)),
  `lifecycle_activity.type` LowCardinality(String) comment 'type of the lifecycle activity, either - created, resumed, paused, destroyed' CODEC(ZSTD(3)),
  `lifecycle_activity.class_name` String comment 'fully qualified class name of the activity' CODEC(ZSTD(3)),
  `lifecycle_fragment.type` LowCardinality(String) comment 'type of the lifecycle fragment, either - attached, resumed, paused, detached' CODEC(ZSTD(3)),
  `lifecycle_fragment.class_name` String comment 'fully qualified class name of the fragment' CODEC(ZSTD(3)),
  `lifecycle_fragment.parent_activity` String comment 'fully qualified class name of the parent activity that the fragment is attached to' CODEC(ZSTD(3)),
  `lifecycle_fragment.parent_fragment` String comment 'fully qualified class name of the parent fragment that the fragment is attached to' CODEC(ZSTD(3)),
  `lifecycle_view_controller.type` LowCardinality(String) comment 'type of the iOS ViewController lifecycle event',
  `lifecycle_view_controller.class_name` LowCardinality(String) comment 'class name of the iOS ViewController lifecycle event',
  `lifecycle_swift_ui.type` LowCardinality(String) comment 'type of the iOS SwiftUI view lifecycle event',
  `lifecycle_swift_ui.class_name` LowCardinality(String) comment 'class name of the iOS SwiftUI view lifecycle event',
  `screen_view.name` String comment 'name of the screen viewed' CODEC(ZSTD(3))
)
engine = ReplacingMergeTree
partition by toYYYYMM(timestamp)
order by (team_id, app_id, app_version.1, app_version.2, timestamp, id)
settings index_granularity = 8192
comment 'journey events';
EOF
)

bug_reports_new_table=$(
  cat <<'EOF'
create or replace table bug_reports_new
(
  `team_id` LowCardinality(UUID) CODEC(LZ4),
  `event_id` UUID comment 'bug report event id' CODEC(LZ4),
  `app_id` LowCardinality(UUID) comment 'unique id of the app' CODEC(LZ4),
  `session_id` UUID comment 'session id' CODEC(LZ4),
  `timestamp` DateTime64(3, 'UTC') comment 'timestamp of the bug report' CODEC(DoubleDelta, ZSTD(3)),
  `updated_at` DateTime64(3, 'UTC') comment 'timestamp when record was last updated' CODEC(DoubleDelta, ZSTD(3)),
  `status` UInt8 comment 'status of the bug report 0 (Closed) or 1 (Open)' CODEC(ZSTD(3)),
  `description` String comment 'description of the bug report' CODEC(ZSTD(3)),
  `app_version` Tuple(
      LowCardinality(String),
      LowCardinality(String)) comment 'composite app version' CODEC(ZSTD(3)),
  `os_version` Tuple(
      LowCardinality(String),
      LowCardinality(String)) comment 'composite os version' CODEC(ZSTD(3)),
  `country_code` LowCardinality(String) comment 'country code' CODEC(ZSTD(3)),
  `network_provider` LowCardinality(String) comment 'name of the network service provider' CODEC(ZSTD(3)),
  `network_type` LowCardinality(String) comment 'wifi, cellular, vpn and so on' CODEC(ZSTD(3)),
  `network_generation` LowCardinality(String) comment '2g, 3g, 4g and so on' CODEC(ZSTD(3)),
  `device_locale` LowCardinality(String) comment 'rfc 5646 locale string' CODEC(ZSTD(3)),
  `device_manufacturer` LowCardinality(String) comment 'manufacturer of the device' CODEC(ZSTD(3)),
  `device_name` LowCardinality(String) comment 'name of the device' CODEC(ZSTD(3)),
  `device_model` LowCardinality(String) comment 'model of the device' CODEC(ZSTD(3)),
  `user_id` LowCardinality(String) comment 'attributed user id' CODEC(ZSTD(3)),
  `device_low_power_mode` Bool comment 'true if low power mode is enabled',
  `device_thermal_throttling_enabled` Bool comment 'true if thermal throttling is enabled',
  `user_defined_attribute` Map(LowCardinality(String), Tuple(
      Enum8('string' = 1, 'int64' = 2, 'float64' = 3, 'bool' = 4),
      String)) comment 'user defined attributes' CODEC(ZSTD(3)),
  `attachments` String comment 'attachment metadata',

  index event_id_bloom_idx `event_id` type bloom_filter(0.01) granularity 2,
  index session_id_bloom_idx `session_id` type bloom_filter(0.01) granularity 2,

  index status_set_idx `status` type set(100) granularity 2,
  index os_version_set_idx `os_version` type set(100) granularity 2,
  index country_code_set_idx `country_code` type set(100) granularity 2,
  index network_provider_set_idx `network_provider` type set(100) granularity 2,
  index network_type_set_idx `network_type` type set(100) granularity 2,
  index network_generation_set_idx `network_generation` type set(100) granularity 2,
  index device_locale_set_idx `device_locale` type set(100) granularity 2,
  index device_manufacturer_set_idx `device_manufacturer` type set(100) granularity 2,
  index device_name_set_idx `device_name` type set(100) granularity 2,
  index user_id_bloom_idx `user_id` type bloom_filter(0.01) granularity 2,

  index user_defined_attribute_key_bloom_idx mapKeys(user_defined_attribute) type bloom_filter(0.01) granularity 8
)
engine = ReplacingMergeTree()
partition by toYYYYMM(timestamp)
order by (team_id, app_id, app_version.1, app_version.2, timestamp, event_id)
settings
  index_granularity = 1024,
  enable_block_number_column = 1,
  enable_block_offset_column = 1
comment 'derived bug reports';
EOF
)

user_def_attrs_new_table=$(
  cat <<'EOF'
create or replace table user_def_attrs_new
(
  `team_id` LowCardinality(UUID) comment 'associated team id' CODEC(LZ4),
  `app_id` LowCardinality(UUID) comment 'associated app id' CODEC(LZ4),
  `event_id` UUID comment 'id of the event' CODEC(LZ4),
  `session_id` UUID comment 'id of the session' CODEC(LZ4),
  `app_version` Tuple(
      LowCardinality(String),
      LowCardinality(String)) comment 'composite app version' CODEC(ZSTD(3)),
  `os_version` Tuple(
      LowCardinality(String),
      LowCardinality(String)) comment 'composite os version' CODEC(ZSTD(3)),
  `bug_report` Bool comment 'true if source is bug_report event' CODEC(ZSTD(3)),
  `key` LowCardinality(String) comment 'key of the user defined attribute' CODEC(ZSTD(3)),
  `type` Enum8('string' = 1, 'int64' = 2, 'float64' = 3, 'bool' = 4) comment 'type of the user defined attribute' CODEC(ZSTD(3)),
  `value` String comment 'value of the user defined attribute' CODEC(ZSTD(3)),
  `timestamp` DateTime64(3, 'UTC') comment 'event timestamp' CODEC(DoubleDelta, ZSTD(3)),

  index timestamp_minmax_idx timestamp type minmax granularity 2,
  index os_version_bloom_idx toString(os_version) type bloom_filter(0.05) granularity 4,
  index os_version_set_idx os_version type set(1000) granularity 2,
  index bug_report_bloom_idx bug_report type bloom_filter(0.05) granularity 2,
  index key_bloom_idx key type bloom_filter(0.05) granularity 1,
  index key_set_idx key type set(5000) granularity 2,
  index session_bloom_idx session_id type bloom_filter(0.05) granularity 2
)
engine = ReplacingMergeTree(timestamp)
partition by toYYYYMM(timestamp)
primary key (team_id, app_id, app_version.1, app_version.2)
order by (team_id, app_id, app_version.1, app_version.2, os_version.1, os_version.2, type, key, event_id, value)
settings index_granularity = 8192
comment 'derived user defined attributes';
EOF
)

sessions_index_new_table=$(
  cat <<'EOF'
create or replace table sessions_index_new
(
    `team_id` LowCardinality(UUID) comment 'associated team id' CODEC(LZ4),
    `app_id` LowCardinality(UUID) comment 'associated app id' CODEC(LZ4),
    `app_version` Tuple(
        LowCardinality(String),
        LowCardinality(String)) comment 'associated app version' CODEC(ZSTD(3)),
    `session_id` UUID comment 'associated session id' CODEC(LZ4),
    `first_event_timestamp` DateTime64(3, 'UTC') comment 'first event timestamp of the block of events' CODEC(DoubleDelta, ZSTD(3)),
    `last_event_timestamp` DateTime64(3, 'UTC') comment 'last event timestamp of the block of events' CODEC(DoubleDelta, ZSTD(3)),

    index first_event_timestamp_minmax_idx first_event_timestamp type minmax granularity 1,
    index last_event_timestamp_minmax_idx last_event_timestamp type minmax granularity 1
)
engine = MergeTree
partition by toYYYYMM(first_event_timestamp)
order by (team_id, app_id, session_id)
settings index_granularity = 1024
comment 'index of keys for sessions to make fast session detail queries'
EOF
)

sessions_new_table=$(
  cat <<'EOF'
create or replace table sessions_new
(
  `session_id` UUID comment 'session id' CODEC(LZ4),
  `team_id` LowCardinality(UUID) CODEC(LZ4),
  `app_id` LowCardinality(UUID) comment 'unique id of the app' CODEC(LZ4),
  `first_event_timestamp` SimpleAggregateFunction(min, DateTime64(3, 'UTC')) comment 'timestamp of the first event' CODEC(DoubleDelta, ZSTD(3)),
  `last_event_timestamp` SimpleAggregateFunction(max, DateTime64(3, 'UTC')) comment 'timestamp of the last event' CODEC(DoubleDelta, ZSTD(3)),
  `app_version` Tuple(
    LowCardinality(String),
    LowCardinality(String)) comment 'composite app version' CODEC(ZSTD(3)),
  `os_version` Tuple(
    LowCardinality(String),
    LowCardinality(String)) comment 'composite os version' CODEC(ZSTD(3)),
  `country_codes` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique country codes',
  `network_providers` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique network service providers',
  `network_types` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique network types',
  `network_generations` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique network generations',
  `device_locales` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique device locales',
  `device_manufacturer` LowCardinality(String) comment 'manufacturer of the device' CODEC(ZSTD(3)),
  `device_name` LowCardinality(String) comment 'name of the device' CODEC(ZSTD(3)),
  `device_model` LowCardinality(String) comment 'model of the device' CODEC(ZSTD(3)),
  `user_ids` AggregateFunction(groupUniqArray, String) comment 'list of all user ids',
  `unique_types` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of unique event type' CODEC(ZSTD(3)),
  `unique_custom_type_names` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of unique custom event type names' CODEC(ZSTD(3)),
  `unique_strings` AggregateFunction(groupUniqArray, String) comment 'list of unique log string values' CODEC(ZSTD(3)),
  `unique_view_classnames` AggregateFunction(groupUniqArray, String) comment 'list of unique view class names' CODEC(ZSTD(3)),
  `unique_subview_classnames` AggregateFunction(groupUniqArray, String) comment 'list of unique subview class names' CODEC(ZSTD(3)),
  `unique_unhandled_exceptions` AggregateFunction(groupUniqArray, Tuple(
    type String,
    message String,
    file_name String,
    class_name String,
    method_name String)) comment 'list of unique tuples of unhandled exception details' CODEC(ZSTD(3)),
  `unique_handled_exceptions` AggregateFunction(groupUniqArray, Tuple(
    type String,
    message String,
    file_name String,
    class_name String,
    method_name String)) comment 'list of unique tuples of handled exception details' CODEC(ZSTD(3)),
  `unique_anrs` AggregateFunction(groupUniqArray, Tuple(
    type String,
    message String,
    file_name String,
    class_name String,
    method_name String)) comment 'list of unique tuples of anr details' CODEC(ZSTD(3)),
  `unique_click_targets` AggregateFunction(groupUniqArray, Tuple(
    String,
    String)) comment 'list of unique tuples of click targets and ids' CODEC(ZSTD(3)),
  `unique_longclick_targets` AggregateFunction(groupUniqArray, Tuple(
    String,
    String)) comment 'list of unique tuples of long click targets and ids' CODEC(ZSTD(3)),
  `unique_scroll_targets` AggregateFunction(groupUniqArray, Tuple(
    String,
    String)) comment 'list of unique tuples of scroll targets and ids' CODEC(ZSTD(3)),
  `event_count` AggregateFunction(sum, UInt64) comment 'count of events in this session' CODEC(ZSTD(3)),
  `crash_count` AggregateFunction(sum, UInt64) comment 'count of crash events in this session' CODEC(ZSTD(3)),
  `anr_count` AggregateFunction(sum, UInt64) comment 'count of ANR events in this session' CODEC(ZSTD(3)),
  `bug_report_count` AggregateFunction(sum, UInt64) comment 'count of bug report events in this session' CODEC(ZSTD(3)),
  `background_count` AggregateFunction(sum, UInt64) comment 'count of background events in this session' CODEC(ZSTD(3)),
  `foreground_count` AggregateFunction(sum, UInt64) comment 'count of foreground events in this session' CODEC(ZSTD(3)),
  `event_type_counts` AggregateFunction(sumMap, Tuple(Array(String), Array(UInt64))) comment 'count of event types in this session' CODEC(ZSTD(3)),

  index first_event_timestamp_minmax_idx first_event_timestamp type minmax granularity 1,
  index last_event_timestamp_minmax_idx last_event_timestamp type minmax granularity 1
)
engine = AggregatingMergeTree
partition by toYYYYMM(first_event_timestamp)
order by (team_id, app_id, app_version.1, app_version.2, session_id)
settings index_granularity = 8192
comment 'aggregated app sessions'
EOF
)

unhandled_exception_groups_new_table=$(
  cat <<'EOF'
create or replace table unhandled_exception_groups_new
(
  `team_id` LowCardinality(UUID) comment 'associated team id' CODEC(LZ4),
  `app_id` LowCardinality(UUID) comment 'linked app id' CODEC(LZ4),
  `id` FixedString(32) comment 'unique fingerprint of the unhandled exception which acts as the id of the group' CODEC(ZSTD(3)),
  `app_version` Tuple(LowCardinality(String), LowCardinality(String)) comment 'composite app version' CODEC(ZSTD(3)),

  `type` String comment 'type of the exception' CODEC(ZSTD(3)),
  `message` String comment 'message of the exception' CODEC(ZSTD(3)),
  `method_name` String comment 'method name where the exception occurred' CODEC(ZSTD(3)),
  `file_name` String comment 'file name where the exception occurred' CODEC(ZSTD(3)),
  `line_number` Int32 comment 'line number where the exception occurred' CODEC(ZSTD(3)),

  `os_versions` AggregateFunction(groupUniqArray, Tuple(LowCardinality(String), LowCardinality(String))) comment 'list of all unique composite os versions' CODEC(ZSTD(3)),
  `country_codes` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique country codes' CODEC(ZSTD(3)),

  `network_providers` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique network service providers' CODEC(ZSTD(3)),
  `network_types` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique network types' CODEC(ZSTD(3)),
  `network_generations` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique network generations' CODEC(ZSTD(3)),

  `device_locales` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique device locales' CODEC(ZSTD(3)),
  `device_manufacturers` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique device manufacturers' CODEC(ZSTD(3)),
  `device_names` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique device names' CODEC(ZSTD(3)),
  `device_models` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique device models' CODEC(ZSTD(3)),

  `count` AggregateFunction(sum, UInt64) comment 'count of unhandled exception instances' CODEC(ZSTD(3)),
  `timestamp` DateTime64(3, 'UTC') comment 'timestamp of the exception event' CODEC(DoubleDelta, ZSTD(3)),

  index timestamp_minmax_idx timestamp type minmax granularity 1
)
engine = AggregatingMergeTree
partition by toYYYYMM(timestamp)
order by (team_id, app_id, app_version.1, app_version.2, id)
settings index_granularity = 8192
comment 'unhandled exception groups'
EOF
)

anr_groups_new_table=$(
  cat <<'EOF'
create or replace table anr_groups_new
(
  `team_id` LowCardinality(UUID) comment 'associated team id' CODEC(LZ4),
  `app_id` LowCardinality(UUID) comment 'linked app id' CODEC(LZ4),
  `id` FixedString(32) comment 'unique fingerprint of the ANR which acts as the id of the group' CODEC(ZSTD(3)),
  `app_version` Tuple(LowCardinality(String), LowCardinality(String)) comment 'composite app version' CODEC(ZSTD(3)),

  `type` String comment 'type of the ANR' CODEC(ZSTD(3)),
  `message` String comment 'message of the ANR' CODEC(ZSTD(3)),
  `method_name` String comment 'method name where the ANR occurred' CODEC(ZSTD(3)),
  `file_name` String comment 'file name where the ANR occurred' CODEC(ZSTD(3)),
  `line_number` Int32 comment 'line number where the ANR occurred' CODEC(ZSTD(3)),

  `os_versions` AggregateFunction(groupUniqArray, Tuple(LowCardinality(String), LowCardinality(String))) comment 'list of all unique composite os versions' CODEC(ZSTD(3)),
  `country_codes` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique country codes' CODEC(ZSTD(3)),

  `network_providers` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique network providers' CODEC(ZSTD(3)),
  `network_types` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique network types' CODEC(ZSTD(3)),
  `network_generations` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique network generations' CODEC(ZSTD(3)),

  `device_locales` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique device locales' CODEC(ZSTD(3)),
  `device_manufacturers` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique device manufacturers' CODEC(ZSTD(3)),
  `device_names` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique device names' CODEC(ZSTD(3)),
  `device_models` AggregateFunction(groupUniqArray, LowCardinality(String)) comment 'list of all unique device models' CODEC(ZSTD(3)),

  `count` AggregateFunction(sum, UInt64) comment 'count of ANR instances' CODEC(ZSTD(3)),
  `timestamp` DateTime64(3, 'UTC') comment 'timestamp of the ANR event' CODEC(DoubleDelta, ZSTD(3)),

  index timestamp_minmax_idx timestamp type minmax granularity 1
)
engine = AggregatingMergeTree
partition by toYYYYMM(timestamp)
order by (team_id, app_id, app_version.1, app_version.2, id)
settings index_granularity = 8192
comment 'ANR groups'
EOF
)

spans_new_table=$(
  cat <<'EOF'
create or replace table spans_new
(
    `team_id` LowCardinality(UUID) comment 'unique id of the team' CODEC(LZ4),
    `app_id` LowCardinality(UUID) comment 'unique id of the app' CODEC(LZ4),
    `inserted_at` DateTime64(3, 'UTC') DEFAULT now64() comment 'original event insertion timestamp' CODEC(Delta(8), ZSTD(3)),
    `span_name` LowCardinality(String) comment 'name of the span' CODEC(ZSTD(3)),
    `span_id` FixedString(16) comment 'id of the span' CODEC(ZSTD(3)),
    `parent_id` FixedString(16) comment 'id of the parent span' CODEC(ZSTD(3)),
    `trace_id` FixedString(32) comment 'id of the trace' CODEC(ZSTD(3)),
    `session_id` UUID comment 'session id' CODEC(LZ4),
    `status` UInt8 comment 'status of the span 0 (Unset), 1 (Ok) or 2 (Error)' CODEC(ZSTD(3)),
    `start_time` DateTime64(3, 'UTC') comment 'start time' CODEC(DoubleDelta, ZSTD(3)),
    `end_time` DateTime64(3, 'UTC') comment 'end time' CODEC(DoubleDelta, ZSTD(3)),
    `checkpoints` Array(Tuple(
        String,
        DateTime64(3, 'UTC'))) comment 'array of checkpoints - {name, timestamp}' CODEC(ZSTD(3)),
    `attribute.app_unique_id` LowCardinality(String) comment 'app bundle identifier' CODEC(ZSTD(3)),
    `attribute.installation_id` UUID comment 'unique id for an installation of an app, generated by sdk' CODEC(LZ4),
    `attribute.user_id` LowCardinality(String) comment 'attributed user id' CODEC(ZSTD(3)),
    `attribute.measure_sdk_version` LowCardinality(String) comment 'measure sdk version identifier' CODEC(ZSTD(3)),
    `attribute.app_version` Tuple(
        LowCardinality(String),
        LowCardinality(String)) comment 'composite app version' CODEC(ZSTD(3)),
    `attribute.os_version` Tuple(
        LowCardinality(String),
        LowCardinality(String)) comment 'composite os version' CODEC(ZSTD(3)),
    `attribute.platform` LowCardinality(String) comment 'platform identifier' CODEC(ZSTD(3)),
    `attribute.thread_name` String comment 'thread on which the span was captured' CODEC(ZSTD(3)),
    `attribute.country_code` LowCardinality(String) comment 'country code' CODEC(ZSTD(3)),
    `attribute.network_provider` LowCardinality(String) comment 'name of the network service provider' CODEC(ZSTD(3)),
    `attribute.network_type` LowCardinality(String) comment 'wifi, cellular, vpn and so on' CODEC(ZSTD(3)),
    `attribute.network_generation` LowCardinality(String) comment '2g, 3g, 4g and so on' CODEC(ZSTD(3)),
    `attribute.device_name` LowCardinality(String) comment 'name of the device' CODEC(ZSTD(3)),
    `attribute.device_model` LowCardinality(String) comment 'model of the device' CODEC(ZSTD(3)),
    `attribute.device_manufacturer` LowCardinality(String) comment 'manufacturer of the device' CODEC(ZSTD(3)),
    `attribute.device_locale` LowCardinality(String) comment 'rfc 5646 locale string' CODEC(ZSTD(3)),
    `attribute.device_low_power_mode` Bool comment 'true if device is in power saving mode' CODEC(ZSTD(3)),
    `attribute.device_thermal_throttling_enabled` Bool comment 'true if device is has thermal throttling enabled' CODEC(ZSTD(3)),
    `user_defined_attribute` Map(LowCardinality(String), Tuple(
        Enum8('string' = 1, 'int64' = 2, 'float64' = 3, 'bool' = 4),
        String)) comment 'user defined attributes' CODEC(ZSTD(3)),

    index span_name_bloom_idx span_name type bloom_filter granularity 2,
    index span_id_bloom_idx span_id type bloom_filter granularity 2,
    index trace_id_bloom_idx trace_id type bloom_filter granularity 2,
    index parent_id_bloom_idx parent_id type bloom_filter granularity 2,
    index start_time_minmax_idx start_time type minmax granularity 2,
    index end_time_minmax_idx end_time type minmax granularity 2,

    index os_version_set_idx `attribute.os_version` type set(100) granularity 2,
    index country_code_set_idx `attribute.country_code` type set(100) granularity 2,
    index network_provider_set_idx `attribute.network_provider` type set(100) granularity 2,
    index network_type_set_idx `attribute.network_type` type set(100) granularity 2,
    index network_generation_set_idx `attribute.network_generation` type set(100) granularity 2,
    index device_locale_set_idx `attribute.device_locale` type set(100) granularity 2,
    index device_manufacturer_set_idx `attribute.device_manufacturer` type set(100) granularity 2,
    index device_name_set_idx `attribute.device_name` type set(100) granularity 2,

    index user_defined_attribute_key_bloom_idx mapKeys(user_defined_attribute) type bloom_filter(0.01) granularity 8
)
engine = ReplacingMergeTree
partition by toYYYYMM(start_time)
primary key (team_id, app_id, attribute.app_version.1, attribute.app_version.2)
order by (team_id, app_id, attribute.app_version.1, attribute.app_version.2, span_name, start_time, trace_id, span_id)
settings index_granularity = 8192
comment 'spans table'
EOF
)

span_filters_new_table=$(
  cat <<'EOF'
create or replace table span_filters_new
(
  `team_id` LowCardinality(UUID) CODEC(LZ4),
  `app_id` LowCardinality(UUID) comment 'associated app id' CODEC(LZ4),
  `end_of_month` DateTime comment 'last day of the month' CODEC(DoubleDelta, ZSTD(3)),
  `app_version` Tuple(
      LowCardinality(String),
      LowCardinality(String)) comment 'composite app version' CODEC(ZSTD(3)),
  `os_version` Tuple(
      LowCardinality(String),
      LowCardinality(String)) comment 'composite os version' CODEC(ZSTD(3)),
  `country_code` LowCardinality(String) comment 'country code' CODEC(ZSTD(3)),
  `network_provider` LowCardinality(String) comment 'network provider' CODEC(ZSTD(3)),
  `network_type` LowCardinality(String) comment 'network type' CODEC(ZSTD(3)),
  `network_generation` LowCardinality(String) comment 'network generation' CODEC(ZSTD(3)),
  `device_locale` LowCardinality(String) comment 'device locale' CODEC(ZSTD(3)),
  `device_manufacturer` LowCardinality(String) comment 'device manufacturer' CODEC(ZSTD(3)),
  `device_name` LowCardinality(String) comment 'device name' CODEC(ZSTD(3))
)
engine = ReplacingMergeTree
primary key (team_id, app_id, end_of_month)
order by (team_id, app_id, end_of_month, app_version, os_version, country_code, network_provider, network_type, network_generation, device_locale, device_manufacturer, device_name)
settings index_granularity = 8192
comment 'derived span filters'
EOF
)

span_metrics_new_table=$(
  cat <<'EOF'
create or replace table span_metrics_new
(
    `team_id` LowCardinality(UUID) comment 'associated team id' CODEC(LZ4),
    `app_id` LowCardinality(UUID) comment 'associated app id' CODEC(LZ4),
    `span_name` LowCardinality(String) comment 'name of the span' CODEC(ZSTD(3)),
    `span_id` FixedString(16) comment 'id of the span' CODEC(ZSTD(3)),
    `status` UInt8 comment 'status of the span 0 (Unset), 1 (Ok) or 2 (Error)' CODEC(ZSTD(3)),
    `timestamp` DateTime64(3, 'UTC') comment 'interval metrics will be aggregated to' CODEC(DoubleDelta, ZSTD(3)),
    `app_version` Tuple(
        LowCardinality(String),
        LowCardinality(String)) comment 'composite app version' CODEC(ZSTD(3)),
    `os_version` Tuple(
        LowCardinality(String),
        LowCardinality(String)) comment 'composite os version' CODEC(ZSTD(3)),
    `country_code` LowCardinality(String) comment 'country code' CODEC(ZSTD(3)),
    `network_provider` LowCardinality(String) comment 'network provider' CODEC(ZSTD(3)),
    `network_type` LowCardinality(String) comment 'network type' CODEC(ZSTD(3)),
    `network_generation` LowCardinality(String) comment 'network generation' CODEC(ZSTD(3)),
    `device_locale` LowCardinality(String) comment 'device locale' CODEC(ZSTD(3)),
    `device_manufacturer` LowCardinality(String) comment 'device manufacturer' CODEC(ZSTD(3)),
    `device_name` LowCardinality(String) comment 'device name' CODEC(ZSTD(3)),
    `device_low_power_mode` Bool comment 'true if device is in power saving mode' CODEC(ZSTD(3)),
    `device_thermal_throttling_enabled` Bool comment 'true if device is has thermal throttling enabled' CODEC(ZSTD(3)),
    `p50` AggregateFunction(quantile(0.5), Int64) comment 'p50 quantile of span duration' CODEC(ZSTD(3)),
    `p90` AggregateFunction(quantile(0.9), Int64) comment 'p90 quantile of span duration' CODEC(ZSTD(3)),
    `p95` AggregateFunction(quantile(0.95), Int64) comment 'p95 quantile of span duration' CODEC(ZSTD(3)),
    `p99` AggregateFunction(quantile(0.5), Int64) comment 'p99 quantile of span duration' CODEC(ZSTD(3)),

    index status_set_idx status type set(100) granularity 2,
    index os_version_set_idx os_version type set(100) granularity 2,
    index country_code_set_idx country_code type set(100) granularity 2,
    index network_provider_set_idx network_provider type set(100) granularity 2,
    index network_type_set_idx network_type type set(100) granularity 2,
    index network_generation_set_idx network_generation type set(100) granularity 2,
    index device_locale_set_idx device_locale type set(100) granularity 2,
    index device_manufacturer_set_idx device_manufacturer type set(100) granularity 2,
    index device_name_set_idx device_name type set(100) granularity 2
)
engine = AggregatingMergeTree
order by (team_id, app_id, app_version.1, app_version.2, span_name, timestamp, span_id)
settings index_granularity = 8192
comment 'aggregated span metrics by a fixed time window'
EOF
)

span_user_def_attrs_new_table=$(
  cat <<'EOF'
create or replace table span_user_def_attrs_new
(
  `team_id` LowCardinality(UUID) comment 'associated team id' CODEC(LZ4),
  `app_id` LowCardinality(UUID) comment 'associated app id' CODEC(LZ4),
  `span_id` FixedString(16) comment 'id of the span' CODEC(LZ4),
  `session_id` UUID comment 'id of the session' CODEC(LZ4),
  `app_version` Tuple(
      LowCardinality(String),
      LowCardinality(String)) comment 'composite app version' CODEC(ZSTD(3)),
  `os_version` Tuple(
      LowCardinality(String),
      LowCardinality(String)) comment 'composite os version' CODEC(ZSTD(3)),
  `key` LowCardinality(String) comment 'key of the user defined attribute' CODEC(ZSTD(3)),
  `type` Enum8('string' = 1, 'int64' = 2, 'float64' = 3, 'bool' = 4) comment 'type of the user defined attribute' CODEC(ZSTD(3)),
  `value` String comment 'value of the user defined attribute' CODEC(ZSTD(3)),
  `timestamp` DateTime64(3, 'UTC') comment 'start time of the span',

  index timestamp_minmax_idx timestamp type minmax granularity 2,
  index os_version_bloom_idx toString(os_version) type bloom_filter(0.05) granularity 4,
  index os_version_set_idx os_version type set(1000) granularity 2,
  index key_bloom_idx key type bloom_filter(0.05) granularity 1,
  index key_set_idx key type set(5000) granularity 2,
  index session_bloom_idx session_id type bloom_filter(0.05) granularity 2
)
engine = ReplacingMergeTree(timestamp)
partition by toYYYYMM(timestamp)
primary key (team_id, app_id, app_version.1, app_version.2)
order by (team_id, app_id, app_version.1, app_version.2, os_version.1, os_version.2, type, key, span_id, value)
settings index_granularity = 8192
comment 'derived span user defined attributes';
EOF
)

app_filters_mv() {
  local mv_name="$1"
  local source="$2"
  local dest="$3"

  cat <<EOF
  create materialized view $mv_name to $dest
  (
    \`team_id\` UUID,
    \`app_id\` UUID,
    \`end_of_month\` Date,
    \`app_version\` Tuple(LowCardinality(String), LowCardinality(String)),
    \`os_version\` Tuple(LowCardinality(String), LowCardinality(String)),
    \`country_code\` LowCardinality(String),
    \`network_provider\` LowCardinality(String),
    \`network_type\` LowCardinality(String),
    \`network_generation\` LowCardinality(String),
    \`device_locale\` LowCardinality(String),
    \`device_manufacturer\` LowCardinality(String),
    \`device_name\` LowCardinality(String),
    \`exception\` Bool,
    \`anr\` Bool
  ) as select
      team_id,
      app_id,
      toLastDayOfMonth(timestamp) as end_of_month,
      (attribute.app_version, attribute.app_build) as app_version,
      (attribute.os_name, attribute.os_version) as os_version,
      inet.country_code as country_code,
      attribute.network_provider as network_provider,
      attribute.network_type as network_type,
      attribute.network_generation as network_generation,
      attribute.device_locale as device_locale,
      attribute.device_manufacturer as device_manufacturer,
      attribute.device_name as device_name,
      max(type = 'exception' and exception.handled = 0) as exception,
      max(type = 'anr') as anr
    from $source
    where
      attribute.os_name != ''
      and attribute.os_version != ''
      and inet.country_code != ''
      and attribute.network_provider != ''
      and attribute.network_type != ''
      and attribute.network_generation != ''
      and attribute.device_locale != ''
      and attribute.device_manufacturer != ''
      and attribute.device_name != ''
    group by
      team_id,
      app_id,
      end_of_month,
      app_version,
      os_version,
      country_code,
      network_provider,
      network_type,
      network_generation,
      device_locale,
      device_manufacturer,
      device_name
EOF
}

app_metrics_mv() {
  local mv_name="$1"
  local source="$2"
  local dest="$3"

  cat <<EOF
  create materialized view $mv_name
  to $dest
  as
  select
      team_id,
      app_id,
      toStartOfFifteenMinutes(timestamp) as timestamp,
      (attribute.app_version, attribute.app_build) as app_version,
      uniqState(session_id) as unique_sessions,
      uniqStateIf(session_id, type = 'exception' and exception.handled = 0) as crash_sessions,
      uniqStateIf(session_id, type = 'exception' and exception.handled = 0 and exception.foreground = 1) as perceived_crash_sessions,
      uniqStateIf(session_id, type = 'anr') as anr_sessions,
      uniqStateIf(session_id, type = 'anr' and anr.foreground = 1) as perceived_anr_sessions,
      quantileStateIf(0.95)(cold_launch.duration, type = 'cold_launch' and cold_launch.duration > 0 and cold_launch.duration <= 30000) as cold_launch_p95,
      quantileStateIf(0.95)(warm_launch.duration, type = 'warm_launch' and warm_launch.duration > 0 and warm_launch.duration <= 10000) as warm_launch_p95,
      quantileStateIf(0.95)(hot_launch.duration, type = 'hot_launch' and hot_launch.duration > 0) as hot_launch_p95
  from $source
  group by
      team_id,
      app_id,
      timestamp,
      app_version;
EOF
}

journey_mv() {
  local mv_name="$1"
  local source="$2"
  local dest="$3"

  cat <<EOF
create materialized view $mv_name
to $dest
as select
  id,
  team_id,
  app_id,
  session_id,
  timestamp,
  inserted_at,
  type,
  (attribute.app_version, attribute.app_build) as app_version,
  exception.handled,
  exception.fingerprint,
  anr.fingerprint,
  lifecycle_activity.type,
  lifecycle_activity.class_name,
  lifecycle_fragment.type,
  lifecycle_fragment.class_name,
  lifecycle_fragment.parent_activity,
  lifecycle_fragment.parent_fragment,
  lifecycle_view_controller.type,
  lifecycle_view_controller.class_name,
  lifecycle_swift_ui.type,
  lifecycle_swift_ui.class_name,
  screen_view.name
from $source
where type = 'lifecycle_activity'
      or type = 'lifecycle_fragment'
      or type = 'lifecycle_view_controller'
      or type = 'lifecycle_swift_ui'
      or type = 'screen_view'
      or type = 'exception'
      or type = 'anr'
;
EOF
}

bug_reports_mv() {
  local mv_name="$1"
  local source="$2"
  local dest="$3"

  cat <<EOF
create materialized view $mv_name to $dest
(
  \`team_id\` UUID,
  \`event_id\` UUID,
  \`app_id\` UUID,
  \`session_id\` UUID,
  \`timestamp\` DateTime64(3, 'UTC'),
  \`updated_at\` DateTime64(3, 'UTC'),
  \`status\` UInt8,
  \`description\` String,
  \`app_version\` Tuple(
      String,
      String),
  \`os_version\` Tuple(
      String,
      String),
  \`country_code\` String,
  \`network_provider\` String,
  \`network_type\` String,
  \`network_generation\` String,
  \`device_locale\` String,
  \`device_manufacturer\` String,
  \`device_name\` String,
  \`device_model\` String,
  \`user_id\` String,
  \`device_low_power_mode\` Bool,
  \`device_thermal_throttling_enabled\` Bool,
  \`user_defined_attribute\` Map(String, Tuple(
      Enum8('string' = 1, 'int64' = 2, 'float64' = 3, 'bool' = 4),
      String)),
  \`attachments\` String
)
as select
  team_id,
  event_id,
  app_id,
  session_id,
  temp_timestamp AS timestamp,
  temp_timestamp AS updated_at,
  status,
  description,
  app_version,
  os_version,
  country_code,
  network_provider,
  network_type,
  network_generation,
  device_locale,
  device_manufacturer,
  device_name,
  device_model,
  user_id,
  device_low_power_mode,
  device_thermal_throttling_enabled,
  user_defined_attribute,
  attachments
from (
  select
    team_id,
    id AS event_id,
    app_id,
    session_id,
    any(timestamp) AS temp_timestamp,
    0 AS status,
    any(bug_report.description) AS description,
    any((attribute.app_version, attribute.app_build)) AS app_version,
    any((attribute.os_name, attribute.os_version)) AS os_version,
    any(inet.country_code) AS country_code,
    any(attribute.network_provider) AS network_provider,
    any(attribute.network_type) AS network_type,
    any(attribute.network_generation) AS network_generation,
    any(attribute.device_locale) AS device_locale,
    any(attribute.device_manufacturer) AS device_manufacturer,
    any(attribute.device_name) AS device_name,
    any(attribute.device_model) AS device_model,
    any(attribute.user_id) AS user_id,
    any(attribute.device_low_power_mode) AS device_low_power_mode,
    any(attribute.device_thermal_throttling_enabled) AS device_thermal_throttling_enabled,
    any(user_defined_attribute) AS user_defined_attribute,
    any(attachments) AS attachments
  from $source
  where
    type = 'bug_report'
  group by
    team_id,
    app_id,
    session_id,
    event_id
)
EOF
}

user_def_attrs_mv() {
  local mv_name="$1"
  local source="$2"
  local dest="$3"

  cat <<EOF
create materialized view $mv_name to $dest
(
  \`team_id\` UUID,
  \`app_id\` UUID,
  \`event_id\` UUID,
  \`session_id\` UUID,
  \`app_version\` Tuple(
      LowCardinality(String),
      LowCardinality(String)),
  \`os_version\` Tuple(
      LowCardinality(String),
      LowCardinality(String)),
  \`bug_report\` Bool,
  \`key\` LowCardinality(String),
  \`type\` Enum8('string' = 1, 'int64' = 2, 'float64' = 3, 'bool' = 4),
  \`value\` String,
  \`timestamp\` DateTime64(3, 'UTC')
)
as select distinct
  e.team_id,
  e.app_id,
  e.id as event_id,
  e.session_id,
  (e.attribute.app_version, e.attribute.app_build) as app_version,
  (e.attribute.os_name, e.attribute.os_version) as os_version,
  if(e.type = 'bug_report', true, false) as bug_report,
  arr_key as key,
  arr_val.1 as type,
  arr_val.2 as value,
  e.timestamp as timestamp
from $source as e
array join
  mapKeys(e.user_defined_attribute) as arr_key,
  mapValues(e.user_defined_attribute) as arr_val
where length(e.user_defined_attribute) > 0
group by
  team_id,
  app_id,
  app_version,
  os_version,
  e.type,
  key,
  type,
  value,
  event_id,
  session_id,
  timestamp
EOF
}

sessions_index_mv() {
  local mv_name="$1"
  local source="$2"
  local dest="$3"

  cat <<EOF
  create materialized view $mv_name
  to $dest
  as
  select
    team_id,
    app_id,
    (attribute.app_version, attribute.app_build) as app_version,
    session_id,
    min(timestamp) as first_event_timestamp,
    max(timestamp) as last_event_timestamp
  from $source
  group by
    team_id,
    app_id,
    app_version,
    session_id
EOF
}

sessions_mv() {
  local mv_name="$1"
  local source="$2"
  local dest="$3"

  cat <<EOF
  create materialized view $mv_name
  to $dest
  as
  select
    session_id,
    team_id,
    app_id,
    (attribute.app_version, attribute.app_build) as app_version,
    (attribute.os_name, attribute.os_version) as os_version,
    min(timestamp) as first_event_timestamp,
    max(timestamp) as last_event_timestamp,
    groupUniqArrayStateIf(\`attribute.user_id\`, \`attribute.user_id\` != '') as user_ids,
    groupUniqArrayState(\`inet.country_code\`) as country_codes,
    groupUniqArrayState(\`attribute.network_provider\`) as network_providers,
    groupUniqArrayState(\`attribute.network_type\`) as network_types,
    groupUniqArrayState(\`attribute.network_generation\`) as network_generations,
    groupUniqArrayState(\`type\`) as unique_types,
    groupUniqArrayStateIf(\`custom.name\`, \`type\` = 'custom') as unique_custom_type_names,
    groupUniqArrayStateIf(\`string.string\`, \`string.string\` != '') as unique_strings,
    groupUniqArrayStateIf(lifecycle_activity.class_name, type = 'lifecycle_activity' and lifecycle_activity.class_name != '') as unique_view_classnames,
    groupUniqArrayStateIf(lifecycle_fragment.class_name, type = 'lifecycle_fragment' and lifecycle_fragment.class_name != '') as unique_subview_classnames,
    groupUniqArrayStateIf(
      tuple(
        simpleJSONExtractString(\`exception.exceptions\`, 'type'),
        simpleJSONExtractString(\`exception.exceptions\`, 'message'),
        simpleJSONExtractString(\`exception.exceptions\`, 'file_name'),
        simpleJSONExtractString(\`exception.exceptions\`, 'class_name'),
        simpleJSONExtractString(\`exception.exceptions\`, 'method_name')
      ),
      type = 'exception' and exception.handled = 0
    ) as unique_unhandled_exceptions,
    groupUniqArrayStateIf(
      tuple(
        simpleJSONExtractString(\`exception.exceptions\`, 'type'),
        simpleJSONExtractString(\`exception.exceptions\`, 'message'),
        simpleJSONExtractString(\`exception.exceptions\`, 'file_name'),
        simpleJSONExtractString(\`exception.exceptions\`, 'class_name'),
        simpleJSONExtractString(\`exception.exceptions\`, 'method_name')
      ),
      type = 'exception' and exception.handled = 1
    ) as unique_handled_exceptions,
    groupUniqArrayStateIf(
      tuple(
        simpleJSONExtractString(\`anr.exceptions\`, 'type'),
        simpleJSONExtractString(\`anr.exceptions\`, 'message'),
        simpleJSONExtractString(\`anr.exceptions\`, 'file_name'),
        simpleJSONExtractString(\`anr.exceptions\`, 'class_name'),
        simpleJSONExtractString(\`anr.exceptions\`, 'method_name')
      ),
      type = 'anr'
    ) as unique_anrs,
    groupUniqArrayStateIf(
      tuple(\`gesture_click.target\`, \`gesture_click.target_id\`),
      type = 'gesture_click'
    ) as unique_click_targets,
    groupUniqArrayStateIf(
      tuple(\`gesture_long_click.target\`, \`gesture_long_click.target_id\`),
      type = 'gesture_long_click'
    ) as unique_longclick_targets,
    groupUniqArrayStateIf(
      tuple(\`gesture_scroll.target\`, \`gesture_scroll.target_id\`),
      type = 'gesture_scroll'
    ) as unique_scroll_targets,
    sumState(toUInt64(1)) as event_count,
    sumStateIf(toUInt64(1), type = 'exception' and exception.handled = 0) as crash_count,
    sumStateIf(toUInt64(1), type = 'anr') as anr_count,
    sumStateIf(toUInt64(1), type = 'bug_report') as bug_report_count,
    sumStateIf(toUInt64(1), lifecycle_app.type = 'background') as background_count,
    sumStateIf(toUInt64(1), lifecycle_app.type = 'foreground') as foreground_count,
    sumMapState(tuple(array(type), array(toUInt64(1)))) as event_type_counts,
    argMax(\`attribute.device_name\`, timestamp) as device_name,
    argMax(\`attribute.device_manufacturer\`, timestamp) as device_manufacturer,
    argMax(\`attribute.device_model\`, timestamp) as device_model,
    groupUniqArrayState(\`attribute.device_locale\`) as device_locales
  from $source
  group by
    team_id,
    app_id,
    session_id,
    app_version,
    os_version
EOF
}

span_filters_mv() {
  local mv_name="$1"
  local source="$2"
  local dest="$3"

  cat <<EOF
  create materialized view $mv_name
  to $dest
  (
    \`team_id\` UUID,
    \`app_id\` UUID,
    \`end_of_month\` Date,
    \`app_version\` String,
    \`os_version\` String,
    \`country_code\` LowCardinality(String),
    \`network_provider\` LowCardinality(String),
    \`network_type\` LowCardinality(String),
    \`network_generation\` LowCardinality(String),
    \`device_locale\` LowCardinality(String),
    \`device_manufacturer\` LowCardinality(String),
    \`device_name\` LowCardinality(String)
  )
  as select distinct
      team_id,
      app_id,
      toLastDayOfMonth(start_time) AS end_of_month,
      attribute.app_version AS app_version,
      attribute.os_version AS os_version,
      attribute.country_code AS country_code,
      attribute.network_provider AS network_provider,
      attribute.network_type AS network_type,
      attribute.network_generation AS network_generation,
      attribute.device_locale AS device_locale,
      attribute.device_manufacturer AS device_manufacturer,
      attribute.device_name AS device_name
  from $source
  where
    (toString(attribute.os_version) != '')
    and (toString(attribute.country_code) != '')
    and (toString(attribute.network_provider) != '')
    and (toString(attribute.network_type) != '')
    and (toString(attribute.network_generation) != '')
    and (toString(attribute.device_locale) != '')
    and (toString(attribute.device_manufacturer) != '')
    and (toString(attribute.device_name) != '')
  group by
      team_id,
      app_id,
      end_of_month,
      attribute.app_version,
      attribute.os_version,
      attribute.country_code,
      attribute.network_provider,
      attribute.network_type,
      attribute.network_generation,
      attribute.device_locale,
      attribute.device_manufacturer,
      attribute.device_name
EOF
}

span_metrics_mv() {
  local mv_name="$1"
  local source="$2"
  local dest="$3"

  cat <<EOF
  create materialized view $mv_name
  to $dest
  (
    team_id UUID,
    app_id UUID,
    span_name LowCardinality(String),
    span_id FixedString(16),
    status UInt8,
    timestamp DateTime('UTC'),
    app_version Tuple(
        LowCardinality(String),
        LowCardinality(String)),
    os_version Tuple(
        LowCardinality(String),
        LowCardinality(String)),
    country_code LowCardinality(String),
    network_provider LowCardinality(String),
    network_type LowCardinality(String),
    network_generation LowCardinality(String),
    device_locale LowCardinality(String),
    device_manufacturer LowCardinality(String),
    device_name LowCardinality(String),
    device_low_power_mode Bool,
    device_thermal_throttling_enabled Bool,
    p50 AggregateFunction(quantile(0.5), Int64),
    p90 AggregateFunction(quantile(0.9), Int64),
    p95 AggregateFunction(quantile(0.95), Int64),
    p99 AggregateFunction(quantile(0.99), Int64)
  )
  as select
    team_id,
    app_id,
    span_name,
    span_id,
    status,
    toStartOfFifteenMinutes(start_time) AS timestamp,
    attribute.app_version AS app_version,
    attribute.os_version AS os_version,
    attribute.country_code AS country_code,
    attribute.network_provider AS network_provider,
    attribute.network_type AS network_type,
    attribute.network_generation AS network_generation,
    attribute.device_locale AS device_locale,
    attribute.device_manufacturer AS device_manufacturer,
    attribute.device_name AS device_name,
    attribute.device_low_power_mode AS device_low_power_mode,
    attribute.device_thermal_throttling_enabled AS device_thermal_throttling_enabled,
    quantileState(0.5)(dateDiff('ms', start_time, end_time)) AS p50,
    quantileState(0.9)(dateDiff('ms', start_time, end_time)) AS p90,
    quantileState(0.95)(dateDiff('ms', start_time, end_time)) AS p95,
    quantileState(0.99)(dateDiff('ms', start_time, end_time)) AS p99
  from $source
  group by
    team_id,
    app_id,
    span_name,
    span_id,
    status,
    timestamp,
    app_version,
    os_version,
    country_code,
    network_provider,
    network_type,
    network_generation,
    device_locale,
    device_manufacturer,
    device_name,
    device_low_power_mode,
    device_thermal_throttling_enabled
EOF
}

span_user_def_attrs_mv() {
  local mv_name="$1"
  local source="$2"
  local dest="$3"

  cat <<EOF
create materialized view $mv_name to $dest
(
  \`team_id\` UUID,
  \`app_id\` UUID,
  \`span_id\` FixedString(16),
  \`session_id\` UUID,
  \`app_version\` Tuple(
      LowCardinality(String),
      LowCardinality(String)),
  \`os_version\` Tuple(
      LowCardinality(String),
      LowCardinality(String)),
  \`key\` LowCardinality(String),
  \`type\` Enum8('string' = 1, 'int64' = 2, 'float64' = 3, 'bool' = 4),
  \`value\` String,
  \`timestamp\` DateTime64(3, 'UTC')
)
as select distinct
  team_id,
  app_id,
  span_id,
  session_id,
  attribute.app_version as app_version,
  attribute.os_version as os_version,
  arr_key as key,
  arr_val.1 as type,
  arr_val.2 as value,
  start_time as timestamp
from $source
array join
  mapKeys(user_defined_attribute) as arr_key,
  mapValues(user_defined_attribute) as arr_val
where length(user_defined_attribute) > 0
group by
  team_id,
  app_id,
  app_version,
  os_version,
  key,
  type,
  value,
  span_id,
  session_id,
  timestamp
EOF
}

# connect to cloud database
USE_CLOUD=1

# replay chunk size
CHUNK_SIZE=10000

if [[ "$USE_CLOUD" -eq 1 ]]; then
  CHUNK_SIZE=10000000
fi

# list of partitions to migrate
# PARTITIONS=(202509 202510 202511 202512 202601)
PARTITIONS=(202601)

clickhouse_query() {
  local admin_user
  local admin_password
  local dbname

  # admin_user=$(get_env_variable CLICKHOUSE_ADMIN_USER)
  # admin_password=$(get_env_variable CLICKHOUSE_ADMIN_PASSWORD)
  admin_user="app_admin"
  admin_password="Da2a-5Up8R.nRJXks5RiFL-jr"
  dbname=measure

  if [[ "$USE_CLOUD" -eq 1 ]]; then
    host="pa5ct2shp1.us-central1.gcp.clickhouse.cloud"
    clickhouse_client \
      --user "$admin_user" \
      --password "$admin_password" \
      --database "$dbname" \
      --host "$host" \
      --port 9440 \
      --secure \
      --progress \
      --receive_timeout 3600 \
      "$@"
  else
    clickhouse_client \
      --user "$admin_user" \
      --password "$admin_password" \
      --database "$dbname" \
      --receive_timeout 3600 \
      --progress \
      "$@"
  fi
}

create_resources() {
  echo "  ✔ Create new events"
  clickhouse_query --query "$events_new_table"

  echo "  ✔ Create new event filters"
  clickhouse_query --query "$app_filters_new_table"
  clickhouse_query --query "drop table if exists app_filters_new_mv sync"
  clickhouse_query --query "$(app_filters_mv 'app_filters_new_mv' 'events_new' 'app_filters_new')"

  echo "  ✔ Create new event metrics"
  clickhouse_query --query "$app_metrics_new_table"
  clickhouse_query --query "drop table if exists app_metrics_new_mv sync"
  clickhouse_query --query "$(app_metrics_mv 'app_metrics_new_mv' 'events_new' 'app_metrics_new')"

  echo "  ✔ Create new journey"
  clickhouse_query --query "$journey_new_table"
  clickhouse_query --query "drop table if exists journey_new_mv sync"
  clickhouse_query --query "$(journey_mv 'journey_new_mv' 'events_new' 'journey_new')"

  echo "  ✔ Create new bug reports"
  clickhouse_query --query "$bug_reports_new_table"
  clickhouse_query --query "drop table if exists bug_reports_new_mv sync"
  clickhouse_query --query "$(bug_reports_mv 'bug_reports_new_mv' 'events_new' 'bug_reports_new')"

  echo "  ✔ Create new user defined attributes"
  clickhouse_query --query "$user_def_attrs_new_table"
  clickhouse_query --query "drop table if exists user_def_attrs_new_mv sync"
  clickhouse_query --query "$(user_def_attrs_mv 'user_def_attrs_new_mv' 'events_new' 'user_def_attrs_new')"

  echo "  ✔ Create new sessions index"
  clickhouse_query --query "$sessions_index_new_table"
  clickhouse_query --query "drop table if exists sessions_index_new_mv sync"
  clickhouse_query --query "$(sessions_index_mv 'sessions_index_new_mv' 'events_new' 'sessions_index_new')"

  echo "  ✔ Create new sessions"
  clickhouse_query --query "$sessions_new_table"
  clickhouse_query --query "drop table if exists sessions_new_mv sync"
  clickhouse_query --query "$(sessions_mv 'sessions_new_mv' 'events_new' 'sessions_new')"

  echo "  ✔ Create new unhandled exception groups"
  clickhouse_query --query "$unhandled_exception_groups_new_table"

  echo "  ✔ Create new anr groups"
  clickhouse_query --query "$anr_groups_new_table"

  echo "  ✔ Create new spans"
  clickhouse_query --query "$spans_new_table"

  echo "  ✔ Create new span filters"
  clickhouse_query --query "$span_filters_new_table"
  clickhouse_query --query "drop table if exists span_filters_new_mv sync"
  clickhouse_query --query "$(span_filters_mv 'span_filters_new_mv' 'spans_new' 'span_filters_new')"

  echo "  ✔ Create new span metrics"
  clickhouse_query --query "$span_metrics_new_table"
  clickhouse_query --query "drop table if exists span_metrics_new_mv sync"
  clickhouse_query --query "$(span_metrics_mv 'span_metrics_new_mv' 'spans_new' 'span_metrics_new')"

  echo "  ✔ Create new span user defined attributes"
  clickhouse_query --query "$span_user_def_attrs_new_table"
  clickhouse_query --query "drop table if exists span_user_def_attrs_new_mv sync"
  clickhouse_query --query "$(span_user_def_attrs_mv 'span_user_def_attrs_new_mv' 'spans_new' 'span_user_def_attrs_new')"
}

replay_events() {
  echo "  ✔ Replaying events"

  if [[ "$USE_CLOUD" -eq 1 ]]; then
    if [[ ${#PARTITIONS[@]} -eq 0 ]]; then
      echo "  ✗ partitions array is empty – set it globally before calling replay_events in cloud mode"
      return 1
    fi

    echo "  ✔ Preparing row counts"
    local event_rows
    event_rows=$(count_rows 'events')
    local moved_rows=0

    for part in "${PARTITIONS[@]}"; do
      echo "  ✔ Starting partition $part"

      local offset=0
      while true; do
        local chunk_count
        chunk_count=$(clickhouse_query --query "
          select count()
          from (
            select 1
            from events
            where toYYYYMM(timestamp) = $part
            order by (app_id, session_id, timestamp, id)
            limit $CHUNK_SIZE offset $offset
          )
        ")

        # trim leading/trailing whitespace
        chunk_count=${chunk_count##[[:space:]]*}
        chunk_count=${chunk_count%%[[:space:]]*}

        if [[ -z "$chunk_count" || "$chunk_count" -eq 0 ]]; then
          echo "  ✔ Finished partition $part"
          break
        fi

        echo "  ✔ Replaying chunk of $chunk_count rows (offset $offset) in partition $part"

        if ! clickhouse_query --query "
          insert into events_new
          select
            id,
            team_id,
            app_id,
            session_id,
            timestamp,
            inserted_at,
            type,
            user_triggered,
            * except (
              id,
              team_id,
              app_id,
              session_id,
              timestamp,
              inserted_at,
              type,
              user_triggered
            )
          from events
          where toYYYYMM(timestamp) = $part
          order by (app_id, session_id, timestamp, id)
          limit $CHUNK_SIZE offset $offset
          settings
            min_insert_block_size_rows = 10484490,
            max_block_size = 1000000,
            max_threads = 16
        "; then
          echo "  ✗ Insert failed at offset $offset in partition $part"
          return 1
        fi

        offset=$((offset + CHUNK_SIZE))
        moved_rows=$((moved_rows + CHUNK_SIZE))
        echo "  ✔ Progress ($((moved_rows / event_rows)))"
      done
    done

    echo "  ✔ Total Rows Moved: $moved_rows"
    echo "  ✔ Finished replaying all cloud partitions"
  else
    local offset=0
    while true; do
      local chunk_count
      chunk_count=$(clickhouse_query --query "
        select count()
        from (
          select 1
          from events
          order by (app_id, session_id, timestamp, id)
          limit $CHUNK_SIZE offset $offset
        )
      ")

      # trim leading/trailing whitespace
      chunk_count=${chunk_count##[[:space:]]*}
      chunk_count=${chunk_count%%[[:space:]]*}

      if [[ -z "$chunk_count" || "$chunk_count" -eq 0 ]]; then
        echo "  ✔ Finished replaying all events"
        break
      fi

      echo "  ✔ Replaying chunk of $chunk_count rows (offset $offset)"

      if ! clickhouse_query --query "
        insert into events_new
        select
          id,
          team_id,
          app_id,
          session_id,
          timestamp,
          inserted_at,
          type,
          user_triggered,
          * except (
            id,
            team_id,
            app_id,
            session_id,
            timestamp,
            inserted_at,
            type,
            user_triggered
          )
        from events
        order by (app_id, session_id, timestamp, id)
        limit $CHUNK_SIZE offset $offset
      "; then
        echo "  ✗ Insert failed at offset $offset"
        return 1
      fi

      offset=$((offset + CHUNK_SIZE))
    done
  fi
}

replay_unhandled_exception_groups() {
  echo "  ✔ Replaying unhandled_exception_groups"

  if ! clickhouse_query --query "
    insert into unhandled_exception_groups_new (
      team_id,
      app_id,
      id,
      type,
      message,
      method_name,
      file_name,
      line_number,
      app_version,
      os_versions,
      country_codes,
      network_providers,
      network_types,
      network_generations,
      device_locales,
      device_manufacturers,
      device_names,
      device_models,
      count,
      timestamp
    )
    select
      g.team_id,
      g.app_id,
      g.id,
      g.type,
      g.message,
      g.method_name,
      g.file_name,
      g.line_number,
      e.app_version as app_version,
      groupUniqArrayState(e.os_version) as os_versions,
      groupUniqArrayState(e.country_code) as country_codes,
      groupUniqArrayState(e.network_provider) as network_providers,
      groupUniqArrayState(e.network_type) as network_types,
      groupUniqArrayState(e.network_generation) as network_generations,
      groupUniqArrayState(e.device_locale) as device_locales,
      groupUniqArrayState(e.device_manufacturer) as device_manufacturers,
      groupUniqArrayState(e.device_name) as device_names,
      groupUniqArrayState(e.device_model) as device_models,
      sumState(e.exception_count) as count,
      timestamp
    from unhandled_exception_groups as g
    left join
    (
      select
        team_id,
        app_id,
        timestamp,
        exception.fingerprint as id,
        (attribute.app_version, attribute.app_build) as app_version,
        (attribute.os_name, attribute.os_version) as os_version,
        inet.country_code as country_code,
        attribute.network_provider as network_provider,
        attribute.network_type as network_type,
        attribute.network_generation as network_generation,
        attribute.device_locale as device_locale,
        attribute.device_manufacturer as device_manufacturer,
        attribute.device_name as device_name,
        attribute.device_model as device_model,
        count() as exception_count
      from events_new
      where
        type = 'exception'
        and exception.handled = false
        and exception.fingerprint != ''
      group by
        team_id,
        app_id,
        timestamp,
        app_version,
        os_version,
        country_code,
        network_provider,
        network_type,
        network_generation,
        device_locale,
        device_manufacturer,
        device_name,
        device_model,
        exception.fingerprint
    ) as e
    on g.team_id = e.team_id
       and g.app_id = e.app_id
       and g.id = e.id
    group by
      g.team_id,
      g.app_id,
      g.id,
      g.type,
      g.message,
      g.method_name,
      g.file_name,
      g.line_number,
      e.app_version,
      e.timestamp
    order by (g.app_id, g.id)
  "; then
    echo "  ✗ Insert failed while replaying unhandled_exception_groups_new"
    return 1
  fi
}

replay_anr_groups() {
  echo "  ✔ Replaying anr_groups"

  if ! clickhouse_query --query "
    insert into anr_groups_new (
      team_id,
      app_id,
      id,
      type,
      message,
      method_name,
      file_name,
      line_number,
      app_version,
      os_versions,
      country_codes,
      network_providers,
      network_types,
      network_generations,
      device_locales,
      device_manufacturers,
      device_names,
      device_models,
      count,
      timestamp
    )
    select
      g.team_id,
      g.app_id,
      g.id,
      g.type,
      g.message,
      g.method_name,
      g.file_name,
      g.line_number,
      e.app_version as app_version,
      groupUniqArrayState(e.os_version) as os_versions,
      groupUniqArrayState(e.country_code) as country_codes,
      groupUniqArrayState(e.network_provider) as network_providers,
      groupUniqArrayState(e.network_type) as network_types,
      groupUniqArrayState(e.network_generation) as network_generations,
      groupUniqArrayState(e.device_locale) as device_locales,
      groupUniqArrayState(e.device_manufacturer) as device_manufacturers,
      groupUniqArrayState(e.device_name) as device_names,
      groupUniqArrayState(e.device_model) as device_models,
      sumState(e.anr_count) as count,
      timestamp
    from anr_groups as g
    left join
    (
      select
        team_id,
        app_id,
        timestamp,
        anr.fingerprint as id,
        (attribute.app_version, attribute.app_build) as app_version,
        (attribute.os_name, attribute.os_version) as os_version,
        inet.country_code as country_code,
        attribute.network_provider as network_provider,
        attribute.network_type as network_type,
        attribute.network_generation as network_generation,
        attribute.device_locale as device_locale,
        attribute.device_manufacturer as device_manufacturer,
        attribute.device_name as device_name,
        attribute.device_model as device_model,
        count() as anr_count
      from events_new
      where
        type = 'anr'
        and anr.fingerprint != ''
      group by
        team_id,
        app_id,
        timestamp,
        app_version,
        os_version,
        country_code,
        network_provider,
        network_type,
        network_generation,
        device_locale,
        device_manufacturer,
        device_name,
        device_model,
        anr.fingerprint
    ) as e
    on g.team_id = e.team_id
       and g.app_id = e.app_id
       and g.id = e.id
    group by
      g.team_id,
      g.app_id,
      g.id,
      g.type,
      g.message,
      g.method_name,
      g.file_name,
      g.line_number,
      e.app_version,
      e.timestamp
    order by (g.app_id, g.id)
  "; then
    echo "  ✗ Insert failed while replaying anr_groups_new"
    return 1
  fi
}

replay_spans() {
  echo "  ✔ Replaying spans"
  if ! clickhouse_query --query "
    insert into spans_new
    select
      *
    from spans
  "; then
    echo "  ✗ Insert failed while replaying spans_new"
    return 1
  fi
}

exchange_resources() {
  echo "  ✔ Exchange event filters"
  clickhouse_query --query "exchange tables app_filters_new and app_filters"

  echo "  ✔ Exchange event metrics"
  clickhouse_query --query "exchange tables app_metrics_new and app_metrics"

  echo "  ✔ Exchange journey"
  clickhouse_query --query "exchange tables journey_new and journey"

  echo "  ✔ Exchange bug reports"
  clickhouse_query --query "exchange tables bug_reports_new and bug_reports"

  echo "  ✔ Exchange user defined attributes"
  clickhouse_query --query "exchange tables user_def_attrs_new and user_def_attrs"

  # echo "  ✔ Exchange sessions index"
  # clickhouse_query --query "exchange tables sessions_index_new and sessions_index"

  echo "  ✔ Exchange sessions"
  clickhouse_query --query "exchange tables sessions_new and sessions"

  echo "  ✔ Exchange events"
  clickhouse_query --query "exchange tables events_new and events"

  echo "  ✔ Exchange unhandled exception groups"
  clickhouse_query --query "exchange tables unhandled_exception_groups_new and unhandled_exception_groups"

  echo "  ✔ Exchange anr groups"
  clickhouse_query --query "exchange tables anr_groups_new and anr_groups"

  echo "  ✔ Exchange span filters"
  clickhouse_query --query "exchange tables span_filters_new and span_filters"

  echo "  ✔ Exchange span metrics"
  clickhouse_query --query "exchange tables span_metrics_new and span_metrics"

  echo "  ✔ Exchange span user defined attributes"
  clickhouse_query --query "exchange tables span_user_def_attrs_new and span_user_def_attrs"

  echo "  ✔ Exchange spans"
  clickhouse_query --query "exchange tables spans_new and spans"
}

recreate_mvs() {
  echo "  ✔ Recreate event filters mv"
  clickhouse_query --query "drop table if exists app_filters_mv sync"
  clickhouse_query --query "$(app_filters_mv 'app_filters_mv' 'events' 'app_filters')"

  echo "  ✔ Recreate event metrics mv"
  clickhouse_query --query "drop table if exists app_metrics_mv sync"
  clickhouse_query --query "$(app_metrics_mv 'app_metrics_mv' 'events' 'app_metrics')"

  echo "  ✔ Recreate journey mv"
  clickhouse_query --query "drop table if exists journey_mv sync"
  clickhouse_query --query "$(journey_mv 'journey_mv' 'events' 'journey')"

  echo "  ✔ Recreate bug reports mv"
  clickhouse_query --query "drop table if exists bug_reports_mv sync"
  clickhouse_query --query "$(bug_reports_mv 'bug_reports_mv' 'events' 'bug_reports')"

  echo "  ✔ Recreate user defined attributes mv"
  clickhouse_query --query "drop table if exists user_def_attrs_mv sync"
  clickhouse_query --query "$(user_def_attrs_mv 'user_def_attrs_mv' 'events' 'user_def_attrs')"

  echo "  ✔ Recreate sessions index mv"
  clickhouse_query --query "drop table if exists sessions_index_mv sync"
  clickhouse_query --query "$(sessions_index_mv 'sessions_index_mv' 'events' 'sessions_index')"

  echo "  ✔ Recreate sessions mv"
  clickhouse_query --query "drop table if exists sessions_mv sync"
  clickhouse_query --query "$(sessions_mv 'sessions_mv' 'events' 'sessions')"

  echo "  ✔ Recreate span filters mv"
  clickhouse_query --query "drop table if exists span_filters_mv sync"
  clickhouse_query --query "$(span_filters_mv 'span_filters_mv' 'spans' 'span_filters')"

  echo "  ✔ Recreate span metrics mv"
  clickhouse_query --query "drop table if exists span_metrics_mv sync"
  clickhouse_query --query "$(span_metrics_mv 'span_metrics_mv' 'spans' 'span_metrics')"

  echo "  ✔ Recreate span user defined attributes mv"
  clickhouse_query --query "drop table if exists span_user_def_attrs_mv sync"
  clickhouse_query --query "$(span_user_def_attrs_mv 'span_user_def_attrs_mv' 'spans' 'span_user_def_attrs')"
}

drop_resources() {
  echo "  ✔ Drop event filters"
  clickhouse_query --query "drop table if exists app_filters_new_mv sync"
  clickhouse_query --query "drop table if exists app_filters_new sync"

  echo "  ✔ Drop event metrics"
  clickhouse_query --query "drop table if exists app_metrics_new_mv sync"
  clickhouse_query --query "drop table if exists app_metrics_new sync"

  echo "  ✔ Drop journey"
  clickhouse_query --query "drop table if exists journey_new_mv sync"
  clickhouse_query --query "drop table if exists journey_new sync"

  echo "  ✔ Drop bug reports"
  clickhouse_query --query "drop table if exists bug_reports_new_mv sync"
  clickhouse_query --query "drop table if exists bug_reports_new sync"

  echo "  ✔ Drop user defined attributes"
  clickhouse_query --query "drop table if exists user_def_attrs_new_mv sync"
  clickhouse_query --query "drop table if exists user_def_attrs_new sync"

  echo "  ✔ Drop sessions"
  clickhouse_query --query "drop table if exists sessions_new_mv sync"
  clickhouse_query --query "drop table if exists sessions_new sync"

  echo "  ✔ Drop unhandled_exception_groups"
  clickhouse_query --query "drop table if exists unhandled_exception_groups_new sync"

  echo "  ✔ Drop anr_groups"
  clickhouse_query --query "drop table if exists anr_groups_new sync"

  echo "  ✔ Drop span filters"
  clickhouse_query --query "drop table if exists span_filters_new_mv sync"
  clickhouse_query --query "drop table if exists span_filters_new sync"

  echo "  ✔ Drop span metrics"
  clickhouse_query --query "drop table if exists span_metrics_new_mv sync"
  clickhouse_query --query "drop table if exists span_metrics_new sync"

  echo "  ✔ Drop events"
  clickhouse_query --query "drop table if exists events_new sync"

  echo "  ✔ Drop spans"
  clickhouse_query --query "drop table if exists span_new sync"
}

verify_resources() {
  clickhouse_query --query "
  select
    (select count() from events final) as events_count,
    (select count() from events_new final) as events_new_count
  settings
    output_format_pretty_row_numbers = 0
  format
    PrettySpace
  "

  echo

  clickhouse_query --query "
  select
    (select count() from app_filters final) as app_filters_count,
    (select count() from app_filters_new final) as app_filters_new_count
  settings
    output_format_pretty_row_numbers = 0
  format
    PrettySpace
  "

  echo

  clickhouse_query --query "
  select
    (select count() from app_metrics final) as app_metrics_count,
    (select count() from app_metrics_new final) as app_metrics_new_count
  settings
    output_format_pretty_row_numbers = 0
  format
    PrettySpace
  "

  echo

  clickhouse_query --query "
  select
    (select count() from bug_reports final) as bug_reports_count,
    (select count() from bug_reports_new final) as bug_reports_new_count
  settings
    output_format_pretty_row_numbers = 0
  format
    PrettySpace
  "

  echo

  clickhouse_query --query "
  select
    (select count() from user_def_attrs final) as user_def_attrs_count,
    (select count() from user_def_attrs_new final) as user_def_attrs_new_count
  settings
    output_format_pretty_row_numbers = 0
  format
    PrettySpace
  "

  echo

  clickhouse_query --query "
  select
    (select count() from sessions final) as sessions_count,
    (select count() from sessions_new final) as sessions_new_count
  settings
    output_format_pretty_row_numbers = 0
  format
    PrettySpace
  "

  echo

  clickhouse_query --query "
  select
    (select count() from unhandled_exception_groups final) as unhandled_exception_groups_count,
    (select count() from unhandled_exception_groups_new final) as unhandled_exception_groups_new_count
  settings
    output_format_pretty_row_numbers = 0
  format
    PrettySpace
  "

  echo

  clickhouse_query --query "
  select
    (select count() from anr_groups final) as anr_groups_count,
    (select count() from anr_groups_new final) as anr_groups_new_count
  settings
    output_format_pretty_row_numbers = 0
  format
    PrettySpace
  "

  echo

  clickhouse_query --query "
  select
    (select count() from spans final) as span_count,
    (select count() from spans_new final) as spans_new_count
  settings
    output_format_pretty_row_numbers = 0
  format
    PrettySpace
  "

  echo

  clickhouse_query --query "
  select
    (select count() from span_filters final) as span_filters_count,
    (select count() from span_filters_new final) as span_filters_new_count
  settings
    output_format_pretty_row_numbers = 0
  format
    PrettySpace
  "

  echo

  clickhouse_query --query "
  select
    (select count() from span_metrics final) as span_metrics_count,
    (select count() from span_metrics_new final) as span_metrics_new_count
  settings
    output_format_pretty_row_numbers = 0
  format
    PrettySpace
  "

  echo

  clickhouse_query --query "
  select
    (select count() from span_user_def_attrs final) as span_user_def_attrs_count,
    (select count() from span_user_def_attrs_new final) as span_user_def_attrs_new_count
  settings
    output_format_pretty_row_numbers = 0
  format
    PrettySpace
  "
}

# Counts the rows for partitions
#
# Args:
#   $1: The name of the table
#
# Returns:
#   Count of rows across the partitions
#   of the table.
count_rows() {
  printf -v joined "'%s', " "${PARTITIONS[@]}"
  joined="(${joined%, })"
  local table=$1
  local result

  result=$(clickhouse_query --query "
    select
      sum(rows) as rows
    from system.parts
    where
      database = 'measure'
      and table = '$table'
      and partition in $joined
  ")

  echo "$result"
}

# kick things off
check_base_dir
set_docker_compose

# echo "Create resources..."
# create_resources

echo
echo "Replay data..."
replay_events
echo
replay_unhandled_exception_groups
echo
replay_anr_groups
echo
replay_spans
echo

echo "Verify backfill..."
verify_resources

# echo "Exchange resources..."
# exchange_resources

# echo "Recreate materialized views..."
# recreate_mvs

# echo "Drop resources..."
# drop_resources

# echo "Testing..."
# clickhouse_query --query "show tables;"
