FROM node:lts-alpine AS base
LABEL org.opencontainers.image.source=https://github.com/measure-sh/measure
LABEL org.opencontainers.image.description="Measure Web App"
LABEL org.opencontainers.image.licenses=Apache-2.0

FROM base AS builder
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

FROM base
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
CMD ["npm", "run", "dev"]
