# build stage
FROM node:lts-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json* ./
RUN apk add --no-cache ca-certificates && npm install
COPY ./ ./
COPY --from=docs . ./content/docs

FROM builder
WORKDIR /app
COPY --from=builder /app ./
CMD ["npm", "run", "dev"]
