FROM node:lts-alpine AS base

FROM base AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install

FROM base
WORKDIR /app
RUN apk add --no-cache curl
COPY --from=builder /app/node_modules ./node_modules
CMD ["npm", "run", "dev"]
