FROM node:lts-slim
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates wget \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm install

COPY . .
COPY --from=docs . ./content/docs
EXPOSE 3000

CMD ["npm", "run", "dev"]
