name: measure_flutter
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  logger: ^2.5.0
  stack_trace: ^1.12.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  plugin:
    platforms:
      android:
        package: sh.measure.flutter
        pluginClass: MeasurePlugin
      ios:
        pluginClass: MeasurePlugin
