name: measure_flutter
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: sh.measure.flutter
        pluginClass: MeasurePlugin
      ios:
        pluginClass: MeasurePlugin
