name: measure
services:
  api:
    build:
      context: ../measure-go
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/postgres
      - CLICKHOUSE_DSN=clickhouse://default:@clickhouse:9000/default
      - GIN_MODE=release
    depends_on:
      - clickhouse
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "9000:9000/tcp"
      - "8123:8123"
    ulimits:
      nofile: 262144
    volumes:
      - clickhouse-volume:/var/lib/clickhouse
      - clickhouse-volume:/var/log/clickhouse-server/logs

volumes:
  clickhouse-volume:
  postgres-volume:
