name: measure
services:
  api:
    build:
      context: ../measure-go
    ports:
      - "8080:8080"
    env_file:
      - ../measure-go/.env
    develop:
      watch:
        - path: ../measure-go
          action: rebuild
    depends_on:
      - clickhouse
      - postgres
      # - symbolicator
      - symbolicator-retrace

  symbolicator-retrace:
    build:
      context: ../symbolicator-retrace
    ports:
      - "8181:8181"
    env_file:
      - ../symbolicator-retrace/.env
    volumes:
      - symbolicator-volume:/data
    develop:
      watch:
        - path: ../symbolicator-retrace
          action: rebuild

  # symbolicator:
  #   build:
  #     context: ../symbolicator
  #   ports:
  #     - "8181:8181"
  #   env_file:
  #     - ../symbolicator/.env
  #   volumes:
  #     - symbolicator-volume:/data
  #   develop:
  #     watch:
  #       - path: ../symbolicator
  #         action: rebuild

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:23
    ports:
      - "9000:9000/tcp"
      - "8123:8123"
    ulimits:
      nofile: 262144
    volumes:
      - clickhouse-volume:/var/lib/clickhouse
      - clickhouse-volume:/var/log/clickhouse-server

volumes:
  clickhouse-volume:
  postgres-volume:
  symbolicator-volume:
