//
//  JSONWriterEscapingTests.swift
//  MeasureSDKTests
//
//  `JSONWriter` writes most scalars verbatim, without escaping, because every scalar the export path emits
//  is generated by the SDK — uuids, ISO-8601 timestamps, enum raw values, uuid-derived attachment names.
//  Only a span's name carries user input, and that one goes through `JSONSerialization`.
//
//  These tests hold both halves of that arrangement in place: that the SDK's generated values really do
//  contain nothing needing escaping, and that a hostile span name really is escaped.
//

import XCTest
@testable import Measure

final class JSONWriterEscapingTests: XCTestCase {
    private func needsEscaping(_ string: String) -> Bool {
        string.utf8.contains { $0 == UInt8(ascii: "\"") || $0 == UInt8(ascii: "\\") || $0 < 0x20 }
    }

    func testGeneratedIdentifiersNeverNeedEscaping() {
        let idProvider = UUIDProvider()

        for _ in 0..<1_000 {
            XCTAssertFalse(needsEscaping(idProvider.uuid()), "uuid() produced a value needing escaping")
            XCTAssertFalse(needsEscaping(idProvider.spanId()), "spanId() produced a value needing escaping")
            XCTAssertFalse(needsEscaping(idProvider.traceId()), "traceId() produced a value needing escaping")
        }
    }

    func testGeneratedTimestampsNeverNeedEscaping() {
        let timeProvider = BaseTimeProvider()
        let samples: [Number] = [0, 1, 1_727_272_496_000, timeProvider.now(), Number(Int32.max), 4_102_444_800_000]

        for millis in samples {
            let timestamp = timeProvider.iso8601Timestamp(timeInMillis: millis)
            XCTAssertFalse(needsEscaping(timestamp), "iso8601Timestamp(\(millis)) = \(timestamp)")
        }
    }

    func testEventAndAttachmentTypeRawValuesNeverNeedEscaping() {
        for type in EventType.allCases {
            XCTAssertFalse(needsEscaping(type.rawValue), "EventType.\(type) raw value needs escaping")
        }

        for type in [AttachmentType.screenshot, .layoutSnapshot, .layoutSnapshotJson] {
            XCTAssertFalse(needsEscaping(type.rawValue), "AttachmentType.\(type) raw value needs escaping")
        }
    }

    func testGeneratedAttachmentNamesNeverNeedEscaping() {
        let uuid = UUIDProvider().uuid()
        let names = ["\(uuid).webp", "\(uuid).svg", "\(uuid).json.gz", galleryImageName]

        for name in names {
            XCTAssertFalse(needsEscaping(name), "attachment name \(name) needs escaping")
        }
    }

    func testWireKeysNeverNeedEscaping() {
        let keys = [
            "id", "session_id", "timestamp", "type", "user_triggered", "attribute",
            "user_defined_attribute", "attachments", "name", "trace_id", "span_id", "parent_id",
            "start_time", "end_time", "duration", "status", "attributes", "checkpoints", "size", "events", "spans"
        ] + EventType.allCases.map { $0.rawValue }

        for key in keys {
            XCTAssertFalse(needsEscaping(key), "wire key \(key) needs escaping")
        }
    }

    func testHostileSpanNameIsEscapedAndRoundTrips() throws {
        let serializer = EventSerializer()

        let hostileNames = [
            #"quote " inside"#,
            #"back \ slash"#,
            "new\nline\ttab",
            "control\u{0}\u{1}\u{1f}chars",
            "emoji 🎉 and 日本語",
            "line\u{2028}separator",
            #"{"injected":"object"}"#,
            #""},{"span_id":"forged"#
        ]

        for name in hostileNames {
            let span = SpanEntity(name: name,
                                  traceId: "trace-id",
                                  spanId: "span-id",
                                  parentId: nil,
                                  sessionId: "session-id",
                                  startTime: 1_727_272_496_000,
                                  startTimeString: "2026-08-22T10:00:00.000Z",
                                  endTime: 1_727_272_496_200,
                                  endTimeString: "2026-08-22T10:00:00.200Z",
                                  duration: 200,
                                  status: 0,
                                  attributes: nil,
                                  userDefinedAttrs: nil,
                                  checkpoints: nil,
                                  hasEnded: true,
                                  isSampled: true,
                                  batchId: nil)

            let data = try XCTUnwrap(serializer.serializeSpan(span), "serializeSpan returned nil for \(name.debugDescription)")
            let json = try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any],
                                     "span with name \(name.debugDescription) did not produce a JSON object")

            XCTAssertEqual(json["name"] as? String, name, "name did not round trip for \(name.debugDescription)")
            XCTAssertEqual(json["span_id"] as? String, "span-id", "payload was corrupted by \(name.debugDescription)")
            XCTAssertEqual(json.keys.count, 9, "unexpected keys for \(name.debugDescription): \(json.keys.sorted())")
        }
    }

    func testHostileUserDefinedAttributeStaysValid() throws {
        let serializer = EventSerializer()

        let attributes: [String: AttributeValue] = [
            "quoted": .string(#"a " quote"#),
            "slashed": .string(#"a \ slash"#),
            "newline": .string("a\nnewline")
        ]
        let serialized = try XCTUnwrap(EventSerializer.serializeUserDefinedAttribute(attributes))

        let event = Event(id: "event-id",
                          sessionId: "session-id",
                          timestamp: "2026-08-22T10:00:00.000Z",
                          timestampInMillis: 1_727_272_496_000,
                          type: .custom,
                          data: CustomEventData(name: "checkout"),
                          attachments: nil,
                          attributes: Attributes(),
                          userTriggered: true,
                          userDefinedAttributes: serialized)

        let data = try XCTUnwrap(serializer.getSerialisedEvent(for: EventEntity(event, needsReporting: true)))
        let json = try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any])
        let userDefined = try XCTUnwrap(json["user_defined_attribute"] as? [String: Any])

        XCTAssertEqual(userDefined["quoted"] as? String, #"a " quote"#)
        XCTAssertEqual(userDefined["slashed"] as? String, #"a \ slash"#)
        XCTAssertEqual(userDefined["newline"] as? String, "a\nnewline")
        XCTAssertEqual(json["id"] as? String, "event-id", "payload was corrupted")
    }

    func testEscapedMatchesJSONSerializationForHostileStrings() throws {
        let samples = [
            "plain", #"with " quotes"#, #"back \ slash"#, "new\nline\ttab", "\u{0}\u{1}\u{1f}",
            "emoji 🎉", "日本語", "line\u{2028}sep", "\u{8}\u{c}\r", "", #"a"b\c/d"#
        ]

        for sample in samples {
            let escaped = JSONWriter.escaped(sample)
            let wrapped = Data("[".utf8) + escaped + Data("]".utf8)
            let parsed = try XCTUnwrap(JSONSerialization.jsonObject(with: wrapped) as? [String],
                                       "escaped(\(sample.debugDescription)) is not a valid JSON string")
            XCTAssertEqual(parsed.first, sample, "escaped(\(sample.debugDescription)) did not round trip")
        }
    }

    func testWriterOmitsAbsentValuesAndProducesAnObject() throws {
        var writer = JSONWriter()
        writer.append(key: "id", unescapedIdentifier: "event-id")
        writer.append(key: "user_triggered", bool: false)
        writer.append(key: "size", int: -42)
        writer.append(key: "attribute", rawJson: Data(#"{"a":1}"#.utf8))
        writer.append(key: "absent_raw", rawJson: nil)
        writer.append(key: "absent_empty", rawJson: Data())
        writer.append(key: "absent_string", optionalString: nil)
        writer.append(key: "absent_identifier", optionalUnescapedIdentifier: nil)
        writer.append(key: "checkpoints", rawJson: nil, fallback: Data("[]".utf8))

        let json = try XCTUnwrap(JSONSerialization.jsonObject(with: writer.finalize()) as? [String: Any])

        XCTAssertEqual(json["id"] as? String, "event-id")
        XCTAssertEqual(json["user_triggered"] as? Bool, false)
        XCTAssertEqual((json["size"] as? NSNumber)?.intValue, -42)
        XCTAssertEqual((json["attribute"] as? [String: Any])?["a"] as? NSNumber, 1)
        XCTAssertEqual((json["checkpoints"] as? [Any])?.count, 0)
        XCTAssertFalse(json.keys.contains { $0.hasPrefix("absent") }, "absent values must omit their key")
    }
}
