package sh.measure.android.attributes

internal object Attribute {
    const val THREAD_NAME = "thread_name"
    const val DEVICE_NAME_KEY = "device_name"
    const val DEVICE_MODEL_KEY = "device_model"
    const val DEVICE_MANUFACTURER_KEY = "device_manufacturer"
    const val DEVICE_TYPE_KEY = "device_type"
    const val DEVICE_IS_FOLDABLE_KEY = "device_is_foldable"
    const val DEVICE_IS_PHYSICAL_KEY = "device_is_physical"
    const val DEVICE_DENSITY_DPI_KEY = "device_density_dpi"
    const val DEVICE_WIDTH_PX_KEY = "device_width_px"
    const val DEVICE_HEIGHT_PX_KEY = "device_height_px"
    const val DEVICE_DENSITY_KEY = "device_density"
    const val DEVICE_LOCALE_KEY = "device_locale"
    const val APP_VERSION_KEY = "app_version"
    const val APP_BUILD_KEY = "app_build"
    const val APP_UNIQUE_ID_KEY = "app_unique_id"
    const val MEASURE_SDK_VERSION = "measure_sdk_version"
    const val OS_NAME_KEY = "os_name"
    const val OS_VERSION_KEY = "os_version"
    const val OS_PAGE_SIZE = "os_page_size"
    const val PLATFORM_KEY = "platform"
    const val NETWORK_TYPE_KEY = "network_type"
    const val NETWORK_GENERATION_KEY = "network_generation"
    const val NETWORK_PROVIDER_KEY = "network_provider"
    const val INSTALLATION_ID_KEY = "installation_id"
    const val USER_ID_KEY = "user_id"
    const val DEVICE_LOW_POWER_ENABLED = "device_low_power_mode"
    const val DEVICE_THERMAL_THROTTLING_ENABLED = "device_thermal_throttling_enabled"
}
