/**
 * Extracts SDK versions from the rendered SDK integration guide and emits
 * a TypeScript constants file consumed by app/components/onboarding.tsx.
 *
 * Source of truth: docs/sdk-integration-guide.md (already kept up to date by
 * the per-platform release prep workflows in .github/workflows/).
 *
 * Runs after copy_docs.js in the prebuild/dev/build/pretest chains, so the
 * onboarding snippets always show versions matching the rendered docs.
 */
const fs = require("fs");
const path = require("path");

const SCRIPT_DIR = __dirname;
const DASHBOARD_ROOT = path.join(SCRIPT_DIR, "..");
const REPO_ROOT = path.join(DASHBOARD_ROOT, "..", "..");
const DOCS_SOURCE = path.join(REPO_ROOT, "docs", "sdk-integration-guide.md");
const CONTENT_DOCS_SOURCE = path.join(
  DASHBOARD_ROOT,
  "content",
  "docs",
  "sdk-integration-guide.md",
);
const OUTPUT_FILE = path.join(
  DASHBOARD_ROOT,
  "app",
  "components",
  "sdk_versions.generated.ts",
);

const PATTERNS = {
  androidSdk: /measure-android:(\d+\.\d+\.\d+)/,
  iosSdk: /branch:\s*["']ios-v(\d+\.\d+\.\d+)["']/,
  flutter: /measure_flutter:\s*\^(\d+\.\d+\.\d+)/,
};

// TODO: replace with a regex pattern once the React Native section lands in
// docs/sdk-integration-guide.md. Until then we ship a hardcoded value so the
// onboarding UI has something to render.
const HARDCODED_VERSIONS = {
  reactNative: "0.1.0",
};

function findSource() {
  // Prefer the canonical repo-root docs/ source. Fall back to content/docs/
  // for Docker builds where the monorepo root is not present.
  if (fs.existsSync(DOCS_SOURCE)) {
    return DOCS_SOURCE;
  }
  if (fs.existsSync(CONTENT_DOCS_SOURCE)) {
    return CONTENT_DOCS_SOURCE;
  }
  throw new Error(
    `Could not find sdk-integration-guide.md at ${DOCS_SOURCE} or ${CONTENT_DOCS_SOURCE}`,
  );
}

function extract(content) {
  const out = { ...HARDCODED_VERSIONS };
  for (const [key, pattern] of Object.entries(PATTERNS)) {
    const match = content.match(pattern);
    if (!match) {
      throw new Error(
        `Could not extract ${key} version from sdk-integration-guide.md (pattern: ${pattern})`,
      );
    }
    out[key] = match[1];
  }
  return out;
}

function generate(versions) {
  return `// Generated by scripts/extract_sdk_versions.js — do not edit by hand.
// Sourced from docs/sdk-integration-guide.md at build time.

export const SDK_VERSIONS = {
  androidSdk: ${JSON.stringify(versions.androidSdk)},
  iosSdk: ${JSON.stringify(versions.iosSdk)},
  flutter: ${JSON.stringify(versions.flutter)},
  reactNative: ${JSON.stringify(versions.reactNative)},
} as const
`;
}

if (require.main === module) {
  const source = findSource();
  console.log(
    `Extracting SDK versions from ${path.relative(REPO_ROOT, source)}...`,
  );
  const content = fs.readFileSync(source, "utf-8");
  const versions = extract(content);
  fs.writeFileSync(OUTPUT_FILE, generate(versions));
  console.log(
    `Wrote SDK versions to ${path.relative(REPO_ROOT, OUTPUT_FILE)}:`,
  );
  for (const [k, v] of Object.entries(versions)) {
    console.log(`  ${k}: ${v}`);
  }
}

module.exports = { extract, generate, PATTERNS, HARDCODED_VERSIONS };
