/**
 * Extracts SDK versions from the rendered SDK integration guide and emits
 * a TypeScript constants file consumed by app/components/onboarding.tsx.
 *
 * Source of truth: content/docs/sdk-integration-guide.mdx (already kept up
 * to date by the per-platform release prep workflows in .github/workflows/).
 *
 * Runs in the prebuild/dev/build/pretest chains, so the onboarding snippets
 * always show versions matching the rendered docs.
 */
const fs = require("fs");
const path = require("path");

const SCRIPT_DIR = __dirname;
const DASHBOARD_ROOT = path.join(SCRIPT_DIR, "..");
const DOCS_SOURCE = path.join(
  DASHBOARD_ROOT,
  "content",
  "docs",
  "sdk-integration-guide.mdx",
);
const OUTPUT_FILE = path.join(
  DASHBOARD_ROOT,
  "app",
  "components",
  "sdk_versions.generated.ts",
);

const PATTERNS = {
  androidSdk: /measure-android:(\d+\.\d+\.\d+)/,
  iosSdk: /branch:\s*["']ios-v(\d+\.\d+\.\d+)["']/,
  flutter: /measure_flutter:\s*\^(\d+\.\d+\.\d+)/,
  reactNative: /@measuresh\/react-native@(\d+\.\d+\.\d+)/,
  kmp: /measure-kmp:(\d+\.\d+\.\d+)/,
};

function findSource() {
  if (fs.existsSync(DOCS_SOURCE)) {
    return DOCS_SOURCE;
  }
  throw new Error(`Could not find the SDK integration guide at ${DOCS_SOURCE}`);
}

function extract(content) {
  const out = {};
  for (const [key, pattern] of Object.entries(PATTERNS)) {
    const match = content.match(pattern);
    if (!match) {
      throw new Error(
        `Could not extract ${key} version from the SDK integration guide (pattern: ${pattern})`,
      );
    }
    out[key] = match[1];
  }
  return out;
}

function generate(versions) {
  return `// Generated by scripts/extract_sdk_versions.js — do not edit by hand.
// Sourced from content/docs/sdk-integration-guide.mdx at build time.

export const SDK_VERSIONS = {
  androidSdk: ${JSON.stringify(versions.androidSdk)},
  iosSdk: ${JSON.stringify(versions.iosSdk)},
  flutter: ${JSON.stringify(versions.flutter)},
  reactNative: ${JSON.stringify(versions.reactNative)},
  kmp: ${JSON.stringify(versions.kmp)},
} as const
`;
}

if (require.main === module) {
  const source = findSource();
  console.log(
    `Extracting SDK versions from ${path.relative(DASHBOARD_ROOT, source)}...`,
  );
  const content = fs.readFileSync(source, "utf-8");
  const versions = extract(content);
  fs.writeFileSync(OUTPUT_FILE, generate(versions));
  console.log(
    `Wrote SDK versions to ${path.relative(DASHBOARD_ROOT, OUTPUT_FILE)}:`,
  );
  for (const [k, v] of Object.entries(versions)) {
    console.log(`  ${k}: ${v}`);
  }
}

module.exports = { extract, generate, PATTERNS };
