package sh.measure

import org.gradle.api.Action
import org.gradle.api.model.ObjectFactory
import javax.inject.Inject

/**
 * Configuration options (Gradle plugin extensions) for the MeasurePlugin.
 *
 * Measure plugin is enabled by default for all variants, to disable all features
 * of the plugin for a specific variant, for example all debug variants:
 *
 * ```kotlin
 * measure {
 *   variantFilter {
 *      if (name.contains("debug")) {
 *          enabled = false
 *      }
 * }
 * ```
 */
open class MeasurePluginExtension @Inject constructor(objects: ObjectFactory) {
    var httpHeaders: Map<String, String> = emptyMap()

    /**
     * Additional packages whose `android.util.Log` calls are auto-collected as log events,
     * on top of the application's own package, which is always collected.
     *
     * Entries are matched as package prefixes: a class is included when its fully qualified
     * name equals an entry or starts with it followed by a dot. Listing `com.example.network`
     * therefore also covers `com.example.network.http`, `com.example.network.ws`, and so on;
     * use a longer prefix to narrow the set. Only calls that go through `android.util.Log`
     * are collected. Defaults to empty, collecting only the application's own package.
     *
     * ```kotlin
     * measure {
     *   logsAutoCollectPackageNames = listOf("com.example.network")
     * }
     * ```
     */
    var logsAutoCollectPackageNames: List<String> = emptyList()

    internal var filter: Action<VariantFilter> = Action {
        if (it.name.lowercase().contains("debug")) {
            it.enabled = true
        }
    }

    /**
     * Allows configuring the Measure gradle plugin for specific variants.
     */
    fun variantFilter(action: Action<VariantFilter>) {
        this.filter = action
    }
}

interface VariantFilter {
    /**
     * The name of the variant.
     */
    val name: String

    /**
     * Allows enabling or disabling the Measure gradle plugin from uploading mapping files
     * generated by Proguard/R8. Note that disabling this will prevent Measure from de-obfuscating
     * stack traces.
     */
    var enabled: Boolean
}

internal class VariantFilterImpl(override val name: String) : VariantFilter {
    override var enabled: Boolean = true
}
