# fly.toml app configuration file generated for frosty-fog-7165 on 2023-08-14T15:40:51+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frosty-fog-7165"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8181
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
