import type { Root } from "mdast";
import { remark } from "remark";
import remarkGfm from "remark-gfm";
import remarkMdx from "remark-mdx";
import { visit } from "unist-util-visit";

// Fumadocs' processed markdown is GFM plus MDX syntax: component tags
// like <Callout> and {...} expressions. Parsing with the same grammar
// keeps those intact through a parse and re-serialize round trip.
const processor = remark().use(remarkGfm).use(remarkMdx);

/** True for JSX comment expressions (a slash-star block in braces), which render nothing. */
function isJsxComment(node: { type: string; value?: string }): boolean {
  if (node.type !== "mdxFlowExpression" && node.type !== "mdxTextExpression") {
    return false;
  }
  const value = (node.value ?? "").trim();
  return value.startsWith("/*") && value.endsWith("*/");
}

/** Root-relative urls; protocol-relative (`//host`) urls are external. */
function isRootRelative(url: string): boolean {
  return url.startsWith("/") && !url.startsWith("//");
}

/**
 * Rework a docs page's processed markdown so it reads correctly outside
 * the site: root-relative link, image and reference-definition urls
 * become absolute on siteUrl, and JSX comments (such as the "generated by
 * Fumadocs" banner on API reference pages) are dropped. The text is
 * transformed as a syntax tree, so link-like text inside code blocks and
 * inline code is never touched.
 *
 * Throws when the text does not parse as MDX. The llms routes are static,
 * so a page whose processed markdown is invalid fails the build; the fix
 * belongs in the page content (or in fumadocs' serializer), not here.
 * Callers add the page url to the error.
 */
export function toStandaloneMarkdown(
  markdown: string,
  siteUrl: string,
): string {
  const tree = processor.parse(markdown) as Root;

  visit(tree, (node, index, parent) => {
    if (parent && typeof index === "number" && isJsxComment(node)) {
      parent.children.splice(index, 1);
      // Revisit the same index, which now holds the next sibling.
      return index;
    }
    if (
      (node.type === "link" ||
        node.type === "image" ||
        node.type === "definition") &&
      isRootRelative(node.url)
    ) {
      node.url = `${siteUrl}${node.url}`;
    }
  });

  return processor.stringify(tree).trim();
}
