import type { ExceptionSpec, PlatformScenario } from "@/app/sandbox/scenario";
import { SPAN_STEPS, shopSpans, standardFlows } from "@/app/sandbox/journeys";

// The stacktrace strings copy the layout backend/libs/event/frame.go renders,
// including the cut at 55 characters with the full symbol on the next line.
const iosExceptions: ExceptionSpec[] = [
  {
    key: "checkout_nil_unwrap",
    kind: "exception",
    type: "SIGTRAP",
    message: "",
    severity: "fatal",
    handled: false,
    foreground: true,
    framework: "apple",
    exceptions: [
      {
        type: "EXC_BREAKPOINT",
        message: "EXC_ARM_BREAKPOINT, subcode: 4362124464",
        signal: "SIGTRAP",
        thread_name: "Thread 0 Crashed",
        os_build_number: "22C161",
        thread_sequence: 0,
        frames: [
          {
            frame_index: 0,
            binary_name: "libswiftCore.dylib",
            binary_address: "00000001ac4d0000",
            symbol_address: "00000001ac50b1d8",
            offset: 160,
            method_name:
              "closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:)",
            in_app: false,
          },
          {
            frame_index: 1,
            binary_name: "libswiftCore.dylib",
            binary_address: "00000001ac4d0000",
            symbol_address: "00000001ac50b0a4",
            offset: 264,
            method_name: "_assertionFailure(_:_:file:line:flags:)",
            in_app: false,
          },
          {
            frame_index: 2,
            binary_name: "AcmeApp",
            binary_address: "0000000102f34000",
            symbol_address: "0000000102f76eb0",
            offset: 288,
            method_name: "PaymentViewController.placeOrderTapped(_: UIButton)",
            file_name: "PaymentViewController.swift",
            line_num: 142,
            in_app: true,
          },
          {
            frame_index: 3,
            binary_name: "AcmeApp",
            binary_address: "0000000102f34000",
            symbol_address: "0000000102f76f10",
            offset: 56,
            method_name:
              "@objc PaymentViewController.placeOrderTapped(_: UIButton)",
            file_name: "<compiler-generated>",
            in_app: true,
          },
          {
            frame_index: 4,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a276d3a4",
            offset: 100,
            method_name: "-[UIApplication sendAction:to:from:forEvent:]",
            in_app: false,
          },
          {
            frame_index: 5,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a276d318",
            offset: 112,
            method_name: "-[UIControl sendAction:to:forEvent:]",
            in_app: false,
          },
          {
            frame_index: 6,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a276d3fc",
            offset: 324,
            method_name: "-[UIControl _sendActionsForEvents:withEvent:]",
            in_app: false,
          },
          {
            frame_index: 7,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a276cf10",
            offset: 400,
            method_name: "-[UIControl touchesEnded:withEvent:]",
            in_app: false,
          },
          {
            frame_index: 8,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a27532d4",
            offset: 852,
            method_name: "-[UIWindow _sendTouchesForEvent:]",
            in_app: false,
          },
          {
            frame_index: 9,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a2753830",
            offset: 3444,
            method_name: "-[UIWindow sendEvent:]",
            in_app: false,
          },
          {
            frame_index: 10,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a2740098",
            offset: 376,
            method_name: "-[UIApplication sendEvent:]",
            in_app: false,
          },
          {
            frame_index: 11,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a265dbc4",
            offset: 1024,
            method_name: "__dispatchPreprocessedEventFromEventQueue",
            in_app: false,
          },
          {
            frame_index: 12,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a26610b8",
            offset: 4932,
            method_name: "__processEventQueue",
            in_app: false,
          },
          {
            frame_index: 13,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a265e55c",
            offset: 232,
            method_name: "__eventFetcherSourceCallback",
            in_app: false,
          },
          {
            frame_index: 14,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca57b4c",
            offset: 28,
            method_name:
              "__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__",
            in_app: false,
          },
          {
            frame_index: 15,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca57ac4",
            offset: 176,
            method_name: "__CFRunLoopDoSource0",
            in_app: false,
          },
          {
            frame_index: 16,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca56c50",
            offset: 244,
            method_name: "__CFRunLoopDoSources0",
            in_app: false,
          },
          {
            frame_index: 17,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca55e24",
            offset: 840,
            method_name: "__CFRunLoopRun",
            in_app: false,
          },
          {
            frame_index: 18,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca55774",
            offset: 588,
            method_name: "CFRunLoopRunSpecific",
            in_app: false,
          },
          {
            frame_index: 19,
            binary_name: "GraphicsServices",
            binary_address: "0000000241f42000",
            symbol_address: "0000000241f449bc",
            offset: 164,
            method_name: "GSEventRunModal",
            in_app: false,
          },
          {
            frame_index: 20,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a277bc3c",
            offset: 816,
            method_name: "-[UIApplication _run]",
            in_app: false,
          },
          {
            frame_index: 21,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a277be64",
            offset: 340,
            method_name: "UIApplicationMain",
            in_app: false,
          },
          {
            frame_index: 22,
            binary_name: "AcmeApp",
            binary_address: "0000000102f34000",
            symbol_address: "0000000102f7e2c8",
            offset: 92,
            method_name: "static AppDelegate.$main()",
            file_name: "<compiler-generated>",
            in_app: true,
          },
          {
            frame_index: 23,
            binary_name: "AcmeApp",
            binary_address: "0000000102f34000",
            symbol_address: "0000000102f7e310",
            offset: 24,
            method_name: "main",
            file_name: "AppDelegate.swift",
            line_num: 18,
            in_app: true,
          },
          {
            frame_index: 24,
            binary_name: "dyld",
            binary_address: "00000001bd0f4000",
            symbol_address: "00000001bd0f5d1c",
            offset: 2724,
            method_name: "start",
            in_app: false,
          },
        ],
      },
    ],
    threads: [
      {
        name: "com.apple.uikit.eventfetch-thread",
        frames: [
          {
            frame_index: 0,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b55cd4",
            offset: 8,
            method_name: "mach_msg2_trap",
            in_app: false,
          },
          {
            frame_index: 1,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b5630c",
            offset: 76,
            method_name: "mach_msg2_internal",
            in_app: false,
          },
          {
            frame_index: 2,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca57ea4",
            offset: 160,
            method_name: "__CFRunLoopServiceMachPort",
            in_app: false,
          },
          {
            frame_index: 3,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca21f94",
            offset: 1188,
            method_name: "__CFRunLoopRun",
            in_app: false,
          },
          {
            frame_index: 4,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca211d0",
            offset: 532,
            method_name: "CFRunLoopRunSpecific",
            in_app: false,
          },
          {
            frame_index: 5,
            binary_name: "Foundation",
            binary_address: "0000000199ca4000",
            symbol_address: "0000000199ca5cf0",
            offset: 212,
            method_name: "-[NSRunLoop(NSRunLoop) runMode:beforeDate:]",
            in_app: false,
          },
          {
            frame_index: 6,
            binary_name: "Foundation",
            binary_address: "0000000199ca4000",
            symbol_address: "0000000199ca5bd8",
            offset: 64,
            method_name: "-[NSRunLoop(NSRunLoop) runUntilDate:]",
            in_app: false,
          },
          {
            frame_index: 7,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a267aafc",
            offset: 420,
            method_name: "-[UIEventFetcher threadMain]",
            in_app: false,
          },
          {
            frame_index: 8,
            binary_name: "Foundation",
            binary_address: "0000000199ca4000",
            symbol_address: "0000000199d18804",
            offset: 732,
            method_name: "__NSThread__start__",
            in_app: false,
          },
          {
            frame_index: 9,
            binary_name: "libsystem_pthread.dylib",
            binary_address: "00000001fb83b000",
            symbol_address: "00000001fb83c438",
            offset: 136,
            method_name: "_pthread_start",
            in_app: false,
          },
        ],
      },
      {
        name: "com.apple.NSURLSession-work",
        frames: [
          {
            frame_index: 0,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b55cd4",
            offset: 8,
            method_name: "mach_msg2_trap",
            in_app: false,
          },
          {
            frame_index: 1,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b5630c",
            offset: 76,
            method_name: "mach_msg2_internal",
            in_app: false,
          },
          {
            frame_index: 2,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca57ea4",
            offset: 160,
            method_name: "__CFRunLoopServiceMachPort",
            in_app: false,
          },
          {
            frame_index: 3,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca21f94",
            offset: 1188,
            method_name: "__CFRunLoopRun",
            in_app: false,
          },
          {
            frame_index: 4,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca211d0",
            offset: 532,
            method_name: "CFRunLoopRunSpecific",
            in_app: false,
          },
          {
            frame_index: 5,
            binary_name: "CFNetwork",
            binary_address: "00000001a1b18000",
            symbol_address: "00000001a1b453a8",
            offset: 492,
            method_name: "+[__CFN_CoreSchedulingSetRunnable _run:]",
            in_app: false,
          },
          {
            frame_index: 6,
            binary_name: "Foundation",
            binary_address: "0000000199ca4000",
            symbol_address: "0000000199d18804",
            offset: 732,
            method_name: "__NSThread__start__",
            in_app: false,
          },
          {
            frame_index: 7,
            binary_name: "libsystem_pthread.dylib",
            binary_address: "00000001fb83b000",
            symbol_address: "00000001fb83c438",
            offset: 136,
            method_name: "_pthread_start",
            in_app: false,
          },
        ],
      },
      {
        name: "com.acme.shop.image-decode",
        frames: [
          {
            frame_index: 0,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b4ee6c",
            offset: 8,
            method_name: "semaphore_wait_trap",
            in_app: false,
          },
          {
            frame_index: 1,
            binary_name: "libdispatch.dylib",
            binary_address: "000000019be30000",
            symbol_address: "000000019be4be84",
            offset: 148,
            method_name: "_dispatch_sema4_wait",
            in_app: false,
          },
          {
            frame_index: 2,
            binary_name: "libdispatch.dylib",
            binary_address: "000000019be30000",
            symbol_address: "000000019be561e4",
            offset: 16,
            method_name: "_dispatch_semaphore_wait_slow",
            in_app: false,
          },
          {
            frame_index: 3,
            binary_name: "libdispatch.dylib",
            binary_address: "000000019be30000",
            symbol_address: "000000019be41148",
            offset: 596,
            method_name: "_dispatch_lane_barrier_sync_invoke_and_complete",
            in_app: false,
          },
          {
            frame_index: 4,
            binary_name: "libdispatch.dylib",
            binary_address: "000000019be30000",
            symbol_address: "000000019be4e900",
            offset: 360,
            method_name: "_dispatch_worker_thread2",
            in_app: false,
          },
          {
            frame_index: 5,
            binary_name: "libsystem_pthread.dylib",
            binary_address: "00000001fb83b000",
            symbol_address: "00000001fb83c374",
            offset: 232,
            method_name: "_pthread_wqthread",
            in_app: false,
          },
          {
            frame_index: 6,
            binary_name: "libsystem_pthread.dylib",
            binary_address: "00000001fb83b000",
            symbol_address: "00000001fb83c390",
            offset: 8,
            method_name: "start_wqthread",
            in_app: false,
          },
        ],
      },
      {
        name: "com.apple.CoreMotion.MotionThread",
        frames: [
          {
            frame_index: 0,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b55cd4",
            offset: 8,
            method_name: "mach_msg2_trap",
            in_app: false,
          },
          {
            frame_index: 1,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b5630c",
            offset: 76,
            method_name: "mach_msg2_internal",
            in_app: false,
          },
          {
            frame_index: 2,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca57ea4",
            offset: 160,
            method_name: "__CFRunLoopServiceMachPort",
            in_app: false,
          },
          {
            frame_index: 3,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca21f94",
            offset: 1188,
            method_name: "__CFRunLoopRun",
            in_app: false,
          },
          {
            frame_index: 4,
            binary_name: "libsystem_pthread.dylib",
            binary_address: "00000001fb83b000",
            symbol_address: "00000001fb83c438",
            offset: 136,
            method_name: "_pthread_start",
            in_app: false,
          },
        ],
      },
      {
        name: "Thread 7",
        frames: [
          {
            frame_index: 0,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b4d390",
            offset: 8,
            method_name: "__workq_kernreturn",
            in_app: false,
          },
          {
            frame_index: 1,
            binary_name: "libsystem_pthread.dylib",
            binary_address: "00000001fb83b000",
            symbol_address: "00000001fb83e3fc",
            offset: 368,
            method_name: "_pthread_wqthread",
            in_app: false,
          },
        ],
      },
      {
        name: "Thread 8",
        frames: [
          {
            frame_index: 0,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b4d390",
            offset: 8,
            method_name: "__workq_kernreturn",
            in_app: false,
          },
          {
            frame_index: 1,
            binary_name: "libsystem_pthread.dylib",
            binary_address: "00000001fb83b000",
            symbol_address: "00000001fb83e3fc",
            offset: 368,
            method_name: "_pthread_wqthread",
            in_app: false,
          },
        ],
      },
    ],
    binary_images: [
      {
        name: "AcmeApp",
        arch: "arm64e",
        uuid: "8f2c1a6e3b4d4e1a9c2f1a2b3c4d5e6f",
        path: "/private/var/containers/Bundle/Application/1A2B3C4D-5E6F-7A8B-9C0D-1E2F3A4B5C6D/AcmeApp.app/AcmeApp",
      },
      {
        name: "CFNetwork",
        arch: "arm64e",
        uuid: "4a0921b76bd83dd0a7b017d82dbbc75a",
        path: "/System/Library/Frameworks/CFNetwork.framework/CFNetwork",
      },
      {
        name: "CoreFoundation",
        arch: "arm64e",
        uuid: "6fc1e77958463275bf66955738404cf6",
        path: "/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation",
      },
      {
        name: "Foundation",
        arch: "arm64e",
        uuid: "cf6b28c49795362ab5637b1b8c116282",
        path: "/System/Library/Frameworks/Foundation.framework/Foundation",
      },
      {
        name: "GraphicsServices",
        arch: "arm64e",
        uuid: "67164c20442f320b924e83c661869ab7",
        path: "/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices",
      },
      {
        name: "UIKitCore",
        arch: "arm64e",
        uuid: "e83e034727d734bdb0d351666dfdfd76",
        path: "/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore",
      },
      {
        name: "dyld",
        arch: "arm64e",
        uuid: "6c9a1e278d533f41b2a60e7c4d91b2f5",
        path: "/usr/lib/dyld",
      },
      {
        name: "libdispatch.dylib",
        arch: "arm64e",
        uuid: "ef0492a68ca538f097bbdf9bdb54c17a",
        path: "/usr/lib/system/libdispatch.dylib",
      },
      {
        name: "libswiftCore.dylib",
        arch: "arm64e",
        uuid: "9d1a2c6f4b833e5d8a102f6c4d8b7e91",
        path: "/usr/lib/swift/libswiftCore.dylib",
      },
      {
        name: "libsystem_kernel.dylib",
        arch: "arm64e",
        uuid: "5ea2a24297863af8b8a97899ecc711c8",
        path: "/usr/lib/system/libsystem_kernel.dylib",
      },
      {
        name: "libsystem_pthread.dylib",
        arch: "arm64e",
        uuid: "5337239180ee3a5285d2b0d39816a60b",
        path: "/usr/lib/system/libsystem_pthread.dylib",
      },
    ],
    file_name: "PaymentViewController.swift",
    method_name: "PaymentViewController.placeOrderTapped(_: UIButton)",
    line_number: 142,
    stacktrace: `Thread 0 Crashed:
  0   libswiftCore.dylib            0x00000001ac4d0000   closure #1 in closure #1 in closure #1 in _assertion... + 160
    Full symbol:closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:)
  1   libswiftCore.dylib            0x00000001ac4d0000   _assertionFailure(_:_:file:line:flags:) + 264
  2   AcmeApp                       0x0000000102f34000   PaymentViewController.placeOrderTapped(_: UIButton)   (PaymentViewController.swift:142)
  3   AcmeApp                       0x0000000102f34000   @objc PaymentViewController.placeOrderTapped(_: UIBu...   (<compiler-generated>)
    Full symbol:@objc PaymentViewController.placeOrderTapped(_: UIButton)
  4   UIKitCore                     0x00000001a25c4000   -[UIApplication sendAction:to:from:forEvent:] + 100
  5   UIKitCore                     0x00000001a25c4000   -[UIControl sendAction:to:forEvent:] + 112
  6   UIKitCore                     0x00000001a25c4000   -[UIControl _sendActionsForEvents:withEvent:] + 324
  7   UIKitCore                     0x00000001a25c4000   -[UIControl touchesEnded:withEvent:] + 400
  8   UIKitCore                     0x00000001a25c4000   -[UIWindow _sendTouchesForEvent:] + 852
  9   UIKitCore                     0x00000001a25c4000   -[UIWindow sendEvent:] + 3444
 10   UIKitCore                     0x00000001a25c4000   -[UIApplication sendEvent:] + 376
 11   UIKitCore                     0x00000001a25c4000   __dispatchPreprocessedEventFromEventQueue + 1024
 12   UIKitCore                     0x00000001a25c4000   __processEventQueue + 4932
 13   UIKitCore                     0x00000001a25c4000   __eventFetcherSourceCallback + 232
 14   CoreFoundation                0x000000019c9f3000   __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNC... + 28
    Full symbol:__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
 15   CoreFoundation                0x000000019c9f3000   __CFRunLoopDoSource0 + 176
 16   CoreFoundation                0x000000019c9f3000   __CFRunLoopDoSources0 + 244
 17   CoreFoundation                0x000000019c9f3000   __CFRunLoopRun + 840
 18   CoreFoundation                0x000000019c9f3000   CFRunLoopRunSpecific + 588
 19   GraphicsServices              0x0000000241f42000   GSEventRunModal + 164
 20   UIKitCore                     0x00000001a25c4000   -[UIApplication _run] + 816
 21   UIKitCore                     0x00000001a25c4000   UIApplicationMain + 340
 22   AcmeApp                       0x0000000102f34000   static AppDelegate.$main()   (<compiler-generated>)
 23   AcmeApp                       0x0000000102f34000   main   (AppDelegate.swift:18)
 24   dyld                          0x00000001bd0f4000   start + 2724

`,
  },
  {
    key: "product_image_bad_access",
    kind: "exception",
    type: "SIGSEGV",
    message: "",
    severity: "fatal",
    handled: false,
    foreground: true,
    framework: "apple",
    exceptions: [
      {
        type: "EXC_BAD_ACCESS",
        message: "KERN_INVALID_ADDRESS at 0x0000000000000010",
        signal: "SIGSEGV",
        thread_name: "com.acme.shop.image-decode",
        os_build_number: "22C161",
        thread_sequence: 6,
        frames: [
          {
            frame_index: 0,
            binary_name: "libsystem_platform.dylib",
            binary_address: "00000001f0a24000",
            symbol_address: "00000001f0a241d4",
            offset: 244,
            method_name: "_platform_memmove",
            in_app: false,
          },
          {
            frame_index: 1,
            binary_name: "ImageIO",
            binary_address: "00000001a5c30000",
            symbol_address: "00000001a5c8b84c",
            offset: 296,
            method_name:
              "IIOImageSource::makeImagePlus(unsigned long, IIODictionary*)",
            in_app: false,
          },
          {
            frame_index: 2,
            binary_name: "ImageIO",
            binary_address: "00000001a5c30000",
            symbol_address: "00000001a5c8a3b0",
            offset: 168,
            method_name: "CGImageSourceCreateImageAtIndex",
            in_app: false,
          },
          {
            frame_index: 3,
            binary_name: "CoreGraphics",
            binary_address: "00000001a0344000",
            symbol_address: "00000001a03731c4",
            offset: 60,
            method_name: "CGImageGetDataProvider",
            in_app: false,
          },
          {
            frame_index: 4,
            binary_name: "AcmeApp",
            binary_address: "0000000102f34000",
            symbol_address: "0000000102f8032c",
            offset: 204,
            method_name:
              "ProductDetailViewController.decodeThumbnail(from: Data)",
            file_name: "ProductDetailViewController.swift",
            line_num: 96,
            in_app: true,
          },
          {
            frame_index: 5,
            binary_name: "AcmeApp",
            binary_address: "0000000102f34000",
            symbol_address: "0000000102f801a8",
            offset: 128,
            method_name:
              "closure #1 in ProductDetailViewController.loadThumbnails()",
            file_name: "ProductDetailViewController.swift",
            line_num: 71,
            in_app: true,
          },
          {
            frame_index: 6,
            binary_name: "AcmeApp",
            binary_address: "0000000102f34000",
            symbol_address: "0000000102f800f0",
            offset: 44,
            method_name: "thunk for @escaping @callee_guaranteed () -> ()",
            file_name: "<compiler-generated>",
            in_app: true,
          },
          {
            frame_index: 7,
            binary_name: "libdispatch.dylib",
            binary_address: "000000019be30000",
            symbol_address: "000000019be4be84",
            offset: 32,
            method_name: "_dispatch_call_block_and_release",
            in_app: false,
          },
          {
            frame_index: 8,
            binary_name: "libdispatch.dylib",
            binary_address: "000000019be30000",
            symbol_address: "000000019be561e4",
            offset: 20,
            method_name: "_dispatch_client_callout",
            in_app: false,
          },
          {
            frame_index: 9,
            binary_name: "libdispatch.dylib",
            binary_address: "000000019be30000",
            symbol_address: "000000019be41148",
            offset: 748,
            method_name: "_dispatch_lane_serial_drain",
            in_app: false,
          },
          {
            frame_index: 10,
            binary_name: "libdispatch.dylib",
            binary_address: "000000019be30000",
            symbol_address: "000000019be4087c",
            offset: 432,
            method_name: "_dispatch_lane_invoke",
            in_app: false,
          },
          {
            frame_index: 11,
            binary_name: "libdispatch.dylib",
            binary_address: "000000019be30000",
            symbol_address: "000000019be4e900",
            offset: 288,
            method_name: "_dispatch_root_queue_drain_deferred_wlh",
            in_app: false,
          },
          {
            frame_index: 12,
            binary_name: "libdispatch.dylib",
            binary_address: "000000019be30000",
            symbol_address: "000000019be4f098",
            offset: 404,
            method_name: "_dispatch_workloop_worker_thread",
            in_app: false,
          },
          {
            frame_index: 13,
            binary_name: "libsystem_pthread.dylib",
            binary_address: "00000001fb83b000",
            symbol_address: "00000001fb83c374",
            offset: 288,
            method_name: "_pthread_wqthread",
            in_app: false,
          },
          {
            frame_index: 14,
            binary_name: "libsystem_pthread.dylib",
            binary_address: "00000001fb83b000",
            symbol_address: "00000001fb83c390",
            offset: 8,
            method_name: "start_wqthread",
            in_app: false,
          },
        ],
      },
    ],
    threads: [
      {
        name: "com.apple.main-thread",
        frames: [
          {
            frame_index: 0,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b55cd4",
            offset: 8,
            method_name: "mach_msg2_trap",
            in_app: false,
          },
          {
            frame_index: 1,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b5630c",
            offset: 76,
            method_name: "mach_msg2_internal",
            in_app: false,
          },
          {
            frame_index: 2,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca57ea4",
            offset: 160,
            method_name: "__CFRunLoopServiceMachPort",
            in_app: false,
          },
          {
            frame_index: 3,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca21f94",
            offset: 1188,
            method_name: "__CFRunLoopRun",
            in_app: false,
          },
          {
            frame_index: 4,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca211d0",
            offset: 532,
            method_name: "CFRunLoopRunSpecific",
            in_app: false,
          },
          {
            frame_index: 5,
            binary_name: "GraphicsServices",
            binary_address: "0000000241f42000",
            symbol_address: "0000000241f449bc",
            offset: 164,
            method_name: "GSEventRunModal",
            in_app: false,
          },
          {
            frame_index: 6,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a277bc3c",
            offset: 816,
            method_name: "-[UIApplication _run]",
            in_app: false,
          },
          {
            frame_index: 7,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a277be64",
            offset: 340,
            method_name: "UIApplicationMain",
            in_app: false,
          },
          {
            frame_index: 8,
            binary_name: "AcmeApp",
            binary_address: "0000000102f34000",
            symbol_address: "0000000102f7e2c8",
            offset: 92,
            method_name: "static AppDelegate.$main()",
            in_app: true,
          },
          {
            frame_index: 9,
            binary_name: "AcmeApp",
            binary_address: "0000000102f34000",
            symbol_address: "0000000102f7e310",
            offset: 24,
            method_name: "main",
            in_app: true,
          },
          {
            frame_index: 10,
            binary_name: "dyld",
            binary_address: "00000001bd0f4000",
            symbol_address: "00000001bd0f5d1c",
            offset: 2724,
            method_name: "start",
            in_app: false,
          },
        ],
      },
      {
        name: "com.apple.uikit.eventfetch-thread",
        frames: [
          {
            frame_index: 0,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b55cd4",
            offset: 8,
            method_name: "mach_msg2_trap",
            in_app: false,
          },
          {
            frame_index: 1,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b5630c",
            offset: 76,
            method_name: "mach_msg2_internal",
            in_app: false,
          },
          {
            frame_index: 2,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca57ea4",
            offset: 160,
            method_name: "__CFRunLoopServiceMachPort",
            in_app: false,
          },
          {
            frame_index: 3,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca21f94",
            offset: 1188,
            method_name: "__CFRunLoopRun",
            in_app: false,
          },
          {
            frame_index: 4,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca211d0",
            offset: 532,
            method_name: "CFRunLoopRunSpecific",
            in_app: false,
          },
          {
            frame_index: 5,
            binary_name: "Foundation",
            binary_address: "0000000199ca4000",
            symbol_address: "0000000199ca5cf0",
            offset: 212,
            method_name: "-[NSRunLoop(NSRunLoop) runMode:beforeDate:]",
            in_app: false,
          },
          {
            frame_index: 6,
            binary_name: "Foundation",
            binary_address: "0000000199ca4000",
            symbol_address: "0000000199ca5bd8",
            offset: 64,
            method_name: "-[NSRunLoop(NSRunLoop) runUntilDate:]",
            in_app: false,
          },
          {
            frame_index: 7,
            binary_name: "UIKitCore",
            binary_address: "00000001a25c4000",
            symbol_address: "00000001a267aafc",
            offset: 420,
            method_name: "-[UIEventFetcher threadMain]",
            in_app: false,
          },
          {
            frame_index: 8,
            binary_name: "Foundation",
            binary_address: "0000000199ca4000",
            symbol_address: "0000000199d18804",
            offset: 732,
            method_name: "__NSThread__start__",
            in_app: false,
          },
          {
            frame_index: 9,
            binary_name: "libsystem_pthread.dylib",
            binary_address: "00000001fb83b000",
            symbol_address: "00000001fb83c438",
            offset: 136,
            method_name: "_pthread_start",
            in_app: false,
          },
        ],
      },
      {
        name: "com.apple.NSURLSession-work",
        frames: [
          {
            frame_index: 0,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b55cd4",
            offset: 8,
            method_name: "mach_msg2_trap",
            in_app: false,
          },
          {
            frame_index: 1,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b5630c",
            offset: 76,
            method_name: "mach_msg2_internal",
            in_app: false,
          },
          {
            frame_index: 2,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca57ea4",
            offset: 160,
            method_name: "__CFRunLoopServiceMachPort",
            in_app: false,
          },
          {
            frame_index: 3,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca21f94",
            offset: 1188,
            method_name: "__CFRunLoopRun",
            in_app: false,
          },
          {
            frame_index: 4,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca211d0",
            offset: 532,
            method_name: "CFRunLoopRunSpecific",
            in_app: false,
          },
          {
            frame_index: 5,
            binary_name: "CFNetwork",
            binary_address: "00000001a1b18000",
            symbol_address: "00000001a1b453a8",
            offset: 492,
            method_name: "+[__CFN_CoreSchedulingSetRunnable _run:]",
            in_app: false,
          },
          {
            frame_index: 6,
            binary_name: "Foundation",
            binary_address: "0000000199ca4000",
            symbol_address: "0000000199d18804",
            offset: 732,
            method_name: "__NSThread__start__",
            in_app: false,
          },
          {
            frame_index: 7,
            binary_name: "libsystem_pthread.dylib",
            binary_address: "00000001fb83b000",
            symbol_address: "00000001fb83c438",
            offset: 136,
            method_name: "_pthread_start",
            in_app: false,
          },
        ],
      },
      {
        name: "com.apple.CoreMotion.MotionThread",
        frames: [
          {
            frame_index: 0,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b55cd4",
            offset: 8,
            method_name: "mach_msg2_trap",
            in_app: false,
          },
          {
            frame_index: 1,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b5630c",
            offset: 76,
            method_name: "mach_msg2_internal",
            in_app: false,
          },
          {
            frame_index: 2,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca57ea4",
            offset: 160,
            method_name: "__CFRunLoopServiceMachPort",
            in_app: false,
          },
          {
            frame_index: 3,
            binary_name: "CoreFoundation",
            binary_address: "000000019c9f3000",
            symbol_address: "000000019ca21f94",
            offset: 1188,
            method_name: "__CFRunLoopRun",
            in_app: false,
          },
          {
            frame_index: 4,
            binary_name: "libsystem_pthread.dylib",
            binary_address: "00000001fb83b000",
            symbol_address: "00000001fb83c438",
            offset: 136,
            method_name: "_pthread_start",
            in_app: false,
          },
        ],
      },
      {
        name: "Thread 9",
        frames: [
          {
            frame_index: 0,
            binary_name: "libsystem_kernel.dylib",
            binary_address: "00000001e6b4c000",
            symbol_address: "00000001e6b4d390",
            offset: 8,
            method_name: "__workq_kernreturn",
            in_app: false,
          },
          {
            frame_index: 1,
            binary_name: "libsystem_pthread.dylib",
            binary_address: "00000001fb83b000",
            symbol_address: "00000001fb83e3fc",
            offset: 368,
            method_name: "_pthread_wqthread",
            in_app: false,
          },
        ],
      },
    ],
    binary_images: [
      {
        name: "AcmeApp",
        arch: "arm64e",
        uuid: "8f2c1a6e3b4d4e1a9c2f1a2b3c4d5e6f",
        path: "/private/var/containers/Bundle/Application/1A2B3C4D-5E6F-7A8B-9C0D-1E2F3A4B5C6D/AcmeApp.app/AcmeApp",
      },
      {
        name: "CFNetwork",
        arch: "arm64e",
        uuid: "4a0921b76bd83dd0a7b017d82dbbc75a",
        path: "/System/Library/Frameworks/CFNetwork.framework/CFNetwork",
      },
      {
        name: "CoreFoundation",
        arch: "arm64e",
        uuid: "6fc1e77958463275bf66955738404cf6",
        path: "/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation",
      },
      {
        name: "CoreGraphics",
        arch: "arm64e",
        uuid: "7b2c9d415e383a6f9b124d8e0a7c6f53",
        path: "/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics",
      },
      {
        name: "Foundation",
        arch: "arm64e",
        uuid: "cf6b28c49795362ab5637b1b8c116282",
        path: "/System/Library/Frameworks/Foundation.framework/Foundation",
      },
      {
        name: "GraphicsServices",
        arch: "arm64e",
        uuid: "67164c20442f320b924e83c661869ab7",
        path: "/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices",
      },
      {
        name: "ImageIO",
        arch: "arm64e",
        uuid: "2e7d4c139a6b3f288d451c0b7e6a9d32",
        path: "/System/Library/Frameworks/ImageIO.framework/ImageIO",
      },
      {
        name: "UIKitCore",
        arch: "arm64e",
        uuid: "e83e034727d734bdb0d351666dfdfd76",
        path: "/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore",
      },
      {
        name: "dyld",
        arch: "arm64e",
        uuid: "6c9a1e278d533f41b2a60e7c4d91b2f5",
        path: "/usr/lib/dyld",
      },
      {
        name: "libdispatch.dylib",
        arch: "arm64e",
        uuid: "ef0492a68ca538f097bbdf9bdb54c17a",
        path: "/usr/lib/system/libdispatch.dylib",
      },
      {
        name: "libsystem_kernel.dylib",
        arch: "arm64e",
        uuid: "5ea2a24297863af8b8a97899ecc711c8",
        path: "/usr/lib/system/libsystem_kernel.dylib",
      },
      {
        name: "libsystem_platform.dylib",
        arch: "arm64e",
        uuid: "1b0c2e7c4f213a1b9c776e6b2d9f3a42",
        path: "/usr/lib/system/libsystem_platform.dylib",
      },
      {
        name: "libsystem_pthread.dylib",
        arch: "arm64e",
        uuid: "5337239180ee3a5285d2b0d39816a60b",
        path: "/usr/lib/system/libsystem_pthread.dylib",
      },
    ],
    file_name: "ProductDetailViewController.swift",
    method_name: "ProductDetailViewController.decodeThumbnail(from: Data)",
    line_number: 96,
    stacktrace: `com.acme.shop.image-decode:
  0   libsystem_platform.dylib      0x00000001f0a24000   _platform_memmove + 244
  1   ImageIO                       0x00000001a5c30000   IIOImageSource::makeImagePlus(unsigned long, IIODict... + 296
    Full symbol:IIOImageSource::makeImagePlus(unsigned long, IIODictionary*)
  2   ImageIO                       0x00000001a5c30000   CGImageSourceCreateImageAtIndex + 168
  3   CoreGraphics                  0x00000001a0344000   CGImageGetDataProvider + 60
  4   AcmeApp                       0x0000000102f34000   ProductDetailViewController.decodeThumbnail(from: Data)   (ProductDetailViewController.swift:96)
  5   AcmeApp                       0x0000000102f34000   closure #1 in ProductDetailViewController.loadThumbn...   (ProductDetailViewController.swift:71)
    Full symbol:closure #1 in ProductDetailViewController.loadThumbnails()
  6   AcmeApp                       0x0000000102f34000   thunk for @escaping @callee_guaranteed () -> ()   (<compiler-generated>)
  7   libdispatch.dylib             0x000000019be30000   _dispatch_call_block_and_release + 32
  8   libdispatch.dylib             0x000000019be30000   _dispatch_client_callout + 20
  9   libdispatch.dylib             0x000000019be30000   _dispatch_lane_serial_drain + 748
 10   libdispatch.dylib             0x000000019be30000   _dispatch_lane_invoke + 432
 11   libdispatch.dylib             0x000000019be30000   _dispatch_root_queue_drain_deferred_wlh + 288
 12   libdispatch.dylib             0x000000019be30000   _dispatch_workloop_worker_thread + 404
 13   libsystem_pthread.dylib       0x00000001fb83b000   _pthread_wqthread + 288
 14   libsystem_pthread.dylib       0x00000001fb83b000   start_wqthread + 8

`,
  },
  // The app tracks the NSError from the request's completion handler without
  // a stack, so the backend names the group by its domain.
  {
    key: "cart_request_timeout",
    kind: "exception",
    type: "NSURLErrorDomain",
    message: "",
    severity: "handled",
    handled: true,
    foreground: true,
    framework: "apple",
    error: {
      code: "NSURLErrorDomain",
      num_code: -1001,
      meta: {
        NSLocalizedDescription: "The request timed out.",
        NSErrorFailingURLStringKey: "https://api.acme.shop/v1/cart",
        _kCFStreamErrorDomainKey: "4",
      },
    },
    exceptions: [],
    threads: [],
    file_name: "",
    method_name: "",
    line_number: 0,
    stacktrace: "",
    reportedOn: "com.apple.NSURLSession-delegate",
  },
];

export const iosNativeScenario: PlatformScenario = {
  ids: { product: "numbered", orderPrefix: "o_" },
  app: {
    id: "d4f2a6b8-3c91-4e5a-9b7f-8a1c2d3e4f5b",
    name: "Acme - Native iOS",
    os: "ios",
    framework: "native",
    uniqueId: "sh.acme.AcmeApp",
    sdkVersion: "0.13.2",
    versions: [
      { name: "3.2.1", code: "412", releasedDaysAgo: 12 },
      { name: "3.2.0", code: "405", releasedDaysAgo: 33 },
      { name: "3.1.4", code: "398", releasedDaysAgo: 220 },
    ],
    candidate: { name: "3.2.2", code: "418" },
    mappingTypes: ["dsym"],
    createdDaysAgo: 214,
    dailySessions: 310_000,
    crashFreeRate: 0.99483,
    perceivedCrashFreeRate: 0.99817,
  },
  ui: {
    style: "ios",
    screens: {
      home: "home",
      productList: "products",
      productDetail: "product_detail",
      cart: "cart",
      checkout: "checkout",
      payment: "payment",
      orderConfirmation: "order_confirmation",
      orders: "orders",
      search: "search",
      login: "login",
      profile: "profile",
    },
  },
  screens: [
    {
      key: "home",
      label: "Home",
      className: "HomeViewController",
      lifecycle: "view_controller",
    },
    {
      key: "productList",
      label: "Product List",
      className: "ProductListViewController",
      lifecycle: "view_controller",
    },
    {
      key: "productDetail",
      label: "Product Detail",
      className: "ProductDetailViewController",
      lifecycle: "view_controller",
    },
    {
      key: "cart",
      label: "Cart",
      className: "CartViewController",
      lifecycle: "view_controller",
    },
    {
      key: "checkout",
      label: "Checkout",
      className: "CheckoutViewController",
      lifecycle: "view_controller",
    },
    {
      key: "payment",
      label: "Payment",
      className: "PaymentViewController",
      lifecycle: "view_controller",
    },
    {
      key: "orderConfirmation",
      label: "Order Confirmation",
      className: "OrderConfirmationViewController",
      lifecycle: "view_controller",
    },
    {
      key: "orders",
      label: "Orders",
      className: "OrderHistoryViewController",
      lifecycle: "view_controller",
    },
    {
      key: "search",
      label: "Search",
      className: "SearchViewController",
      lifecycle: "view_controller",
    },
    {
      key: "login",
      label: "Login",
      className: "LoginViewController",
      lifecycle: "view_controller",
    },
    {
      key: "profile",
      label: "Profile",
      className: "ProfileView",
      lifecycle: "swift_ui",
    },
  ],
  devices: [
    {
      device_name: "iPhone",
      device_model: "iPhone 15 Pro",
      device_manufacturer: "Apple",
      device_type: "phone",
      os_version: "26.2",
      device_width_px: 1179,
      device_height_px: 2556,
      device_density_dpi: 480,
      device_density: 3.0,
      device_cpu_arch: "arm64e",
      device_is_foldable: false,
      device_low_power_mode: false,
      device_thermal_throttling_enabled: false,
      os_page_size: 0,
      network_type: "wifi",
      network_generation: "5g",
      network_provider: "AT&T",
    },
    {
      device_name: "iPhone",
      device_model: "iPhone 14",
      device_manufacturer: "Apple",
      device_type: "phone",
      os_version: "26.1",
      device_width_px: 1170,
      device_height_px: 2532,
      device_density_dpi: 480,
      device_density: 3.0,
      device_cpu_arch: "arm64e",
      device_is_foldable: false,
      device_low_power_mode: true,
      device_thermal_throttling_enabled: false,
      os_page_size: 0,
      network_type: "cellular",
      network_generation: "5g",
      network_provider: "Verizon",
    },
    {
      device_name: "iPhone",
      device_model: "iPhone SE (3rd generation)",
      device_manufacturer: "Apple",
      device_type: "phone",
      os_version: "18.6.2",
      device_width_px: 750,
      device_height_px: 1334,
      device_density_dpi: 320,
      device_density: 2.0,
      device_cpu_arch: "arm64e",
      device_is_foldable: false,
      device_low_power_mode: false,
      device_thermal_throttling_enabled: false,
      os_page_size: 0,
      network_type: "cellular",
      network_generation: "4g",
      network_provider: "T-Mobile",
    },
    {
      device_name: "iPad",
      device_model: "iPad Air (5th generation)",
      device_manufacturer: "Apple",
      device_type: "tablet",
      os_version: "26.2",
      device_width_px: 1640,
      device_height_px: 2360,
      device_density_dpi: 320,
      device_density: 2.0,
      device_cpu_arch: "arm64e",
      device_is_foldable: false,
      device_low_power_mode: false,
      device_thermal_throttling_enabled: false,
      os_page_size: 0,
      network_type: "wifi",
      network_generation: "unknown",
      network_provider: "unknown",
    },
  ],
  users: [
    { person: 6, device: 0, locale: "es_US" },
    { person: 7, device: 1, locale: "en_US" },
    { person: 8, device: 2, locale: "en_US" },
    { person: 9, device: 3, locale: "en_US" },
    { person: 10, device: 1, locale: "en_US" },
  ],
  http: [
    {
      key: "products_list",
      url: "https://api.acme.shop/v1/catalog/products",
      method: "get",
      client: "URLSession",
      statusCodes: [
        { code: 200, weight: 0.96 },
        { code: 500, weight: 0.04 },
      ],
      latencyMs: [120, 420],
      responseBody: '{"products":{catalog}}',
    },
    {
      key: "product_detail",
      url: "https://api.acme.shop/v1/catalog/products/{product_id}",
      method: "get",
      client: "URLSession",
      statusCodes: [
        { code: 200, weight: 0.97 },
        { code: 404, weight: 0.03 },
      ],
      latencyMs: [100, 300],
      responseBody:
        '{"id":"{product_id}","name":"{product_name}","price_cents":{price_cents},"in_stock":true}',
    },
    {
      key: "product_reviews",
      url: "https://api.acme.shop/v1/catalog/products/{product_id}/reviews",
      method: "get",
      client: "URLSession",
      statusCodes: [{ code: 200, weight: 1 }],
      latencyMs: [90, 280],
    },
    {
      key: "product_image",
      url: "https://cdn.acme.shop/images/{product_id}/hero.heic",
      method: "get",
      client: "URLSession",
      statusCodes: [{ code: 200, weight: 1 }],
      latencyMs: [150, 700],
    },
    {
      key: "add_to_cart",
      url: "https://api.acme.shop/v1/cart/items",
      method: "post",
      client: "URLSession",
      statusCodes: [
        { code: 201, weight: 0.95 },
        { code: 422, weight: 0.05 },
      ],
      latencyMs: [150, 400],
      requestBody:
        '{"product_id":"{product_id}","option":"{option}","quantity":{quantity}}',
      responseBody: '{"cart_id":"{cart_id}","item_count":{item_count}}',
      effect: "cart_add",
    },
    {
      key: "update_cart_item",
      url: "https://api.acme.shop/v1/cart/items/{product_id}",
      method: "patch",
      client: "URLSession",
      statusCodes: [{ code: 200, weight: 1 }],
      latencyMs: [120, 320],
      requestBody: '{"quantity":{quantity}}',
      responseBody: '{"cart_id":"{cart_id}","item_count":{item_count}}',
      effect: "cart_update",
    },
    {
      key: "remove_cart_item",
      url: "https://api.acme.shop/v1/cart/items/{product_id}",
      method: "delete",
      client: "URLSession",
      statusCodes: [{ code: 200, weight: 1 }],
      latencyMs: [120, 320],
      responseBody: '{"cart_id":"{cart_id}","item_count":{item_count}}',
      effect: "cart_remove",
    },
    {
      key: "get_cart",
      url: "https://api.acme.shop/v1/cart",
      method: "get",
      client: "URLSession",
      statusCodes: [
        { code: 200, weight: 0.9 },
        { code: 500, weight: 0.02 },
      ],
      latencyMs: [100, 260],
      failure: {
        reason: "NSURLErrorTimedOut",
        description: "The request timed out.",
        weight: 0.08,
        durationMs: [30_000, 30_020],
      },
      responseBody: '{"cart_id":"{cart_id}","items":{cart_items}}',
    },
    {
      key: "apply_promo",
      url: "https://api.acme.shop/v1/cart/promo",
      method: "post",
      client: "URLSession",
      statusCodes: [{ code: 200, weight: 1 }],
      latencyMs: [120, 320],
      requestBody: '{"code":"{coupon}"}',
      responseBody: '{"code":"{coupon}","discount":{discount},"total":{total}}',
      effect: "coupon",
    },
    {
      key: "place_order",
      url: "https://api.acme.shop/v1/checkout/orders",
      method: "post",
      client: "URLSession",
      statusCodes: [
        { code: 201, weight: 0.92 },
        { code: 402, weight: 0.05 },
        { code: 500, weight: 0.03 },
      ],
      latencyMs: [300, 900],
      requestBody: '{"cart_id":"{cart_id}","shipping":"{shipping_method}"}',
      responseBody:
        '{"order_id":"{order_id}","number":"{order_number}","status":"pending_payment","total_cents":{total_cents}}',
      effect: "order",
    },
    {
      key: "charge_payment",
      url: "https://api.acme.shop/v1/payments/charge",
      method: "post",
      client: "URLSession",
      statusCodes: [
        { code: 200, weight: 0.9 },
        { code: 402, weight: 0.08 },
        { code: 500, weight: 0.02 },
      ],
      latencyMs: [400, 1200],
      requestBody:
        '{"order_id":"{order_id}","method":"{payment_method}","amount_cents":{total_cents}}',
      responseBody: '{"order_id":"{order_id}","status":"paid"}',
    },
    {
      key: "search_products",
      url: "https://api.acme.shop/v1/search?q={query_param}",
      method: "get",
      client: "URLSession",
      statusCodes: [
        { code: 200, weight: 0.98 },
        { code: 500, weight: 0.02 },
      ],
      latencyMs: [90, 260],
      responseBody: '{"query":"{query}","results":{results}}',
      effect: "search",
    },
    {
      key: "login",
      url: "https://api.acme.shop/v1/auth/login",
      method: "post",
      client: "URLSession",
      statusCodes: [
        { code: 200, weight: 0.94 },
        { code: 401, weight: 0.06 },
      ],
      latencyMs: [200, 500],
      requestBody: '{"email":"{email}","password":"[redacted]"}',
      responseBody: '{"user_id":"{user_id}","token":"[redacted]"}',
    },
    {
      key: "get_profile",
      url: "https://api.acme.shop/v1/user/profile",
      method: "get",
      client: "URLSession",
      statusCodes: [{ code: 200, weight: 1.0 }],
      latencyMs: [80, 220],
      responseBody:
        '{"user_id":"{user_id}","name":"{user_name}","email":"{email}","orders_count":4}',
    },
    {
      key: "get_orders",
      url: "https://api.acme.shop/v1/orders",
      method: "get",
      client: "URLSession",
      statusCodes: [{ code: 200, weight: 1.0 }],
      latencyMs: [90, 260],
    },
    {
      key: "update_preferences",
      url: "https://api.acme.shop/v1/user/preferences",
      method: "patch",
      client: "URLSession",
      statusCodes: [{ code: 200, weight: 1.0 }],
      latencyMs: [80, 220],
      requestBody: '{"promotions":true}',
    },
  ],
  exceptions: iosExceptions,

  spans: shopSpans({
    worker: "com.apple.root.default-qos",
    network: "com.apple.NSURLSession-work",
    decode: "com.acme.shop.image-decode",
    requests: {
      detail: "product_detail",
      reviews: "product_reviews",
      image: "product_image",
      search: "search_products",
      cart: "get_cart",
      payment: "charge_payment",
      order: "place_order",
    },
    orderBeforePayment: true,
    image: { format: "heic", scale: "3x" },
    layout: { view_count: "62" },
  }),
  flows: standardFlows(
    {
      screen: {
        login: "login",
        home: "home",
        products: "productList",
        search: "search",
        product_detail: "productDetail",
        cart: "cart",
        checkout: "checkout",
        payment: "payment",
        order_confirmation: "orderConfirmation",
        profile: "profile",
        orders: "orders",
      },
      http: {
        products: "products_list",
        cart_add: "add_to_cart",
        cart_update: "update_cart_item",
        cart_remove: "remove_cart_item",
        promo: "apply_promo",
        orders: "get_orders",
        login: "login",
        profile: "get_profile",
        preferences: "update_preferences",
      },
      span: {
        product_load: "product_load",
        checkout_flow: "checkout_flow",
        search_query: "search_query",
        cart_refresh: "cart_refresh",
      },
      wallet: "radio_apple_pay",
    },
    {
      checkoutCrash: {
        steps: [{ kind: "exception", exception: "checkout_nil_unwrap" }],
      },
      detailCrash: {
        abortBefore: SPAN_STEPS.productDecode,
        steps: [{ kind: "exception", exception: "product_image_bad_access" }],
      },
      cartHandled: {
        loadFailure: [{ kind: "exception", exception: "cart_request_timeout" }],
      },
      reports: {
        profile: (j) =>
          j
            .tap("switch_promos")
            .http("preferences")
            .tap("row_orders")
            .screen("orders")
            .http("orders")
            .back()
            .http("profile")
            .variant(null)
            .bugReport(
              "I turned on Offers and promotions, checked my orders, and when I came back to Profile the switch was off again. Third time now.",
            ),
        payment: (j) =>
          j
            .tap("btn_place_order")
            .tap("btn_place_order")
            .bugReport(
              "Tapped Pay with Apple Pay twice and the Apple Pay sheet closed right away both times. Had to switch to my Visa to place the order.",
            ),
      },
      keys: {
        checkout_crash: "checkout_crash",
        detail_crash: "product_detail_crash",
        cart_handled: "cart_timeout",
        payment_bug: "apple_pay_bug_report",
        purchase: "full_purchase",
        search: "search_and_browse",
        quick_purchase: "quick_purchase",
        profile: "profile_browse",
      },
    },
  ),

  sessions: [
    {
      flow: "checkout_crash",
      user: 0,
      version: 0,
      agoMinutes: 12,
      launch: "cold",
    },
    {
      flow: "checkout_crash",
      user: 1,
      version: 2,
      agoMinutes: 20000,
      launch: "warm",
    },
    {
      flow: "apple_pay_bug_report",
      user: 3,
      version: 0,
      agoMinutes: 55,
      launch: "warm",
    },
    {
      flow: "product_detail_crash",
      user: 2,
      version: 0,
      agoMinutes: 95,
      launch: "cold",
    },
    {
      flow: "cart_timeout",
      user: 4,
      version: 0,
      agoMinutes: 130,
      launch: "hot",
    },
    {
      flow: "full_purchase",
      user: 1,
      version: 0,
      agoMinutes: 165,
      launch: "cold",
      memoryLeak: true,
    },
    {
      flow: "search_and_browse",
      user: 2,
      version: 1,
      agoMinutes: 200,
      launch: "hot",
      memoryLeak: true,
    },
    {
      flow: "quick_purchase",
      user: 0,
      version: 0,
      agoMinutes: 235,
      launch: "cold",
    },
    {
      flow: "profile_browse",
      user: 3,
      version: 1,
      agoMinutes: 2900,
      launch: "warm",
    },
    {
      flow: "full_purchase",
      user: 4,
      version: 1,
      agoMinutes: 9000,
      launch: "hot",
    },
  ],
  launch: {
    coldMs: [400, 900],
    warmMs: [200, 500],
    hotMs: [80, 220],
  },
  threadNames: {
    main: "com.apple.main-thread",
    network: "com.apple.NSURLSession-delegate",
  },
};
