FROM public.ecr.aws/docker/library/gradle:8-jdk17 AS build
LABEL org.opencontainers.image.source=https://github.com/measure-sh/measure
LABEL org.opencontainers.image.description="Measure Symbolicator Retrace"
LABEL org.opencontainers.image.licenses=Apache-2.0
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN --mount=type=cache,target=/root/.gradle gradle buildFatJar --no-daemon

FROM public.ecr.aws/docker/library/eclipse-temurin:17
EXPOSE 8181:8181
RUN mkdir /app
COPY --from=build /home/gradle/src/build/libs/*.jar /app/app.jar
ENTRYPOINT ["java","-jar","/app/app.jar"]
