/**
 * Exercises the standalone-markdown transform behind the llms routes.
 * Url absolutizing and JSX comment removal operate on the parsed tree,
 * not on the text, so link-like or comment-shaped text inside code must
 * come through untouched.
 */
import { describe, expect, it } from "@jest/globals";

import { toStandaloneMarkdown } from "@/app/utils/llms/standalone_markdown";

const SITE = "https://measure.sh";

describe("toStandaloneMarkdown", () => {
  it("absolutizes root-relative links, images, and reference definitions", () => {
    const out = toStandaloneMarkdown(
      [
        "See [config](/docs/configuration-options).",
        "",
        "![shot](/docs/assets/shot.png)",
        "",
        "[ref]: /docs/hosting",
      ].join("\n"),
      SITE,
    );

    expect(out).toContain(`[config](${SITE}/docs/configuration-options)`);
    expect(out).toContain(`![shot](${SITE}/docs/assets/shot.png)`);
    expect(out).toContain(`[ref]: ${SITE}/docs/hosting`);
  });

  it("rewrites both urls of an image wrapped in a link", () => {
    const out = toStandaloneMarkdown(
      "[![badge](/img/badge.png)](/docs/target)",
      SITE,
    );

    expect(out).toContain(`![badge](${SITE}/img/badge.png)`);
    expect(out).toContain(`](${SITE}/docs/target)`);
  });

  it("leaves external, protocol-relative, and anchor urls alone", () => {
    const out = toStandaloneMarkdown(
      [
        "[ext](https://github.com/measure-sh)",
        "",
        "[proto](//example.com/x)",
        "",
        "[anchor](#setup)",
      ].join("\n"),
      SITE,
    );

    expect(out).toContain("(https://github.com/measure-sh)");
    expect(out).toContain("(//example.com/x)");
    expect(out).toContain("(#setup)");
    expect(out).not.toContain(SITE);
  });

  it("does not touch link-like text inside code", () => {
    const out = toStandaloneMarkdown(
      [
        "```md",
        "[docs](/docs/hosting)",
        "```",
        "",
        "Inline `[x](/y)` too.",
      ].join("\n"),
      SITE,
    );

    expect(out).toContain("[docs](/docs/hosting)");
    expect(out).toContain("`[x](/y)`");
  });

  it("drops JSX comments but keeps components and expressions", () => {
    const out = toStandaloneMarkdown(
      [
        "{/* This page is generated by Fumadocs */}",
        "",
        '<Callout type="info">Body</Callout>',
        "",
        "Before {/* inline note */} after.",
      ].join("\n"),
      SITE,
    );

    expect(out).not.toContain("generated by Fumadocs");
    expect(out).not.toContain("inline note");
    expect(out).toContain('<Callout type="info">Body</Callout>');
    expect(out).toContain("Before");
    expect(out).toContain("after.");
  });

  it("does not strip comment-shaped text inside code", () => {
    const out = toStandaloneMarkdown(
      ["```jsx", "{/* keep me */}", "```"].join("\n"),
      SITE,
    );

    expect(out).toContain("{/* keep me */}");
  });

  it("throws on text that is not valid MDX", () => {
    // The entity-escaped `>` after the self-closing slash is a sequence
    // fumadocs' processed-markdown serializer emits for <br /> inside
    // table cells; the MDX grammar rejects it. Serving such a page
    // silently degraded is worse than failing the build, so it throws.
    expect(() =>
      toStandaloneMarkdown("Broken <br /&#x3E; tag.", SITE),
    ).toThrow();
  });

  it("keeps GFM tables intact", () => {
    const out = toStandaloneMarkdown(
      ["| a | b |", "| - | - |", "| 1 | [x](/y) |"].join("\n"),
      SITE,
    );

    // The serializer pads cells to the widest column, so compare with
    // runs of spaces collapsed.
    expect(out.replace(/ +/g, " ")).toContain("| a | b |");
    expect(out).toContain(`[x](${SITE}/y)`);
  });
});
