-- migrate:up
ALTER TABLE default.events
ADD COLUMN http.url String,
ADD COLUMN http.method LowCardinality(FixedString(16)),
ADD COLUMN http.status_code LowCardinality(UInt16),
ADD COLUMN http.request_body_size UInt64,
ADD COLUMN http.response_body_size UInt64,
ADD COLUMN http.request_timestamp DateTime64(9, 'UTC'),
ADD COLUMN http.response_timestamp DateTime64(9, 'UTC'),
ADD COLUMN http.start_time UInt64,
ADD COLUMN http.end_time UInt64,
ADD COLUMN http.dns_start UInt64,
ADD COLUMN http.dns_end UInt64,
ADD COLUMN http.connect_start UInt64,
ADD COLUMN http.connect_end UInt64,
ADD COLUMN http.request_start UInt64,
ADD COLUMN http.request_end UInt64,
ADD COLUMN http.request_headers_start UInt64,
ADD COLUMN http.request_headers_end UInt64,
ADD COLUMN http.request_body_start UInt64,
ADD COLUMN http.request_body_end UInt64,
ADD COLUMN http.response_start UInt64,
ADD COLUMN http.response_end UInt64,
ADD COLUMN http.response_headers_start UInt64,
ADD COLUMN http.response_headers_end UInt64,
ADD COLUMN http.response_body_start UInt64,
ADD COLUMN http.response_body_end UInt64,
ADD COLUMN http.request_headers_size UInt64,
ADD COLUMN http.response_headers_size UInt64,
ADD COLUMN http.failure_reason String,
ADD COLUMN http.failure_description String,
ADD COLUMN http_request_headers Map(String, String),
ADD COLUMN http_response_headers Map(String, String),
ADD COLUMN http.client LowCardinality(FixedString(32));


-- migrate:down
ALTER TABLE default.events
DROP COLUMN http.url,
DROP COLUMN http.method,
DROP COLUMN http.status_code,
DROP COLUMN http.request_body_size,
DROP COLUMN http.response_body_size,
DROP COLUMN http.request_timestamp,
DROP COLUMN http.response_timestamp,
DROP COLUMN http.start_time,
DROP COLUMN http.end_time,
DROP COLUMN http.dns_start,
DROP COLUMN http.dns_end,
DROP COLUMN http.connect_start,
DROP COLUMN http.connect_end,
DROP COLUMN http.request_start,
DROP COLUMN http.request_end,
DROP COLUMN http.request_headers_start,
DROP COLUMN http.request_headers_end,
DROP COLUMN http.request_body_start,
DROP COLUMN http.request_body_end,
DROP COLUMN http.response_start,
DROP COLUMN http.response_end,
DROP COLUMN http.response_headers_start,
DROP COLUMN http.response_headers_end,
DROP COLUMN http.response_body_start,
DROP COLUMN http.response_body_end,
DROP COLUMN http.request_headers_size,
DROP COLUMN http.response_headers_size,
DROP COLUMN http.failure_reason,
DROP COLUMN http.failure_description,
DROP COLUMN http_request_headers,
DROP COLUMN http_response_headers,
DROP COLUMN http.client;
