-- migrate:up
create table if not exists spans
(
    `team_id` LowCardinality(UUID) comment 'unique id of the team' CODEC(LZ4),
    `app_id` LowCardinality(UUID) comment 'unique id of the app' CODEC(LZ4),
    `inserted_at` DateTime64(3, 'UTC') DEFAULT now64() comment 'original event insertion timestamp' CODEC(Delta(8), ZSTD(3)),
    `span_name` LowCardinality(String) comment 'name of the span' CODEC(ZSTD(3)),
    `span_id` FixedString(16) comment 'id of the span' CODEC(ZSTD(3)),
    `parent_id` FixedString(16) comment 'id of the parent span' CODEC(ZSTD(3)),
    `trace_id` FixedString(32) comment 'id of the trace' CODEC(ZSTD(3)),
    `session_id` UUID comment 'session id' CODEC(LZ4),
    `status` UInt8 comment 'status of the span 0 (Unset), 1 (Ok) or 2 (Error)' CODEC(ZSTD(3)),
    `start_time` DateTime64(3, 'UTC') comment 'start time' CODEC(DoubleDelta, ZSTD(3)),
    `end_time` DateTime64(3, 'UTC') comment 'end time' CODEC(DoubleDelta, ZSTD(3)),
    `checkpoints` Array(Tuple(String, DateTime64(3, 'UTC'))) comment 'array of checkpoints - {name, timestamp}' CODEC(ZSTD(3)),
    `attribute.app_unique_id` LowCardinality(String) comment 'app bundle identifier' CODEC(ZSTD(3)),
    `attribute.installation_id` UUID comment 'unique id for an installation of an app, generated by sdk' CODEC(LZ4),
    `attribute.user_id` LowCardinality(String) comment 'attributed user id' CODEC(ZSTD(3)),
    `attribute.measure_sdk_version` LowCardinality(String) comment 'measure sdk version identifier' CODEC(ZSTD(3)),
    `attribute.app_version` Tuple(LowCardinality(String), LowCardinality(String)) comment 'composite app version' CODEC(ZSTD(3)),
    `attribute.os_version` Tuple(LowCardinality(String), LowCardinality(String)) comment 'composite os version' CODEC(ZSTD(3)),
    `attribute.platform` LowCardinality(String) comment 'platform identifier' CODEC(ZSTD(3)),
    `attribute.thread_name` String comment 'thread on which the span was captured' CODEC(ZSTD(3)),
    `attribute.country_code` LowCardinality(String) comment 'country code' CODEC(ZSTD(3)),
    `attribute.network_provider` LowCardinality(String) comment 'name of the network service provider' CODEC(ZSTD(3)),
    `attribute.session_start_time` DateTime64(3, 'UTC') comment 'start time of the session containing this span' CODEC(DoubleDelta, ZSTD(3)),
    `attribute.network_type` LowCardinality(String) comment 'wifi, cellular, vpn and so on' CODEC(ZSTD(3)),
    `attribute.network_generation` LowCardinality(String) comment '2g, 3g, 4g and so on' CODEC(ZSTD(3)),
    `attribute.device_name` LowCardinality(String) comment 'name of the device' CODEC(ZSTD(3)),
    `attribute.device_model` LowCardinality(String) comment 'model of the device' CODEC(ZSTD(3)),
    `attribute.device_manufacturer` LowCardinality(String) comment 'manufacturer of the device' CODEC(ZSTD(3)),
    `attribute.device_locale` LowCardinality(String) comment 'rfc 5646 locale string' CODEC(ZSTD(3)),
    `attribute.device_low_power_mode` Bool comment 'true if device is in power saving mode' CODEC(ZSTD(3)),
    `attribute.device_thermal_throttling_enabled` Bool comment 'true if device is has thermal throttling enabled' CODEC(ZSTD(3)),
    `user_defined_attribute` Map(LowCardinality(String), Tuple(
        Enum8('string' = 1, 'int64' = 2, 'float64' = 3, 'bool' = 4),
        String)) comment 'user defined attributes' CODEC(ZSTD(3)),
    index span_name_bloom_idx span_name type bloom_filter(0.025) granularity 2,
    index span_id_bloom_idx span_id type bloom_filter(0.025) granularity 2,
    index trace_id_bloom_idx trace_id type bloom_filter(0.01) granularity 1,
    index session_id_bloom_idx session_id type bloom_filter(0.01) granularity 2,
    index parent_id_bloom_idx parent_id type bloom_filter(0.025) granularity 2,
    index start_time_minmax_idx start_time type minmax granularity 1,
    index end_time_minmax_idx end_time type minmax granularity 1,
    index os_version_set_idx `attribute.os_version` type set(100) granularity 2,
    index country_code_set_idx `attribute.country_code` type set(1000) granularity 2,
    index network_provider_set_idx `attribute.network_provider` type set(5000) granularity 2,
    index network_type_set_idx `attribute.network_type` type set(100) granularity 2,
    index network_generation_set_idx `attribute.network_generation` type set(100) granularity 2,
    index device_locale_set_idx `attribute.device_locale` type set(1000) granularity 2,
    index device_manufacturer_set_idx `attribute.device_manufacturer` type set(2000) granularity 2,
    index device_name_set_idx `attribute.device_name` type set(2000) granularity 2,
    index user_defined_attribute_key_bloom_idx mapKeys(user_defined_attribute) type bloom_filter(0.01) granularity 8
)
engine = ReplacingMergeTree
partition by toYYYYMM(start_time)
primary key (team_id, app_id, attribute.app_version.1, attribute.app_version.2)
order by (team_id, app_id, attribute.app_version.1, attribute.app_version.2, span_name, start_time, trace_id, span_id)
settings index_granularity = 8192
comment 'spans table';

-- migrate:down
drop table if exists spans;
