-- migrate:up
CREATE TABLE if not exists spans_rmt
(
`team_id` UUID COMMENT 'unique id of the team' CODEC (ZSTD (3)),
`app_id` UUID COMMENT 'unique id of the app' CODEC (ZSTD (3)),
`inserted_at` DateTime DEFAULT now() COMMENT 'original event insertion timestamp' CODEC(Delta, ZSTD(3)),
`span_name` LowCardinality (FixedString (128)) COMMENT 'name of the span' CODEC (ZSTD (3)),
`span_id` FixedString (16) COMMENT 'id of the span' CODEC (ZSTD (3)),
`parent_id` FixedString (16) COMMENT 'id of the parent span' CODEC (ZSTD (3)),
`trace_id` FixedString (32) COMMENT 'id of the trace' CODEC (ZSTD (3)),
`session_id` UUID COMMENT 'session id' CODEC (ZSTD (3)),
`status` UInt8 COMMENT 'status of the span 0 (Unset), 1 (Ok) or 2 (Error)' CODEC (ZSTD (3)),
`start_time` DateTime64 (9,
'UTC') COMMENT 'start time' CODEC (DoubleDelta,
ZSTD (3)),
`end_time` DateTime64 (9,
'UTC') COMMENT 'end time' CODEC (DoubleDelta,
ZSTD (3)),
`checkpoints` Array (Tuple (
String,
DateTime64 (9,
'UTC'))) COMMENT 'array of checkpoints - {name, timestamp}' CODEC (ZSTD (3)),
`attribute.app_unique_id` LowCardinality (FixedString (128)) COMMENT 'app bundle identifier' CODEC (ZSTD (3)),
`attribute.installation_id` UUID COMMENT 'unique id for an installation of an app, generated by sdk' CODEC (ZSTD (3)),
`attribute.user_id` LowCardinality (String) COMMENT 'attributed user id' CODEC (ZSTD (3)),
`attribute.measure_sdk_version` LowCardinality (FixedString (16)) COMMENT 'measure sdk version identifier' CODEC (ZSTD (3)),
`attribute.app_version` Tuple (
LowCardinality (String),
LowCardinality (String)) COMMENT 'composite app version' CODEC (ZSTD (3)),
`attribute.os_version` Tuple (
LowCardinality (String),
LowCardinality (String)) COMMENT 'composite os version' CODEC (ZSTD (3)),
`attribute.platform` LowCardinality (FixedString (32)) COMMENT 'platform identifier' CODEC (ZSTD (3)),
`attribute.thread_name` FixedString (64) COMMENT 'thread on which the span was captured' CODEC (ZSTD (3)),
`attribute.country_code` LowCardinality (String) COMMENT 'country code' CODEC (ZSTD (3)),
`attribute.network_provider` LowCardinality (String) COMMENT 'name of the network service provider' CODEC (ZSTD (3)),
`attribute.network_type` LowCardinality (String) COMMENT 'wifi, cellular, vpn and so on' CODEC (ZSTD (3)),
`attribute.network_generation` LowCardinality (String) COMMENT '2g, 3g, 4g and so on' CODEC (ZSTD (3)),
`attribute.device_name` LowCardinality (String) COMMENT 'name of the device' CODEC (ZSTD (3)),
`attribute.device_model` LowCardinality (String) COMMENT 'model of the device' CODEC (ZSTD (3)),
`attribute.device_manufacturer` LowCardinality (String) COMMENT 'manufacturer of the device' CODEC (ZSTD (3)),
`attribute.device_locale` LowCardinality (String) COMMENT 'rfc 5646 locale string' CODEC (ZSTD (3)),
`attribute.device_low_power_mode` Bool COMMENT 'true if device is in power saving mode' CODEC (ZSTD (3)),
`attribute.device_thermal_throttling_enabled` Bool COMMENT 'true if device is has thermal throttling enabled' CODEC (ZSTD (3)),
`user_defined_attribute` Map (LowCardinality (String), Tuple (
Enum8 ('string' = 1, 'int64' = 2, 'float64' = 3, 'bool' = 4),
String)) COMMENT 'user defined attributes' CODEC (ZSTD (3)),
INDEX team_id_idx `team_id` TYPE bloom_filter(0.01) GRANULARITY 8,
INDEX span_name_bloom_idx span_name TYPE bloom_filter GRANULARITY 2,
INDEX span_id_bloom_idx span_id TYPE bloom_filter GRANULARITY 2,
INDEX trace_id_bloom_idx trace_id TYPE bloom_filter GRANULARITY 2,
INDEX parent_id_bloom_idx parent_id TYPE bloom_filter GRANULARITY 2,
INDEX start_time_minmax_idx start_time TYPE minmax GRANULARITY 2,
INDEX end_time_minmax_idx end_time TYPE minmax GRANULARITY 2,
INDEX user_defined_attribute_key_bloom_idx mapKeys (user_defined_attribute) TYPE bloom_filter (0.01) GRANULARITY 16,
INDEX user_defined_attribute_key_minmax_idx mapKeys (user_defined_attribute) TYPE minmax GRANULARITY 16
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMMDD (start_time)
ORDER BY (app_id, span_name, start_time, end_time, trace_id, span_id)
SETTINGS index_granularity = 8192
COMMENT 'spans table';

-- migrate:down
drop table if exists spans_rmt;
