-- migrate:up
alter table span_metrics_mv modify query
SELECT
  team_id,
  app_id,
  span_name,
  span_id,
  status,
  toStartOfFifteenMinutes(start_time) AS timestamp,
  attribute.app_version AS app_version,
  attribute.os_version AS os_version,
  attribute.country_code AS country_code,
  attribute.network_provider AS network_provider,
  attribute.network_type AS network_type,
  attribute.network_generation AS network_generation,
  attribute.device_locale AS device_locale,
  attribute.device_manufacturer AS device_manufacturer,
  attribute.device_name AS device_name,
  attribute.device_low_power_mode AS device_low_power_mode,
  attribute.device_thermal_throttling_enabled AS device_thermal_throttling_enabled,
  quantileState(0.5)(dateDiff('ms', start_time, end_time)) AS p50,
  quantileState(0.9)(dateDiff('ms', start_time, end_time)) AS p90,
  quantileState(0.95)(dateDiff('ms', start_time, end_time)) AS p95,
  quantileState(0.99)(dateDiff('ms', start_time, end_time)) AS p99
FROM spans
GROUP BY
  team_id,
  app_id,
  span_name,
  span_id,
  status,
  timestamp,
  app_version,
  os_version,
  country_code,
  network_provider,
  network_type,
  network_generation,
  device_locale,
  device_manufacturer,
  device_name,
  device_low_power_mode,
  device_thermal_throttling_enabled
ORDER BY
  app_id ASC,
  span_name ASC,
  span_id ASC,
  status ASC,
  timestamp ASC,
  app_version ASC,
  os_version ASC,
  country_code ASC,
  network_provider ASC,
  network_type ASC,
  network_generation ASC,
  device_locale ASC,
  device_manufacturer ASC,
  device_name ASC,
  device_low_power_mode ASC,
  device_thermal_throttling_enabled ASC;

-- migrate:down
alter table span_metrics_mv modify query
SELECT
  app_id,
  span_name,
  span_id,
  status,
  toStartOfFifteenMinutes(start_time) AS timestamp,
  attribute.app_version AS app_version,
  attribute.os_version AS os_version,
  attribute.country_code AS country_code,
  attribute.network_provider AS network_provider,
  attribute.network_type AS network_type,
  attribute.network_generation AS network_generation,
  attribute.device_locale AS device_locale,
  attribute.device_manufacturer AS device_manufacturer,
  attribute.device_name AS device_name,
  attribute.device_low_power_mode AS device_low_power_mode,
  attribute.device_thermal_throttling_enabled AS device_thermal_throttling_enabled,
  quantileState(0.5)(dateDiff('ms', start_time, end_time)) AS p50,
  quantileState(0.9)(dateDiff('ms', start_time, end_time)) AS p90,
  quantileState(0.95)(dateDiff('ms', start_time, end_time)) AS p95,
  quantileState(0.99)(dateDiff('ms', start_time, end_time)) AS p99
FROM spans
GROUP BY
  app_id,
  span_name,
  span_id,
  status,
  timestamp,
  app_version,
  os_version,
  country_code,
  network_provider,
  network_type,
  network_generation,
  device_locale,
  device_manufacturer,
  device_name,
  device_low_power_mode,
  device_thermal_throttling_enabled
ORDER BY
  app_id ASC,
  span_name ASC,
  span_id ASC,
  status ASC,
  timestamp ASC,
  app_version ASC,
  os_version ASC,
  country_code ASC,
  network_provider ASC,
  network_type ASC,
  network_generation ASC,
  device_locale ASC,
  device_manufacturer ASC,
  device_name ASC,
  device_low_power_mode ASC,
  device_thermal_throttling_enabled ASC;
