-- migrate:up
create materialized view if not exists sessions_span_mv to sessions
(
    `session_id`                    UUID,
    `team_id`                       LowCardinality(UUID),
    `app_id`                        LowCardinality(UUID),
    `first_event_timestamp`         SimpleAggregateFunction(min, DateTime64(3, 'UTC')),
    `last_event_timestamp`          SimpleAggregateFunction(max, DateTime64(3, 'UTC')),
    `app_version`                   Tuple(String, String),
    `os_version`                    Tuple(String, String),
    `country_codes`                 SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `network_providers`             SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `network_types`                 SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `network_generations`           SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `device_locales`                SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `device_manufacturer`           String,
    `device_name`                   String,
    `device_model`                  String,
    `user_ids`                      SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `unique_types`                  SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `unique_custom_type_names`      SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `unique_strings`                SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `unique_view_classnames`        SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `unique_subview_classnames`     SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `unique_unhandled_exceptions`   SimpleAggregateFunction(groupUniqArrayArray, Array(Tuple(String, String, String, String, String))),
    `unique_handled_exceptions`     SimpleAggregateFunction(groupUniqArrayArray, Array(Tuple(String, String, String, String, String))),
    `unique_errors`                 SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `unique_anrs`                   SimpleAggregateFunction(groupUniqArrayArray, Array(Tuple(String, String, String, String, String))),
    `unique_click_targets`          SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `unique_longclick_targets`      SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `unique_scroll_targets`         SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
    `event_count`                   SimpleAggregateFunction(sum, UInt64),
    `crash_count`                   SimpleAggregateFunction(sum, UInt64),
    `anr_count`                     SimpleAggregateFunction(sum, UInt64),
    `bug_report_count`              SimpleAggregateFunction(sum, UInt64),
    `background_count`              SimpleAggregateFunction(sum, UInt64),
    `foreground_count`              SimpleAggregateFunction(sum, UInt64),
    `event_type_counts`             SimpleAggregateFunction(sumMap, Map(String, UInt64))
)
as select
    session_id,
    team_id,
    app_id,
    minSimpleState(start_time)                                                              as first_event_timestamp,
    maxSimpleState(end_time)                                                                as last_event_timestamp,
    argMax(attribute.app_version, start_time)                                               as app_version,
    argMax(attribute.os_version, start_time)                                                as os_version,
    groupUniqArrayArraySimpleState([attribute.country_code])                                as country_codes,
    groupUniqArrayArraySimpleState([attribute.network_provider])                            as network_providers,
    groupUniqArrayArraySimpleState([attribute.network_type])                                as network_types,
    groupUniqArrayArraySimpleState([attribute.network_generation])                          as network_generations,
    groupUniqArrayArraySimpleState([attribute.device_locale])                               as device_locales,
    argMax(attribute.device_manufacturer, start_time)                                       as device_manufacturer,
    argMax(attribute.device_name, start_time)                                               as device_name,
    argMax(attribute.device_model, start_time)                                              as device_model,
    groupUniqArrayArraySimpleState([attribute.user_id])                                     as user_ids,
    groupUniqArrayArraySimpleState(cast('[]', 'Array(String)'))                             as unique_types,
    groupUniqArrayArraySimpleState(cast('[]', 'Array(String)'))                             as unique_custom_type_names,
    groupUniqArrayArraySimpleState(cast('[]', 'Array(String)'))                             as unique_strings,
    groupUniqArrayArraySimpleState(cast('[]', 'Array(String)'))                             as unique_view_classnames,
    groupUniqArrayArraySimpleState(cast('[]', 'Array(String)'))                             as unique_subview_classnames,
    groupUniqArrayArraySimpleState(cast('[]', 'Array(Tuple(String, String, String, String, String))')) as unique_unhandled_exceptions,
    groupUniqArrayArraySimpleState(cast('[]', 'Array(Tuple(String, String, String, String, String))')) as unique_handled_exceptions,
    groupUniqArrayArraySimpleState(cast('[]', 'Array(String)'))                             as unique_errors,
    groupUniqArrayArraySimpleState(cast('[]', 'Array(Tuple(String, String, String, String, String))')) as unique_anrs,
    groupUniqArrayArraySimpleState(cast('[]', 'Array(String)'))                             as unique_click_targets,
    groupUniqArrayArraySimpleState(cast('[]', 'Array(String)'))                             as unique_longclick_targets,
    groupUniqArrayArraySimpleState(cast('[]', 'Array(String)'))                             as unique_scroll_targets,
    sumSimpleState(toUInt64(0))                                                             as event_count,
    sumSimpleState(toUInt64(0))                                                             as crash_count,
    sumSimpleState(toUInt64(0))                                                             as anr_count,
    sumSimpleState(toUInt64(0))                                                             as bug_report_count,
    sumSimpleState(toUInt64(0))                                                             as background_count,
    sumSimpleState(toUInt64(0))                                                             as foreground_count,
    sumMapSimpleState(cast(map(), 'Map(String, UInt64)'))                                   as event_type_counts
from spans
group by
    team_id,
    app_id,
    attribute.app_version,
    session_id;


-- migrate:down
drop view if exists sessions_span_mv;
