-- migrate:up
alter table sessions_mv modify query
select
    session_id,
    team_id,
    app_id,
    minSimpleState(timestamp)                                                                                                                                                                                                as first_event_timestamp,
    maxSimpleState(timestamp)                                                                                                                                                                                                as last_event_timestamp,
    (attribute.app_version, attribute.app_build)                                                                                                                                                                             as app_version,
    (attribute.os_name, attribute.os_version)                                                                                                                                                                                as os_version,
    groupUniqArrayArraySimpleState(if(inet.country_code != '', [inet.country_code], []))                                                                                                                                     as country_codes,
    groupUniqArrayArraySimpleState(if(attribute.network_provider != '', [attribute.network_provider], []))                                                                                                                   as network_providers,
    groupUniqArrayArraySimpleState(if(attribute.network_type != '', [attribute.network_type], []))                                                                                                                           as network_types,
    groupUniqArrayArraySimpleState(if(attribute.network_generation != '', [attribute.network_generation], []))                                                                                                               as network_generations,
    groupUniqArrayArraySimpleState([attribute.device_locale])                                                                                                                                                                as device_locales,
    argMax(attribute.device_name, timestamp)                                                                                                                                                                                 as device_name,
    argMax(attribute.device_manufacturer, timestamp)                                                                                                                                                                         as device_manufacturer,
    argMax(attribute.device_model, timestamp)                                                                                                                                                                                as device_model,
    groupUniqArrayArraySimpleState(if(attribute.user_id != '', [attribute.user_id], []))                                                                                                                                     as user_ids,
    groupUniqArrayArraySimpleState([type])                                                                                                                                                                                   as unique_types,
    groupUniqArrayArraySimpleState(if(type = 'custom', [custom.name], []))                                                                                                                                                   as unique_custom_type_names,
    groupUniqArrayArraySimpleState(if(`string.string` != '', [`string.string`], []))                                                                                                                                         as unique_strings,
    groupUniqArrayArraySimpleState(if((type = 'lifecycle_activity') and (lifecycle_activity.class_name != ''), [lifecycle_activity.class_name], []))                                                                         as unique_view_classnames,
    groupUniqArrayArraySimpleState(if((type = 'lifecycle_fragment') and (lifecycle_fragment.class_name != ''), [lifecycle_fragment.class_name], []))                                                                         as unique_subview_classnames,
    groupUniqArrayArraySimpleState(if((type = 'exception') and (exception.handled = 0), [(simpleJSONExtractString(`exception.exceptions`, 'type'), simpleJSONExtractString(`exception.exceptions`, 'message'), simpleJSONExtractString(`exception.exceptions`, 'file_name'), simpleJSONExtractString(`exception.exceptions`, 'class_name'), simpleJSONExtractString(`exception.exceptions`, 'method_name'))], [])) as unique_unhandled_exceptions,
    groupUniqArrayArraySimpleState(if((type = 'exception') and (exception.handled = 1), [(simpleJSONExtractString(`exception.exceptions`, 'type'), simpleJSONExtractString(`exception.exceptions`, 'message'), simpleJSONExtractString(`exception.exceptions`, 'file_name'), simpleJSONExtractString(`exception.exceptions`, 'class_name'), simpleJSONExtractString(`exception.exceptions`, 'method_name'))], [])) as unique_handled_exceptions,
    groupUniqArrayArraySimpleState(if((type = 'exception') and (exception.error != '') and (exception.error != '{}'), [exception.error], []))                                                                                 as unique_errors,
    groupUniqArrayArraySimpleState(if(type = 'anr', [(simpleJSONExtractString(`anr.exceptions`, 'type'), simpleJSONExtractString(`anr.exceptions`, 'message'), simpleJSONExtractString(`anr.exceptions`, 'file_name'), simpleJSONExtractString(`anr.exceptions`, 'class_name'), simpleJSONExtractString(`anr.exceptions`, 'method_name'))], []))                                                                          as unique_anrs,
    groupUniqArrayArraySimpleState(if(type = 'gesture_click', [(gesture_click.target, gesture_click.target_id)], []))                                                                                                        as unique_click_targets,
    groupUniqArrayArraySimpleState(if(type = 'gesture_long_click', [(gesture_long_click.target, gesture_long_click.target_id)], []))                                                                                         as unique_longclick_targets,
    groupUniqArrayArraySimpleState(if(type = 'gesture_scroll', [(gesture_scroll.target, gesture_scroll.target_id)], []))                                                                                                     as unique_scroll_targets,
    sumSimpleState(toUInt64(1))                                                                                                                                                                                              as event_count,
    sumSimpleState(if((type = 'exception') and (exception.handled = 0), toUInt64(1), toUInt64(0)))                                                                                                                           as crash_count,
    sumSimpleState(if(type = 'anr', toUInt64(1), toUInt64(0)))                                                                                                                                                              as anr_count,
    sumSimpleState(if(type = 'bug_report', toUInt64(1), toUInt64(0)))                                                                                                                                                       as bug_report_count,
    sumSimpleState(if((type = 'lifecycle_app') and (lifecycle_app.type = 'background'), toUInt64(1), toUInt64(0)))                                                                                                           as background_count,
    sumSimpleState(if((type = 'lifecycle_app') and (lifecycle_app.type = 'foreground'), toUInt64(1), toUInt64(0)))                                                                                                           as foreground_count,
    sumMapSimpleState(map(type, toUInt64(1)))                                                                                                                                                                                as event_type_counts
from events
group by
    team_id,
    app_id,
    session_id,
    app_version,
    os_version;

-- migrate:down
alter table sessions_mv modify query
SELECT
    team_id,
    app_id,
    session_id,
    min(timestamp) AS first_event_timestamp,
    minSimpleState(timestamp) as start_time,
    maxSimpleState(timestamp) as end_time,
    anyLast((toString(attribute.app_version), toString(attribute.app_build))) AS app_version,
    anyLast((toString(attribute.os_name), toString(attribute.os_version))) AS os_version,
    anyLast(toString(inet.country_code)) AS country_code,
    anyLast(toString(attribute.network_provider)) AS network_provider,
    anyLast(toString(attribute.network_type)) AS network_type,
    anyLast(toString(attribute.network_generation)) AS network_generation,
    anyLast(toString(attribute.device_locale)) AS device_locale,
    anyLast(toString(attribute.device_manufacturer)) AS device_manufacturer,
    anyLast(toString(attribute.device_name)) AS device_name,
    anyLast(toString(attribute.device_model)) AS device_model,
    anyLast(toString(attribute.user_id)) AS user_id,
    groupUniqArrayArraySimpleState(10)([toString(type)]) AS unique_types,
    groupUniqArrayArraySimpleState(10)([toString(string.string)]) AS unique_strings,
    groupUniqArrayArraySimpleStateIf(10)([toString(lifecycle_activity.class_name)], (type = 'lifecycle_activity') AND (lifecycle_activity.class_name != '')) AS unique_view_classnames,
    groupUniqArrayArraySimpleStateIf(10)([toString(lifecycle_fragment.class_name)], (type = 'lifecycle_fragment') AND (lifecycle_fragment.class_name != '')) AS unique_subview_classnames,
    groupUniqArrayArraySimpleStateIf(5)([(simpleJSONExtractString(exception.exceptions, 'type'), simpleJSONExtractString(exception.exceptions, 'message'), simpleJSONExtractString(exception.exceptions, 'file_name'), simpleJSONExtractString(exception.exceptions, 'class_name'), simpleJSONExtractString(exception.exceptions, 'method_name'))], (type = 'exception') AND (exception.handled = false)) AS unique_exceptions,
    groupUniqArrayArraySimpleStateIf(5)([(simpleJSONExtractString(anr.exceptions, 'type'), simpleJSONExtractString(anr.exceptions, 'message'), simpleJSONExtractString(anr.exceptions, 'file_name'), simpleJSONExtractString(anr.exceptions, 'class_name'), simpleJSONExtractString(anr.exceptions, 'method_name'))], type = 'anr') AS unique_anrs,
    groupUniqArrayArraySimpleStateIf(5)([(toString(gesture_click.target), toString(gesture_click.target_id))], type = 'gesture_click') AS unique_click_targets,
    groupUniqArrayArraySimpleStateIf(5)([(toString(gesture_long_click.target), toString(gesture_long_click.target_id))], type = 'gesture_long_click') AS unique_longclick_targets,
    groupUniqArrayArraySimpleStateIf(5)([(toString(gesture_scroll.target), toString(gesture_scroll.target_id))], type = 'gesture_scroll') AS unique_scroll_targets,
    uniqState(id) AS event_count,
    uniqStateIf(id, (type = 'exception') AND (exception.handled = false)) AS crash_count,
    uniqStateIf(id, type = 'anr') AS anr_count
FROM events
GROUP BY
    team_id,
    app_id,
    session_id;
