# build stage
FROM --platform=$BUILDPLATFORM public.ecr.aws/docker/library/golang:alpine AS builder
ARG TARGETOS
ARG TARGETARCH
ARG TARGETTYPE
WORKDIR /go/src

# Copy dependency modules first for caching
COPY --from=libs go.mod go.sum ../libs/
COPY ["go.mod", "go.sum", "./"]

RUN go mod download

# Copy source
COPY --from=libs . ../libs/
COPY . .

RUN --mount=type=cache,target=/go/pkg/mod \
  --mount=type=cache,target=/root/.cache/go-build \
  if [ "$TARGETTYPE" = "debug" ]; then \
  CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
  go build -o /go/bin/app -v . && \
  CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
  go build -o /go/bin/symboloader-cli -v ./cmd/symboloader/; \
  else \
  CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
  go build -ldflags="-s -w" -o /go/bin/app -v . && \
  CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
  go build -ldflags="-s -w" -o /go/bin/symboloader-cli -v ./cmd/symboloader/; \
  fi

# final stage
FROM public.ecr.aws/docker/library/alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/bin/app /app
COPY --from=builder /go/bin/symboloader-cli /usr/local/bin/symboloader
ENTRYPOINT ["/app"]
EXPOSE 8083
