name: Android CI

on:
  pull_request:
    paths:
      - 'measure-android/**'
  push:
    branches:
      - 'main'
    paths:
      - 'measure-android/**'
  release:
    types: [ published ]

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: 'temurin'
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: measure-android
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run all checks
        run: ./gradlew :measure:check

  publish-android:
    runs-on: ubuntu-latest
    needs: [ checks ]
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/measure-android-') && !startsWith(github.ref, 'refs/tags/measure-android-gradle-')
    defaults:
      run:
        working-directory: measure-android
    permissions:
      contents: read
      packages: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish measure-android
        run: ./gradlew clean :measure:publish --no-daemon --no-parallel --no-configuration-cache --stacktrace

  publish-android-gradle:
    runs-on: ubuntu-latest
    needs: [ checks ]
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/measure-android-gradle-')
    defaults:
      run:
        working-directory: measure-android
    permissions:
      contents: read
      packages: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish measure-android-gradle
        run: ./gradlew clean :measure-gradle-plugin:publishMavenPublicationToGitHubPackagesRepository --no-daemon --no-parallel --no-configuration-cache --stacktrace