name: Android CI

on:
  pull_request:
    paths:
      - 'measure-android/**'
  push:
    branches:
      - 'main'
    paths:
      - 'measure-android/**'

env:
  JAVA_VERSION: 17
  CACHE_VERSION: 1

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: measure-android
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - run: ./ci-scripts/ci_clear_gradle_cache.sh
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ env.CACHE_VERSION }}-${{ hashFiles('**/**.gradle.kts', '**/gradle/wrapper/gradle-wrapper.properties', '**/libs.versions.toml') }}

      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Check lint
        run: ./gradlew :measure:lint
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: measure-android
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - run: ./ci-scripts/ci_clear_gradle_cache.sh
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ env.CACHE_VERSION }}-${{ hashFiles('**/**.gradle.kts', '**/gradle/wrapper/gradle-wrapper.properties', '**/libs.versions.toml') }}
      - name: Unit tests
        run: ./gradlew :measure:testDebugUnitTest
