name: API Server Build
on:
  push:
    paths:
      - "measure-backend/measure-go/**"
  pull_request:
    paths:
      - "measure-backend/measure-go/**"

jobs:
  build:
    name: Build & test API server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21.x"]
    defaults:
      run:
        working-directory: measure-backend/measure-go
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display go version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: Build with ${{ matrix.go-version }}
        run: go build -v ./...
      - name: Test with ${{ matrix.go-version }}
        run: go test
