on:
  pull_request:
    paths:
      - 'ios/**'
  push:
    branches:
      - 'main'
    paths:
      - 'ios/**'
    tags:
      - 'ios-*'

jobs:
  ios_lint_and_tests:
    runs-on: macos-15
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Switch to Xcode 16.4
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: Confirm Xcode Version
        run: xcodebuild -version

      - name: Show Available Simulators
        run: xcrun simctl list devices

      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project ios/MeasureSDK.xcodeproj \
            -scheme MeasureSDKTests \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.4' \
            ONLY_ACTIVE_ARCH=YES \
            -parallel-testing-enabled NO