on:
  pull_request:
    paths:
      - 'ios/**'
  push:
    branches:
      - 'main'
    paths:
      - 'ios/**'
    tags:
      - 'ios-*'

jobs:
  ios_lint_and_tests:
    runs-on: macos-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clean Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project ios/MeasureSDK.xcodeproj \
            -scheme Measure \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            -only-testing:MeasureSDKTests
            ONLY_ACTIVE_ARCH=YES
