name: Ship

on:
  workflow_dispatch:
  push:
  # push:
  #   tags:
  #     - "v*"

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get bumped version
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --bumped-version
        env:
          OUTPUT: next-version.txt

      - name: Save bumped version
        id: bumped-version
        run: |
          echo "Bumped version: $(cat next-version.txt)"
          echo "bumped_version=$(cat next-version.txt)" >> "$GITHUB_OUTPUT"

      - name: Print bumped version
        run: |
          echo "Bumped version: ${{ steps.bumped-version.outputs.bumped_version }}"

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Generate release notes
        uses: orhun/git-cliff-action@v4
        id: release-notes
        with:
          args: --verbose --latest --strip header footer
        env:
          OUTPUT: release-notes-${{ steps.bumped-version.outputs.bumped_version }}.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Print release notes
        run: |
          echo "Release notes:"
          cat release-notes-${{ steps.release-notes.outputs.content }}
